# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nvx"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Nanvix Runtime Library"
homepage.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
sys = { workspace = true, features = ["kcall"] }
talc = { workspace = true }
cfg-if = { workspace = true }
config = { workspace = true }

[features]
default = []
allocator = []
std = []
staticlib = ["allocator"]

# Logging Features
trace = ["debug"]
debug = ["info"]
info = ["warn"]
warn = ["error"]
error = ["panic"]
panic = []
