# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nvx"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Nanvix Runtime Library"
homepage.workspace = true

[dependencies]
sysalloc = { workspace = true, optional = true }
cfg-if = { workspace = true }
syslog = { workspace = true }
sys = { workspace = true, features = ["kcall"] }
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1", optional = true }

[features]
default = ["staticlib", "sysalloc"]
staticlib = []
sysalloc = ["dep:sysalloc"]
rustc-dep-of-std = [
    "core",
    "compiler_builtins/rustc-dep-of-std",
    "sysalloc/rustc-dep-of-std",
    "sys/rustc-dep-of-std",
    "syslog/rustc-dep-of-std",
    "cfg-if/rustc-dep-of-std",
]

# Logging Features
trace = ["syslog/trace", "syslog/trace"]
debug = ["syslog/debug", "syslog/debug"]
info = ["syslog/info", "syslog/info"]
warn = ["syslog/warn", "syslog/warn"]
error = ["syslog/error", "syslog/error"]
panic = ["syslog/panic", "syslog/panic"]
