# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "boottime"
version = "0.0.5"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Echo Benchmark"
homepage = "https://github.com/nanvix"

[[bin]]
name = "boottime"

[dependencies]
nvx = { path = "../../libs/nvx" }

[build-dependencies]
cc = "1.2.6"
cfg-if = "1.0.0"
