# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "boottime"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Boot Time Benchmark"
homepage.workspace = true

[[bin]]
name = "boottime"

[dependencies]
cfg-if = { workspace = true }
nvx = { workspace = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }
