# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "libc_sys_time"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "POSIX Time Types Library"
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
sys = { workspace = true }
sysapi = { workspace = true }
syscall = { workspace = true, features = ["syscall"] }
syslog = { workspace = true, default-features = true }

[features]
default = []
# Enables the use of the Rust Standard Library.
std = []

# Logging
trace = ["syslog/trace"]
debug = ["syslog/debug"]
info = ["syslog/info"]
warn = ["syslog/warn"]
error = ["syslog/error"]
panic = ["syslog/panic"]

[lints]
workspace = true
