#!/bin/bash

# This script checks code formatting before a commit.

#===================================================================================================

# Fast fail on errors, unset variables, and pipe failures.
set -euo pipefail

#===================================================================================================
# Global Variables
#===================================================================================================

# Colors
RED='\033[0;31m'    # Red
GREEN='\033[0;32m'  # Green
NC='\033[0m'        # No Color

#===================================================================================================
# Functions
#===================================================================================================

#
# DESCRIPTION
#   Prints an error message on stderr.
#
# ARGUMENTS
#   $1 - The error message to print.
#
# USAGE EXAMPLE
#   print_error "Print an error message."
#
print_error() {
    echo -e "${RED}[ERROR] ${1}${NC}" >&2
}

#
# DESCRIPTION
#   Prints a success message on stdout.
#
# ARGUMENTS
#   $1 - The success message to print.
#
# USAGE EXAMPLE
#   print_success "Print a success message."
#
print_success() {
    echo -e "${GREEN}[INFO] ${1}${NC}"
}

#===================================================================================================
# Main Script
#===================================================================================================

main() {
    # By default, use Docker to run the code formatting check.
    local build_command="./z build --with-cached-options --"

    # Check if we are not running inside a Git repository.
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        print_error "(pre-commit) This script must be run inside a Git repository."
        exit 1
    fi

    # No need to check for Docker installation or the correct Docker image here. This script uses
    # cached build options, and all necessary environment checks were already performed when the
    # build cache was created.

    # Create a temporary file to capture output.
    tmpfile="$(mktemp)"
    trap 'rm -f "$tmpfile"' EXIT

    # Run code formatting check.
    if ! eval "${build_command} format-check" >${tmpfile} 2>&1 ; then
        # Code formatting check failed, print the output.
        cat "${tmpfile}"
        print_error "(pre-commit) Format check failed. Please fix formatting before committing."
        exit 1
    fi

    print_success "(pre-commit) Code formatting check passed successfully."

    # Run code linting check.
    if ! eval "${build_command} lint-check" >${tmpfile} 2>&1 ; then
        # Code linting check failed, print the output.
        cat "${tmpfile}"
        print_error "(pre-commit) Lint check failed. Please fix linting issues before committing."
        exit 1
    fi

    print_success "(pre-commit) Code linting check passed successfully."
}

# Run the main function.
main "$@"
