#!/bin/bash

# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

# Toolchain directory.
toolchain_dir=$(pwd)/toolchain

# Check if toolchain directory exists.
if [ ! -d "$toolchain_dir" ]; then
  echo "toolchain directory not found"
  exit 1
fi

# Check if there are any untracked files as this may impact the pipeline.
if [ -n "$(git status --porcelain)" ]; then
  echo "Untracked files found, please commit or remove them before pushing."
  exit 1
fi

# Get the name of the target branch being pushed
target_branch=$(git rev-parse --abbrev-ref HEAD@{upstream})

# Check if the target branch name is "dev"
if [ "$target_branch" = "origin/dev" ]; then
  echo "Running pipeline for target branch 'dev'..."
  ./scripts/pipeline.sh $toolchain_dir
else
  echo "Target branch is not 'dev', skipping pipeline."
fi
