#!/bin/bash

# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
  last_local_ref=$local_ref
  last_local_sha=$local_sha
  last_remote_ref=$remote_ref
  last_remote_sha=$remote_sha
done

echo "last_local_ref: $last_local_ref"
echo "last_local_sha: $last_local_sha"
echo "last_remote_ref: $last_remote_ref"
echo "last_remote_sha: $last_remote_sha"

if [ "$last_local_sha" != $z40 ]
then
  if [ "$last_remote_sha" = $z40 ]
  then
    # New branch, examine all commits
    range="$last_local_sha"
  else
    # Update to existing branch.

    # Check if the target branch name is "dev"
    if [ "$last_remote_ref" = "refs/heads/dev" ]; then
      # Check if there are any untracked files as this may impact the pipeline.
      if [ -n "$(git status --porcelain)" ]; then
        echo "Untracked files found, please commit or remove them before pushing."
        exit 1
      fi

      echo "Running pipeline for target branch '$remote'..."
      ./scripts/pipeline.sh
    else
      echo "Target branch is not 'dev', skipping pipeline."
    fi
  fi
fi
