# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "linux-app"
version = "0.0.1"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Linux App Benchmark"
homepage = "https://github.com/nanvix"

[[bin]]
name = "linux-app"

[dependencies]
nvx = { path = "../../libs/nvx", features = ["allocator"] }
linuxd = { path = "../../libs/posix", default-features = false, features = [
    "syscall", "allocator"
], package = "posix" }

[build-dependencies]
cc = "1.1.24"
cfg-if = "1.0.0"
