# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "mmio-tag"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Memory-Mapped I/O Tag Type"
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]

[features]
default = []
std = []

[lints]
workspace = true
