# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "noop-rust-nostd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Boot Time Benchmark"
homepage.workspace = true

[[bin]]
name = "noop-rust-nostd"

[dependencies]
cfg-if = { workspace = true }
nvx = { workspace = true }
nvx-crt0 = { workspace = true, features = ["rust-main", "provides-allocator"] }
libc_string = { workspace = true }
sys = { workspace = true }
sysalloc = { workspace = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
trace = ["nvx/trace", "nvx-crt0/trace"]
debug = ["nvx/debug", "nvx-crt0/debug"]
info = ["nvx/info", "nvx-crt0/info"]
warn = ["nvx/warn", "nvx-crt0/warn"]
error = ["nvx/error", "nvx-crt0/error"]
panic = ["nvx/panic", "nvx-crt0/panic"]

[lints]
workspace = true
