# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "testd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Test Daemon"
homepage.workspace = true

[[bin]]
name = "testd"

[dependencies]
arch = { workspace = true }
libc_string = { workspace = true }
sys = { workspace = true }
nvx = { workspace = true }
proc = { workspace = true, features = ["syscall"] }
config = { workspace = true }
syslog = { workspace = true, default-features = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
trace = ["nvx/trace"]
debug = ["nvx/debug"]
info = ["nvx/info"]
warn = ["nvx/warn"]
error = ["nvx/error"]
panic = ["nvx/panic"]

[lints]
workspace = true
