.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH freopen 3 "January 2014" "C Library" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
freopen \- Reopens a file stream.
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "#include <" "stdio.h" >

.BI "FILE *freopen(const char *" filename ", const char *" mode ", FILE *" stream ");"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The
.BR freopen()
function first attempts to flush the stream and close any file descriptor 
associated with 
.IR stream .
Failure to flush or close the file descriptor successfully are ignored. The
error and end-of-file indicators for the stream are cleared.

Then, 
.BR freopen() 
opens the file whose pathname is the string pointed to by
.IR filename
and associate the stream pointed to by
.IR stream
with it. The
.IR mode 
argument is used just as 
.BR fopen() .

The original stream is closed regardless of whether the subsequent open
succeeds.
.\"
.\"=============================================================================
.\"
.SH "RETURN VALUE"
.\"
Upon successful completion,
.BR freopen()
returns the value of 
.IR stream .
Otherwise, a null a pointer is returned and 
.IR errno
is set to indicate the error.
.\"
.\"=============================================================================
.\"
.SH ERRORS
.\"
.TP
.BR [EINVAL]
Invalid 
.IR mode .
.\"
.\"=============================================================================
.\"
.SH "CONFORMING TO"
.\"
POSIX.1-2001
.\"
.\"=============================================================================
.\"
.SH "NOTES"
.\"
Since the stream is closed during the operation, any user-buffers assigned 
to it are unassigned.
.\"
.\"=============================================================================
.\"
.SH "SEE ALSO"
.\"
.BR fclose(3) ,
.BR fopen(3) ,
.BR fdopen(3)
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
