.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH opendir 3 "January 2014" "C Library" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
opendir \- Opens a directory stream
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "#include <" "dirent.h" >

.BI "DIR *opendir(const char *" dirname ");"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The
.BR
opendir()
function opens a directory stream corresponding to the directory named by the
.IR dirname
argument. The directory stream is positioned at the first entry.

Applications are only able to open up to a total of 
.BR OPEN_MAX
files and directories.
.\"
.\"=============================================================================
.\"
.SH "RETURN VALUE"
.\"
Upon successful completion, 
.BR opendir()
returns a pointer to a directory stream. Otherwise, a null pointer is returned 
and 
.IR errno
is set to indicate the error.
.\"
.\"=============================================================================
.\"
.SH ERRORS
.\"
.TP
.BR EMFILE
.BR OPEN_MAX
files descriptors are currently open in the calling process.

.P
For other errors refer to
.BR open(2) .
.\"
.\"=============================================================================
.\"
.SH "SEE ALSO"
.\"
.BR open(2) ,
.BR readdir(3) ,
.BR rewinddir(3)
.\"
.\"=============================================================================
.\"
.SH "CONFORMING TO"
.\"
POSIX.1-2001
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
