# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

name: "Set-up Nanvix build and test environment"

runs:
  using: "composite"
  steps:
  - name: "Install APT dependencies"
    shell: bash
    run: |
      sudo -E ./scripts/setup/ubuntu.sh

  - name: "Install Rust"
    shell: bash
    run: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  - name: "Add rust toolchains"
    shell: bash
    run: |
      source $HOME/.cargo/env
      rustup component add rust-src
      rustup target add wasm32-wasip1
