# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT license.

[package]
name = "echo-client"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
flexi_logger = { workspace = true }
log = { workspace = true }
hyper = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["full"] }
http-body-util = { workspace = true }
hyper-util = { workspace = true, features = ["full"] }
