// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//! # `fork()` File-Descriptor Duplication Tests over the Host Filesystem
//!
//! Exercises file-descriptor inheritance across `fork()` end-to-end for a file backed by the host
//! filesystem daemon (`hostfsd`), rather than the in-guest RAMFS image used by `test-fork-guestfs`. The
//! request path therefore runs from the guest through `vfsd` and out over IKC to `hostfsd`, which
//! owns the underlying host `File`. The scenario verifies that:
//!
//! 1. **Inheritance** — a descriptor opened by the parent before `fork()` is usable by the child
//!    afterwards: the child can read from the inherited descriptor without re-opening the file.
//! 2. **Shared open file description** — the parent and child share a single file offset. Because
//!    `vfsd` forwards reads with a "use current position" offset, the offset lives in the single
//!    host `File` that `hostfsd` keys by remote descriptor; the parent and child both reference
//!    that one remote descriptor after `fork()`, so the child's read advances the offset the parent
//!    subsequently observes, matching POSIX semantics.
//!
//! ## Layout of the fixture
//!
//! The descriptor refers to `/mnt/forkfd.dat`, a file in the host directory mounted at `/mnt` (the
//! directory is generated by `build.rs` and passed to the runner via `-mount`). The file holds a
//! deterministic ramp: byte `i` has value `i as u8`. The test reads the file in three disjoint,
//! sequential windows so that each window's expected bytes are a simple function of the file
//! offset:
//!
//! ```text
//! offset:  0          16             48        64
//!          |  parent  |    child     |  parent |
//!          |  prelude |    chunk     |   tail  |
//! ```
//!
//! The parent reads the prelude before `fork()`, advancing the shared offset to 16. The child
//! reads the chunk (offset 16..48), advancing the shared offset to 48. The parent then reads the
//! tail (offset 48..64). The tail landing exactly on the bytes that follow the child's read proves
//! the offset was shared, not merely copied.
//!
//! ## Synchronization
//!
//! `procd` notifies `vfsd` to duplicate the parent's descriptors onto the child asynchronously
//! (fire-and-forget), so a freshly forked child may briefly observe the descriptor as unknown.
//! The child therefore retries its first read until the duplication lands; because `vfsd`
//! processes messages in order on a single thread, this converges. A parent/child rendezvous over
//! IPC orders the child's read before the parent's tail read, turning an offset-sharing violation
//! into a deterministic failure rather than a flake.

//==================================================================================================
// Imports
//==================================================================================================

use ::core::sync::atomic::{
    AtomicI32,
    Ordering,
};
use ::sys::{
    error::Error,
    ipc::{
        Message,
        MessageReceiver,
        MessageSender,
        MessageType,
    },
    kcall::{
        fork,
        ipc,
        pm,
    },
    pm::ProcessIdentifier,
};
use ::sysapi::ffi::c_int;
use ::syscall::{
    fcntl,
    safe::RegularFileOpenFlags,
    unistd,
};

//==================================================================================================
// Constants
//==================================================================================================

/// Ordering used for all atomic operations.
const ORDER: Ordering = Ordering::SeqCst;

/// Mount point at which the host filesystem is attached for the duration of the test.
const MOUNT_POINT: &str = "/mnt";

/// Path of the fixture file in the hostfs-mounted directory. Kept in sync with `build.rs`.
const FIXTURE_PATH: &str = "/mnt/forkfd.dat";

/// Number of bytes the parent reads before `fork()` (file offset `0..16`).
const PARENT_PRELUDE: usize = 16;

/// Number of bytes the child reads from the inherited descriptor (file offset `16..48`).
const CHILD_CHUNK: usize = 32;

/// Number of bytes the parent reads after the child (file offset `48..64`).
const PARENT_TAIL: usize = 16;

/// File offset at which the child begins reading (end of the parent's prelude).
const CHILD_START: usize = PARENT_PRELUDE;

/// File offset at which the parent's tail read begins (end of the child's chunk).
const TAIL_START: usize = PARENT_PRELUDE + CHILD_CHUNK;

/// Upper bound on first-read retries used to absorb the asynchronous descriptor duplication.
///
/// Each attempt is a full system-call round-trip to `vfsd` (and onward to `hostfsd`), which yields
/// the processor and gives `procd` and `vfsd` ample opportunity to process the fork-clone
/// notification. The bound only guards against a genuinely broken descriptor.
const MAX_FIRST_READ_ATTEMPTS: u32 = 4096;

/// Exit status used by the child when all of its checks succeed.
const CHILD_EXIT_OK: i32 = 0;

/// Exit status used by the child when one of its checks fails.
const CHILD_EXIT_FAIL: i32 = 1;

//==================================================================================================
// Global State
//==================================================================================================

/// Descriptor opened by the parent before `fork()`, recovered by the child from copy-on-write
/// memory. Initialized to an invalid descriptor so a missing store is detectable.
static OPEN_FD: AtomicI32 = AtomicI32::new(-1);

//==================================================================================================
// Helpers
//==================================================================================================

/// Returns the fixture byte expected at file offset `offset`.
fn expected_byte(offset: usize) -> u8 {
    // The fixture holds a ramp where byte `i` has value `i as u8`; the low 8 bits of the offset
    // therefore give the expected value without any lossy cast.
    u8::try_from(offset & 0xFF).unwrap_or(0)
}

/// Reads exactly `buf.len()` bytes from `fd`, or fewer on end-of-file.
///
/// When `retry` is set, an error on the very first read (before any byte has been consumed) is
/// retried up to [`MAX_FIRST_READ_ATTEMPTS`] times. This absorbs the window in which a freshly
/// forked child's descriptors have not yet been duplicated into `vfsd`. Once any byte has been
/// read the descriptor is known to be valid, so further errors are treated as failures.
///
/// Returns the number of bytes read, or `Err(())` if the read fails.
fn read_filling(fd: c_int, buf: &mut [u8], retry: bool) -> Result<usize, ()> {
    let mut total: usize = 0;
    let mut attempts: u32 = 0;
    while total < buf.len() {
        match unistd::read(fd, &mut buf[total..]) {
            // End-of-file: stop early and report what was read.
            Ok(0) => break,
            Ok(n) => match usize::try_from(n) {
                Ok(count) => total += count,
                Err(_) => return Err(()),
            },
            Err(_) if retry && total == 0 && attempts < MAX_FIRST_READ_ATTEMPTS => {
                attempts += 1;
            },
            Err(_) => return Err(()),
        }
    }
    Ok(total)
}

/// Returns whether the first `len` bytes of `buf` match the fixture ramp starting at `start`.
fn matches_ramp(buf: &[u8], start: usize, len: usize) -> bool {
    if buf.len() < len {
        return false;
    }
    (0..len).all(|i| buf[i] == expected_byte(start + i))
}

//==================================================================================================
// Child Path
//==================================================================================================

/// Runs the child's checks against the inherited descriptor and reports the outcome to the parent.
///
/// The child:
///
/// 1. Blocks on `recv()` to rendezvous with the parent.
/// 2. Recovers the inherited descriptor from copy-on-write memory.
/// 3. Reads [`CHILD_CHUNK`] bytes, retrying the first read to absorb the asynchronous descriptor
///    duplication, and confirms the bytes are the fixture window the parent's offset pointed at.
/// 4. Reports a pass/fail flag, the first byte observed, and the byte count to the parent.
fn run_child(parent_pid: ProcessIdentifier, my_pid: ProcessIdentifier) -> Result<(), Error> {
    // Barrier: block until the parent releases the child.
    ipc::__kcall_recv()?;

    // Recover the inherited descriptor.
    let fd: c_int = OPEN_FD.load(ORDER);

    // Read the child's window from the inherited descriptor.
    let mut buf: [u8; CHILD_CHUNK] = [0u8; CHILD_CHUNK];
    let read_result: Result<usize, ()> = read_filling(fd, &mut buf, true);

    let (passed, first_byte, count): (bool, u8, u8) = match read_result {
        Ok(total) => {
            let ok: bool = total == CHILD_CHUNK && matches_ramp(&buf, CHILD_START, CHILD_CHUNK);
            (ok, buf[0], u8::try_from(total).unwrap_or(0))
        },
        Err(()) => (false, 0, 0),
    };

    // Report observations to the parent.
    let mut payload: [u8; Message::PAYLOAD_SIZE] = [0u8; Message::PAYLOAD_SIZE];
    payload[0] = u8::from(passed);
    payload[1] = first_byte;
    payload[2] = count;
    let reply: Message = Message::new(
        MessageSender::from(my_pid),
        MessageReceiver::from(parent_pid),
        MessageType::Ipc,
        None,
        payload,
    );
    ipc::__kcall_send(&reply)?;

    Ok(())
}

//==================================================================================================
// Test
//==================================================================================================

/// Runs the descriptor-inheritance and shared-offset scenario over the host filesystem.
fn test_fork_hostfs_descriptor_inheritance() -> Result<(), Error> {
    let parent_pid: ProcessIdentifier = pm::__kcall_getpid()?;

    // Attach the host filesystem at /mnt so the fixture is reachable from the guest. The mount is
    // VFS-global, so the child forked below observes it without remounting.
    ::syscall::sys::mount::mount("", MOUNT_POINT, "hostfs", 0)?;

    // Open the fixture read-only. The descriptor is allocated in the parent's table inside vfsd and
    // refers to a remote descriptor owned by hostfsd.
    let fd: c_int = fcntl::open(FIXTURE_PATH, RegularFileOpenFlags::read_only().into(), 0)?;
    OPEN_FD.store(fd, ORDER);

    // Read the prelude, advancing the descriptor's offset to CHILD_START before forking.
    let mut prelude: [u8; PARENT_PRELUDE] = [0u8; PARENT_PRELUDE];
    match read_filling(fd, &mut prelude, false) {
        Ok(total) => assert!(
            total == PARENT_PRELUDE && matches_ramp(&prelude, 0, PARENT_PRELUDE),
            "parent prelude read returned unexpected data (bytes={})",
            total
        ),
        Err(()) => panic!("parent failed to read fixture prelude"),
    }

    // Fork. Both processes resume here; the child inherits a copy of the parent's descriptors.
    let child_pid: ProcessIdentifier = fork::__kcall_fork()?;

    // Child: perform its checks and terminate without returning to the shared flow.
    if child_pid == ProcessIdentifier::from(0) {
        let my_pid: ProcessIdentifier = match pm::__kcall_getpid() {
            Ok(pid) => pid,
            Err(_) => pm::__kcall_exit(CHILD_EXIT_FAIL)?,
        };
        let status: i32 = match run_child(parent_pid, my_pid) {
            Ok(()) => CHILD_EXIT_OK,
            Err(_) => CHILD_EXIT_FAIL,
        };
        pm::__kcall_exit(status)?;
    }

    // Parent: reaching here means this is the parent process.
    assert!(child_pid != parent_pid, "child PID must differ from parent PID");

    // Release the child to perform its read against the inherited descriptor.
    let go: Message = Message::new(
        MessageSender::from(parent_pid),
        MessageReceiver::from(child_pid),
        MessageType::Ipc,
        None,
        [0u8; Message::PAYLOAD_SIZE],
    );
    ipc::__kcall_send(&go)?;

    // Receive the child's report. This happens-after the child's read, so the shared offset now
    // points at TAIL_START.
    let reply: Message = ipc::__kcall_recv()?;
    let reply_type: MessageType = { reply.message_type };
    assert!(reply_type == MessageType::Ipc, "expected IPC reply from child");

    let child_passed: u8 = reply.payload[0];
    let child_first_byte: u8 = reply.payload[1];
    let child_count: u8 = reply.payload[2];

    // Inheritance invariant: the child read its full window from the inherited descriptor.
    assert!(
        child_passed == 1,
        "child failed to read the inherited descriptor (first_byte={:#x}, count={})",
        child_first_byte,
        child_count
    );
    // The child's first byte must be the fixture byte at CHILD_START, confirming it inherited both
    // the descriptor and its offset rather than a fresh descriptor positioned at zero.
    assert!(
        usize::from(child_first_byte) == CHILD_START,
        "child observed first byte {:#x}; expected {:#x} (inherited offset broken)",
        child_first_byte,
        CHILD_START
    );
    assert!(
        usize::from(child_count) == CHILD_CHUNK,
        "child read {} bytes; expected {}",
        child_count,
        CHILD_CHUNK
    );

    // Shared-offset invariant: the parent's tail read continues exactly where the child left off.
    let mut tail: [u8; PARENT_TAIL] = [0u8; PARENT_TAIL];
    match read_filling(fd, &mut tail, false) {
        Ok(total) => assert!(
            total == PARENT_TAIL && matches_ramp(&tail, TAIL_START, PARENT_TAIL),
            "parent tail read did not continue from the child's offset (bytes={}, first={:#x}; \
             expected first={:#x}) — open file description not shared",
            total,
            tail[0],
            expected_byte(TAIL_START)
        ),
        Err(()) => panic!("parent failed to read fixture tail"),
    }

    // Release the inherited descriptor in the parent.
    unistd::close(fd)?;

    // Detach the host filesystem.
    ::syscall::sys::mount::umount(MOUNT_POINT)?;

    Ok(())
}

//==================================================================================================
// Public Entry Point
//==================================================================================================

/// Runs all `fork()` host-filesystem file-descriptor duplication tests.
pub fn run() -> Result<(), Error> {
    ::syslog::info!("test-fork-hostfs: starting fork() hostfs descriptor duplication tests");
    test_fork_hostfs_descriptor_inheritance()?;
    ::syslog::info!("test-fork-hostfs: PASS - fork_hostfs_descriptor_inheritance");
    Ok(())
}
