// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//==================================================================================================
// Configuration
//==================================================================================================

#![no_std]
#![no_main]
#![deny(clippy::all)]

//==================================================================================================
// Modules
//==================================================================================================

extern crate alloc;
extern crate libc_string;
extern crate nvx;

//==================================================================================================
// Imports
//==================================================================================================

use ::alloc::vec;
use ::core::ptr;
use ::sys::{
    error::{
        Error,
        ErrorCode,
    },
    kcall::{
        mm,
        pm,
    },
    mm::Address,
    pm::Capability,
};

//==================================================================================================
// Constants
//==================================================================================================

/// Encoded 8-byte "RAMFS   " tag exposed by the MicroVM RAMFS MMIO region.
const RAMFS_MMIO_TAG: u64 = u64::from_be_bytes(*b"RAMFS   ");

//==================================================================================================
// Entry Point
//==================================================================================================

#[no_mangle]
pub fn main() -> Result<(), Error> {
    // Initialize the fat32 filesystem.
    fat32::init().map_err(|_| Error::new(ErrorCode::InvalidArgument, "fat32 init failed"))?;

    // Run tests.
    test_create_mount()?;
    test_ramfs_mount()?;

    // Output "ok" to signal success to the test runner.
    let magic_string: &[u8] = "ok".as_bytes();
    ::syscall::unistd::write(::sysapi::unistd::STDOUT_FILENO, magic_string)?;

    Ok(())
}

//==================================================================================================
// Test: Mount RAMFS Image
//==================================================================================================

/// Tests mounting a FAT image provided via the RAMFS MMIO region.
///
/// The FAT image is generated by build.rs and passed to nanvixd via `-ramfs`.
/// Since the RAMFS region is read-only in the guest, the image is copied to a
/// heap buffer before mounting.
fn test_ramfs_mount() -> Result<(), Error> {
    ::syslog::info!("fat32-test: test_ramfs_mount begin");

    let mut cap_acquired: bool = false;
    let mut region_attached: bool = false;

    let result: Result<(), Error> = (|| {
        // Acquire IO management capability.
        pm::capctl(Capability::IoManagement, true)?;
        cap_acquired = true;

        // Attach RAMFS MMIO region.
        mm::mmio_alloc(RAMFS_MMIO_TAG)?;
        region_attached = true;

        // Get region info.
        let info = mm::mmio_info(RAMFS_MMIO_TAG)?;
        let total_size: usize = info.size();

        ::syslog::info!("fat32-test: ramfs region (size={})", total_size,);

        // Copy RAMFS to heap buffer (RAMFS is read-only in guest).
        let mut buffer: alloc::vec::Vec<u8> = vec![0u8; total_size];
        unsafe {
            let src: *const u8 = info.base().as_ptr();
            for (i, byte) in buffer.iter_mut().enumerate() {
                *byte = ptr::read_volatile(src.add(i));
            }
        }

        // Release MMIO region before mounting.
        mm::mmio_free(RAMFS_MMIO_TAG)?;
        region_attached = false;
        pm::capctl(Capability::IoManagement, false)?;
        cap_acquired = false;

        // Leak the buffer so it lives for the program's lifetime.
        // SAFETY: The mount holds a raw pointer into this buffer, so it
        // must not be deallocated while the mount exists.
        let leaked: &'static mut [u8] = alloc::boxed::Box::leak(buffer.into_boxed_slice());

        // Mount the FAT image.
        unsafe {
            fat32::mount("/ramfs", leaked.as_mut_ptr(), leaked.len())
                .map_err(|_| Error::new(ErrorCode::InvalidArgument, "fat32 mount failed"))?;
        }

        // Verify hello.txt exists and contains expected content.
        verify_file("/ramfs/hello.txt", b"Hello from FAT32 on Nanvix!\n")?;

        // Verify subdirectory and nested file.
        let info = fat32::stat("/ramfs/subdir")
            .map_err(|_| Error::new(ErrorCode::NoSuchEntry, "stat subdir failed"))?;
        if !info.is_dir {
            return Err(Error::new(ErrorCode::InvalidArgument, "subdir should be a directory"));
        }

        verify_file("/ramfs/subdir/nested.txt", b"nested content\n")?;

        // Verify read_dir on root.
        let entries = fat32::read_dir("/ramfs")
            .map_err(|_| Error::new(ErrorCode::InvalidArgument, "read_dir /ramfs failed"))?;
        if entries.len() != 2 {
            return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 entries in /ramfs"));
        }

        ::syslog::info!("fat32-test: test_ramfs_mount passed");
        Ok(())
    })();

    // Cleanup on error.
    if region_attached {
        let _ = mm::mmio_free(RAMFS_MMIO_TAG);
    }
    if cap_acquired {
        let _ = pm::capctl(Capability::IoManagement, false);
    }

    result
}

//==================================================================================================
// Test: Create In-Memory Mount
//==================================================================================================

/// Tests creating an in-memory FAT filesystem via `create_mount`.
///
/// Validates write, read, stat, mkdir, readdir, rmdir, unlink, and unmount.
fn test_create_mount() -> Result<(), Error> {
    ::syslog::info!("fat32-test: test_create_mount begin");

    // Create an in-memory FAT mount.
    fat32::create_mount("/scratch", 128 * 1024)
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "create_mount failed"))?;

    // Write a file.
    {
        let mut file = fat32::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/scratch/test.txt")
            .map_err(|_| Error::new(ErrorCode::InvalidArgument, "failed to create test.txt"))?;
        file.write(b"test data")
            .map_err(|_| Error::new(ErrorCode::InvalidArgument, "failed to write test.txt"))?;
        file.flush()
            .map_err(|_| Error::new(ErrorCode::InvalidArgument, "failed to flush test.txt"))?;
    }

    // Read it back.
    {
        let mut file = fat32::open("/scratch/test.txt")
            .map_err(|_| Error::new(ErrorCode::NoSuchEntry, "failed to open test.txt"))?;
        let content = file
            .read_to_vec()
            .map_err(|_| Error::new(ErrorCode::InvalidArgument, "failed to read test.txt"))?;
        if content.as_slice() != b"test data" {
            return Err(Error::new(ErrorCode::InvalidArgument, "test.txt content mismatch"));
        }
    }

    // Verify stat.
    let info = fat32::stat("/scratch/test.txt")
        .map_err(|_| Error::new(ErrorCode::NoSuchEntry, "stat test.txt failed"))?;
    if info.is_dir {
        return Err(Error::new(ErrorCode::InvalidArgument, "test.txt should not be a directory"));
    }
    if info.size != 9 {
        return Err(Error::new(ErrorCode::InvalidArgument, "test.txt size mismatch"));
    }

    // Test mkdir.
    fat32::mkdir("/scratch/mydir")
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "mkdir failed"))?;

    // Verify read_dir sees both entries.
    let entries = fat32::read_dir("/scratch")
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "read_dir failed"))?;
    if entries.len() != 2 {
        return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 entries in /scratch"));
    }

    // Clean up: remove directory and file, then unmount.
    fat32::rmdir("/scratch/mydir")
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "rmdir failed"))?;
    fat32::unlink("/scratch/test.txt")
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "unlink failed"))?;
    fat32::unmount("/scratch")
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "unmount failed"))?;

    ::syslog::info!("fat32-test: test_create_mount passed");
    Ok(())
}

//==================================================================================================
// Helpers
//==================================================================================================

/// Opens a file and verifies its contents match `expected`.
fn verify_file(path: &str, expected: &[u8]) -> Result<(), Error> {
    let mut file =
        fat32::open(path).map_err(|_| Error::new(ErrorCode::NoSuchEntry, "failed to open file"))?;
    let content = file
        .read_to_vec()
        .map_err(|_| Error::new(ErrorCode::InvalidArgument, "failed to read file"))?;
    if content.as_slice() != expected {
        return Err(Error::new(ErrorCode::InvalidArgument, "file content mismatch"));
    }
    Ok(())
}
