sudo: required

language: C

services:
  - docker

before_install:
- docker build -t turbolay/launchnanvix --build-arg BRANCH=$TRAVIS_BRANCH .

script:
- docker run turbolay/launchnanvix /bin/sh -c "cd /root/nanvix; make nanvix > /dev/null"
