# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[workspace]
resolver = "2"
default-members = ["src/microvm"]
members = [
        "src/benchmarks/echo-rust-nostd",
        "src/benchmarks/echo-wasm-rust",
        "src/benchmarks/noop-rust-nostd",
        "src/benchmarks/noop-wasm-rust",
        "src/daemons/linuxd",
        "src/daemons/memd",
        "src/daemons/procd",
        "src/daemons/wasmd",
        "src/kernel",
        "src/libs/arch",
        "src/libs/bitmap",
        "src/libs/config",
        "src/libs/elf",
        "src/libs/error",
        "src/libs/hwloc",
        "src/libs/nvx",
        "src/libs/posix",
        "src/libs/proc",
        "src/libs/profiler",
        "src/libs/raw-array",
        "src/libs/slab",
        "src/libs/static_assert",
        "src/libs/sysalloc",
        "src/libs/sysapi",
        "src/libs/syscall",
        "src/libs/syscomm",
        "src/libs/syslog",
        "src/libs/sys",
        "src/libs/type-safe",
        "src/microvm",
        "src/tests/file-rust",
        "src/tests/linux-app",
        "src/tests/testd",
        "src/user/hello-rust-nostd",
        "src/user/hello-wasm",
        "src/utils/echo-client",
        "src/utils/nanvix-bench",
        "src/utils/nanvixd",
]

[workspace.package]
version = "0.8.77"
license-file = "LICENSE.txt"
authors = ["The Maintainers of Nanvix"]
edition = "2021"
homepage = "https://github.com/nanvix"

[workspace.dependencies]
arch = { path = "src/libs/arch", default-features = false }
anyhow = "1.0.98"
base64 = "0.22.1"
bitmap = { path = "src/libs/bitmap", default-features = false }
cc = "1.2.26"
cfg-if = "1.0.0"
config = { path = "src/libs/config", default-features = false }
elf = { path = "src/libs/elf", default-features = false }
error = { path = "src/libs/error", default-features = false }
flexi_logger = "0.31.2"
goblin = { version = "0.10.0", default-features = false }
indicatif = "0.18.0"
http = "1.3.1"
http-body-util = "0.1.3"
hyperlight-common = { version = "0.7.0", default-features = false }
hyperlight-host = { version = "0.7.0", default-features = false, features = [
        "kvm",
] }
hyperlight-guest = { version = "0.7.0", default-features = false }
hyper = { version = "1.6.0", default-features = false }
hyper-util = { version = "0.1.14", default-features = false }
hwloc = { path = "src/libs/hwloc", default-features = false }
kvm-bindings = "0.13.0"
kvm-ioctls = "0.23.0"
libc = "0.2.172"
log = "0.4.27"
microvm = { path = "src/microvm", default-features = false }
nanvixd = { path = "src/utils/nanvixd", default-features = false }
num_enum = { version = "0.7.3", default-features = false }
nvx = { path = "src/libs/nvx", default-features = false }
profiler = { path = "src/libs/profiler", default-features = false }
posix = { path = "src/libs/posix", default-features = false }
proc = { path = "src/libs/proc", default-features = false }
raw-array = { path = "src/libs/raw-array", default-features = false }
reqwest = { version = "0.12", default-features = false }
serde = { version = "1.0.219", default-features = false }
serde_json = { version = "1.0.140", default-features = false, features = [
        "alloc",
] }
signal-hook = "0.3.18"
slab = { path = "src/libs/slab", default-features = false }
spin = { git = "https://github.com/nanvix/spin-rs", package = "spin", branch = "nanvix/v0.10.0", default-features = false }
static_assert = { path = "src/libs/static_assert", default-features = false }
sysapi = { path = "src/libs/sysapi", default-features = false }
sysalloc = { path = "src/libs/sysalloc", default-features = false }
syscall = { path = "src/libs/syscall", default-features = false }
sys = { path = "src/libs/sys", default-features = false }
talc = { git = "https://github.com/nanvix/talc", rev = "12e66643796be912933a369a2d556aaac4c68771", default-features = false, package = "talc" }
tokio = { version = "1.45.1", default-features = false }
type-safe = { path = "src/libs/type-safe", default-features = false }
uuid = { version = "1.17.0", features = ["v4"] }
syscomm = { path = "src/libs/syscomm", default-features = false }
syslog = { path = "src/libs/syslog", default-features = false }
wasmi = { version = "0.49.0", default-features = false }

[profile.dev]
opt-level = 0
debug = true
strip = false
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[profile.dev-wasm]
inherits = "dev"
opt-level = "z"
lto = true

[profile.release-wasm]
inherits = "release"
opt-level = "z"
lto = true

[workspace.lints.rust]
warnings = "deny"
