# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[workspace]
resolver = "2"
default-members = ["src/utils/nanvixd"]
members = [
        "src/benchmarks/echo-rust-nostd",
        "src/benchmarks/echo-wasm-rust",
        "src/benchmarks/noop-rust-nostd",
        "src/benchmarks/noop-wasm-rust",
        "src/daemons/linuxd",
        "src/daemons/memd",
        "src/daemons/procd",
        "src/daemons/wasmd",
        "src/kernel",
        "src/libs/arch",
        "src/libs/bitmap",
        "src/libs/config",
        "src/libs/control-plane-api",
        "src/libs/elf",
        "src/libs/error",
        "src/libs/hwloc",
        "src/libs/nanvix",
        "src/libs/nanvix-http",
        "src/libs/nanvix-registry",
        "src/libs/nanvix-sandbox",
        "src/libs/nanvix-sandbox-cache",
        "src/libs/nanvix-terminal",
        "src/libs/no_fail",
        "src/libs/nvx",
        "src/libs/posix",
        "src/libs/proc",
        "src/libs/profiler",
        "src/libs/raw-array",
        "src/libs/slab",
        "src/libs/static_assert",
        "src/libs/sysalloc",
        "src/libs/sysapi",
        "src/libs/syscall",
        "src/libs/syscomm",
        "src/libs/syslog",
        "src/libs/libc_stdlib",
        "src/libs/libc_string",
        "src/libs/sys",
        "src/libs/type-safe",
        "src/libs/user-vm-api",
        "src/tests/arch-rust",
        "src/tests/file-rust",
        "src/tests/linux-app",
        "src/tests/testd",
        "src/uservm",
        "src/user/hello-rust-nostd",
        "src/user/hello-wasm",
        "src/utils/echo-client",
        "src/utils/nanvix-bench",
        "src/utils/nanvix-test",
        "src/utils/nanvixd",
]

[workspace.package]
version = "0.11.48"
license-file = "LICENSE.txt"
authors = ["The Maintainers of Nanvix"]
edition = "2021"
homepage = "https://github.com/nanvix"

[workspace.dependencies]
arch = { path = "src/libs/arch", default-features = false }
anyhow = "1.0.98"
base64 = "0.22.1"
bitmap = { path = "src/libs/bitmap", default-features = false }
cc = "1.2.26"
cfg-if = "1.0.0"
chrono = "0.4.42"
compiler_builtins = "0.1.160"
config = { path = "src/libs/config", default-features = false }
control-plane-api = { path = "src/libs/control-plane-api", default-features = false }
dirs = "6.0"
elf = { path = "src/libs/elf", default-features = false }
error = { path = "src/libs/error", default-features = false }
flexi_logger = "0.31.2"
goblin = { version = "0.10.0", default-features = false }
indicatif = "0.18.0"
http = "1.3.1"
http-body-util = "0.1.3"
hyperlight-common = { git = "https://github.com/nanvix/hyperlight", branch = "nanvix/v0.12.0", default-features = false }
hyperlight-host = { git = "https://github.com/nanvix/hyperlight", branch = "nanvix/v0.12.0", default-features = false, features = [
        "kvm",
        "mshv3",
        "hw-interrupts",
] }
hyperlight-guest = { git = "https://github.com/nanvix/hyperlight", branch = "nanvix/v0.12.0", default-features = false }
hyper = { version = "1.6.0", default-features = false }
hyper-util = { version = "0.1.14", default-features = false }
hwloc = { path = "src/libs/hwloc", default-features = false }
kvm-bindings = "0.14.0"
kvm-ioctls = "0.24.0"
libc = "0.2.172"
linuxd = { path = "src/daemons/linuxd", default-features = false }
log = "0.4.27"
nanvix = { path = "src/libs/nanvix", default-features = false }
nanvix-http = { path = "src/libs/nanvix-http", default-features = false }
nanvix-registry = { path = "src/libs/nanvix-registry", default-features = false }
nanvix-sandbox = { path = "src/libs/nanvix-sandbox", default-features = false }
nanvix-sandbox-cache = { path = "src/libs/nanvix-sandbox-cache", default-features = false }
nanvix-terminal = { path = "src/libs/nanvix-terminal", default-features = false }
nanvixd = { path = "src/utils/nanvixd", default-features = false }
no_fail = { path = "src/libs/no_fail", default-features = false }
num_enum = { version = "0.7.3", default-features = false }
nvx = { path = "src/libs/nvx", default-features = false }
profiler = { path = "src/libs/profiler", default-features = false }
posix = { path = "src/libs/posix", default-features = false }
proc = { path = "src/libs/proc", default-features = false }
rand = "0.9.2"
raw-array = { path = "src/libs/raw-array", default-features = false }
reqwest = { version = "0.13", default-features = false }
serde = { version = "1.0.219", default-features = false }
serde_cbor = { version = "0.11.2", default-features = false, features = [
        "alloc",
        "std",
] }
serde_json = { version = "1.0.140", default-features = false, features = [
        "alloc",
] }
shell-words = "1.1"
signal-hook = "0.4.1"
slab = { path = "src/libs/slab", default-features = false }
spin = { git = "https://github.com/nanvix/spin-rs", package = "spin", branch = "nanvix/v0.10.0", default-features = false }
static_assert = { path = "src/libs/static_assert", default-features = false }
libc_stdlib = { path = "src/libs/libc_stdlib", default-features = false }
libc_string = { path = "src/libs/libc_string", default-features = false }
sys = { path = "src/libs/sys", default-features = false }
sysapi = { path = "src/libs/sysapi", default-features = false }
sysalloc = { path = "src/libs/sysalloc", default-features = false }
syscall = { path = "src/libs/syscall", default-features = false }
syscomm = { path = "src/libs/syscomm", default-features = false }
syslog = { path = "src/libs/syslog", default-features = false }
talc = { git = "https://github.com/nanvix/talc", rev = "12e66643796be912933a369a2d556aaac4c68771", default-features = false, package = "talc" }
tokio = { version = "1.45.1", default-features = false }
toml = { version = "0.9.10", default-features = false, features = [
        "parse",
        "serde",
] }
type-safe = { path = "src/libs/type-safe", default-features = false }
uservm = { path = "src/uservm", default-features = false }
uuid = { version = "1.18.1", default-features = false }
user-vm-api = { path = "src/libs/user-vm-api", default-features = false }
vmm-sys-util = { version = "0.15.0", default-features = false }
wasmi = { version = "1.0.0", default-features = false }

[profile.dev]
opt-level = 0
debug = true
strip = false
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[profile.dev-wasm]
inherits = "dev"
opt-level = "z"
lto = true

[profile.release-wasm]
inherits = "release"
opt-level = "z"
lto = true

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
# TODO (#1146): Enable restriction linting rules, once they are fixed.
# restriction = "deny"
# TODO (#1147): Enable pedantic linting rules, once they are fixed.
# pedantic = "deny"
# TODO (#1148): Enable nursery linting rules, once they are fixed.
# nursery = "deny"
# TODO (#1149): Enable cargo linting rules, once they are fixed.
# cargo = "deny"
