# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "config"
version.workspace = true
license-file.workspace = true
authors.workspace = true
edition.workspace = true
description = "Configuration and constants for Nanvix"
homepage.workspace = true

[lib]
crate-type = ["lib"]

[build-dependencies]
toml = "0.8.19"

[features]
default = []
std = []
