# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "test-kernel"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Focused user-level regression tests for kernel interfaces"
homepage.workspace = true

[[bin]]
name = "test-kernel"

[dependencies]
arch = { workspace = true }
config = { workspace = true }
libc_string = { workspace = true }
nvx = { workspace = true }
static_assert = { workspace = true }
sys = { workspace = true, features = ["kcall"] }
syslog = { workspace = true, default-features = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
trace = ["nvx/trace", "syslog/trace"]
debug = ["nvx/debug", "syslog/debug"]
info = ["nvx/info", "syslog/info"]
warn = ["nvx/warn", "syslog/warn"]
error = ["nvx/error", "syslog/error"]
panic = ["nvx/panic", "syslog/panic"]

[lints]
workspace = true
