# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "proc"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Process Management Daemon"
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
nvx = { workspace = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = []
syscall = []
daemon = ["nvx/allocator"]
