# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "user-vm-api"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "User VM API Library"
homepage.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }

[features]
default = []

[lints]
workspace = true
