# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "bitmap"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
raw-array = { workspace = true }
sys = { workspace = true }

[dev-dependencies]
rand = "0.8"

[features]
default = []
std = ["sys/std"]

[lints]
workspace = true
