# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "microvm"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[lib]
name = "microvm"
path = "src/lib.rs"

[[bin]]
name = "microvm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
flexi_logger = { workspace = true }
hyperlight_host = { workspace = true, optional = true, features = [
    "kvm",
    "remove-timeout",
] }
log = { workspace = true }
profiler = { workspace = true, features = ["auto-calibrate"] }
sys = { workspace = true }
cfg-if = { workspace = true }
config = { workspace = true, features = ["microvm"] }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { workspace = true }
kvm-ioctls = { workspace = true }
libc = { workspace = true }

[features]
default = []
hyperlight = ["dep:hyperlight_host"]
profiler = ["profiler/auto-calibrate"]
auto-calibrate = []
