# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "microvm"
version.workspace = true
license-file.workspace = true
edition = "2024"
authors.workspace = true
homepage.workspace = true

[lib]
name = "microvm"
path = "src/lib.rs"

[[bin]]
name = "microvm"
path = "src/main.rs"

[dependencies]
arch = { workspace = true, features = ["cpuid"] }
anyhow = { workspace = true }
bincode = { workspace = true, features = ["serde"] }
cfg-if = { workspace = true }
config = { workspace = true, features = ["microvm"] }
control-plane-api = { workspace = true }
hyperlight-host = { workspace = true, optional = true }
profiler = { workspace = true, features = ["auto-calibrate"] }
serde = { workspace = true, features = ["derive"] }
static_assert = { workspace = true }
sys = { workspace = true }
syscall = { workspace = true }
syscomm = { workspace = true }
user-vm-api = { workspace = true }
vmm-sys-util = { workspace = true }
syslog = { workspace = true, features = ["std"] }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { workspace = true, features = ["fam-wrappers", "serde"] }
kvm-ioctls = { workspace = true }
libc = { workspace = true }

[features]
default = []
hyperlight = ["dep:hyperlight-host", "config/hyperlight"]
profiler = ["profiler/auto-calibrate"]
auto-calibrate = []
timestamp-messages = ["profiler/timestamp-messages"]
