.\" 
.\" Copyright(C) 2011-2015 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This file is part of Nanvix.
.\" 
.\" Nanvix is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" Nanvix is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with Nanvix.  If not, see <http://www.gnu.org/licenses/>.
.\"

.TH "assert" "3" "April 2015" "Nanvix" "The Nanvix Programmer's Manual"

.\ "============================================================================

.SH "NAME"

assert \- Asserts a condition

.\ "============================================================================

.SH "SYNOPSIS"

.BI "#include <" "assert.h" >

.BI "void assert(scalar " expression ");"

.\ "============================================================================

.SH "DESCRIPTION"

The 
.BR assert()
macro inserts diagnostics into programs; it expands to a void expression. When
it is executed, if expression is false,
.BR assert()
writes information about the particular call that failed on 
.IR stderr
and calls
.BR abort() .

Forcing a definition of the name
.BR NDEBUG ,
stops assertions from being compiled into the program.

.\ "============================================================================

.SH "RETURN VALUE"

The
.BR assert()
macro does not return a value.

.\ "============================================================================

.SH "ERRORS"

No errors are defined.

.\ "============================================================================

.SH "CONFORMING TO"

POSIX.1-2008

.\ "============================================================================

.SH "AUTHOR"
Pedro H. Penna <pedrohenriquepenna@gmail.com>

.\ "============================================================================

.SH "SEE ALSO"

.BR abort(3)
