.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH atexit 3 "January 2014" "C Library" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
atexit \- Registers a function to run at process termination
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "#include <" "stdlib.h" >

.BI "int atexit(void (*" func ")(void));"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The 
.BR atexit()
function registers the function pointer pointed to by
.IR func ,
to be called at normal program termination. At normal program termination, all
functions registered by the
.BR atexit()
function are called in the reverse order of their registration. Normal 
termination occurs either by a call to 
.BR exit()
or a return from 
.BR main() .

At mots 
.BR ATEXIT_MAX
functions can be registered with 
.BR atexit() .
.\"
.\"=============================================================================
.\"
.SH "RETURN VALUE"
.\"
Upon successful completion, 
.BR atexit() 
return 0; otherwise it returns a non-zero value.
.\"
.\"=============================================================================
.\"
.SH ERRORS
.\"
No errors are defined.
.\"
.\"=============================================================================
.\"
.SH BUGS
.\"
Since the behavior is undefined if the 
.BR exit() 
function is called more than once, portable applications calling 
.BR atexit()
must ensure that the
.BR exit()
function is not called at normal process termination when all functions 
registered by 
.BR atexit()
function are called.

If, at a normal process termination, a function registered by the 
.BR atexit()
function is called and a portable application needs to stop further
.BR exit()
processing, it must call the
.BR _exti()
function or one of the function which cause abnormal process termination.
.
.\"
.\"=============================================================================
.\"
.SH "SEE ALSO"
.\"
.BR _exit(2) ,
.BR exit(3)
.\"
.\"=============================================================================
.\"
.SH "CONFORMING TO"
.\"
POSIX.1-2001
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
