.\" 
.\" Copyright(C) 2011-2015 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This file is part of Nanvix.
.\" 
.\" Nanvix is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" Nanvix is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with Nanvix.  If not, see <http://www.gnu.org/licenses/>.
.\"

.TH "ispunct" "3" "April 2015" "Nanvix" "The Nanvix Programmer's Manual"

.\ "============================================================================

.SH "NAME"

ispunct \- Checks for a punctuation character

.\ "============================================================================

.SH "SYNOPSIS"

.BI "#include <" "ctype.h" >

.BI "int ispunct(int " c ");"

.BI "int ispunct_l(int " c ", locale_t " locale ");"

.\ "============================================================================

.SH "DESCRIPTION"

The
.BR ispunct()
and
.BR ispunct_l()
functions test whether
.IR c
is a character of class
.BR punct
in the current locale, or in the locale represented by
.IR locale ,
respectively.

The behavior is undefined if the
.IR locale
argument to
.BR ispunct_l()
is the special locale object
.BR LC_GLOBAL_LOCALE
or is not a valid locale object handle.

.\ "============================================================================

.SH "RETURN VALUE"

The
.BR ispunct()
and
.BR ispunct_l() 
functions return non-zero if
.IR c
is a punctuation character; otherwise, they return 0.

.\ "============================================================================

.SH "ERRORS"

No errors are defined.

.\ "============================================================================

.SH "CONFORMING TO"

POSIX.1-2008

.\ "============================================================================

.SH "AUTHOR"
Pedro H. Penna <pedrohenriquepenna@gmail.com>

.\ "============================================================================

.SH "SEE ALSO"

.BR isalnum(3) , 
.BR isalpha(3) ,
.BR isblank(3) ,
.BR iscntrl(3) ,
.BR isdigit(3) ,
.BR isgraph(3) ,
.BR islower(3) ,
.BR isprint(3) ,
.BR isspace(3) ,
.BR isupper(3) ,
.BR isxdigit(3) ,
.BR setlocale(3) ,
.BR uselocale(3)
