.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH readdir 3 "January 2014" "C Library" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
rewinddir \- Rewinds a directory stream
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "#include <" "dirent.h" >

.BI "void rewinddir(DIR *" dirp ");"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The
.BR rewinddir()
resets the position of the directory stream pointed to by
.BR dirp
to the beginning of the directory.
.\"
.\"=============================================================================
.\"
.SH "RETURN VALUE"
.\"
The
.BR rewinddir()
returns no value.
.\"
.\"=============================================================================
.\"
.SH ERRORS
.\"
No errors are defined.
.\"
.\"=============================================================================
.\"
.SH "SEE ALSO"
.\"
.BR closedir(3) ,
.BR opendir(3) ,
.BR readdir(3)
.\"
.\"=============================================================================
.\"
.SH "CONFORMING TO"
.\"
POSIX.1-2001
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
