.\" 
.\" Copyright(C) 2011-2015 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This file is part of Nanvix.
.\" 
.\" Nanvix is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" Nanvix is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with Nanvix.  If not, see <http://www.gnu.org/licenses/>.
.\"

.TH "toupper" "3" "April 2015" "Nanvix" "The Nanvix Programmer's Manual"

.\ "============================================================================

.SH "NAME"

toupper \- Transliterates lowercase characters to uppercase

.\ "============================================================================

.SH "SYNOPSIS"

.BI "#include <" "ctype.h" >

.BI "int toupper(int " c ");"

.BI "int toupper_l(int " c ", locale_t " locale ");"

.\ "============================================================================

.SH "DESCRIPTION"

The
.BR toupper()
and
.BR toupper_l()
functions have as a domain a type int, the value of which is representable as
an unsigned char or the value of
.BR EOF .
If the argument has any other value, the behavior is undefined. If the argument
of
.BR toupper()
or
.BR toupper_l()
represents a lowercase letter, and there exists a corresponding uppercase
letter as defined by character type information in the current locale or in the
locale represented by 
.IR locale , 
respectively, the result is the corresponding uppercase letter. All other
arguments in the domain are returned unchanged.

The behavior is undefined if the locale argument to
.BR toupper_l()
is the special locale object
.BR LC_GLOBAL_LOCALE
or is not a valid locale object handle.

.\ "============================================================================

.SH "RETURN VALUE"

Upon successful completion, the
.BR toupper()
and
.BR toupper_l()
functions return the uppercase letter corresponding to the argument passed;
otherwise, they return the argument unchanged.

.\ "============================================================================

.SH "ERRORS"

No errors are defined.

.\ "============================================================================

.SH "CONFORMING TO"

POSIX.1-2008

.\ "============================================================================

.SH "AUTHOR"
Pedro H. Penna <pedrohenriquepenna@gmail.com>

.\ "============================================================================

.SH "SEE ALSO"

.BR tolower(3) ,
.BR setlocale(3) ,
.BR uselocale(3)
