# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "wasmd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "WASM Daemon"
homepage.workspace = true

[[bin]]
name = "wasmd"

[dependencies]
wasmi = { workspace = true }
nvx = { workspace = true, features = ["allocator"] }
posix = { workspace = true, features = ["syscall", "allocator"] }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[dev-dependencies]
wasm-bindgen = { workspace = true }

[features]
default = []
wasm_binary = []
