# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "strace"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Nanvix system call trace analyzer"
homepage.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }

[features]
default = []

[lints]
workspace = true
