# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nanvix-bench"
version.workspace = true
license-file.workspace = true
edition = "2024"
authors.workspace = true
description = "Benchmark Utility for Nanvix"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
config = { workspace = true }
flexi_logger = { workspace = true }
hwloc = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
microvm = { workspace = true }
nanvixd = { workspace = true }
nix = { workspace = true }
profiler = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
sys = { workspace = true, features = ["std"] }
syscall = { workspace = true, features = ["std"] }
syscomm = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
default = []
timestamp-messages = ["profiler/timestamp-messages"]
