# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "snapshot-test"
version.workspace = true
license-file.workspace = true
edition = "2024"
authors.workspace = true
description = "Integration test for snapshot save / restore lifecycle"
homepage.workspace = true

[[bin]]
name = "snapshot-test"

[dependencies]
nvx = { workspace = true }
nvx-crt0 = { workspace = true, features = ["rust-main", "provides-allocator"] }
sysalloc = { workspace = true }
libc_string = { workspace = true }
sys = { workspace = true, features = ["kcall"] }

[features]
default = ["panic"]
panic = ["nvx/panic", "nvx-crt0/panic"]

[lints]
workspace = true
