# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
nvx = { path = "../../libs/nvx", default-features = false, features = ["std"] }
anyhow = "1.0.95"
log = "0.4.22"
flexi_logger = "0.29.8"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.128"
