# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

all: all-echo-js all-hello-c all-hello-cpp all-hello-js

clean: clean-echo-js clean-hello-c clean-hello-cpp clean-hello-js

all-echo-js:
	$(MAKE) -C echo-js

clean-echo-js:
	$(MAKE) -C echo-js clean

all-hello-c:
	$(MAKE) -C hello-c

clean-hello-c:
	$(MAKE) -C hello-c clean

all-hello-cpp:
	$(MAKE) -C hello-cpp

clean-hello-cpp:
	$(MAKE) -C hello-cpp clean

all-hello-js:
	$(MAKE) -C hello-js

clean-hello-js:
	$(MAKE) -C hello-js clean
