# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

all: all-hello

clean: clean-hello

clippy:
	$(MAKE) -C hello clippy

all-hello:
	$(MAKE) -C hello

clean-hello:
	$(MAKE) -C hello clean

clippy-hello:
	$(MAKE) -C hello clippy
