# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

all:  all-hello-c all-hello-cpp

clean: clean-hello-c clean-hello-cpp

all-hello-c:
	$(MAKE) -C hello-c

clean-hello-c:
	$(MAKE) -C hello-c clean

all-hello-cpp:
	$(MAKE) -C hello-cpp

clean-hello-cpp:
	$(MAKE) -C hello-cpp clean
