# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "control-plane-api"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Control-Plane API Library"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true, features = ["serde"] }
config = { workspace = true }
num_enum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
syscomm = { workspace = true }
syslog = { workspace = true, features = ["std"] }
