.\"
.\" Copyright(C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.\"=============================================================================
.\"
.TH "cp" 1 "February 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
cp \- Copies a file
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "ls [" "options" "] " "source" " " "dest"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR cp 
copies the regular file
.IR source
onto the regular file
.IR dest .
The mode and the owner of the
.IR dest
file are preserved if it already existed; otherwise the mode of the
.IR source
file is used.

It is forbidden to copy a file onto itself.
.\"
.\"=============================================================================
.\"
.SH "OPTIONS"
.\"
.TP 
.BR --help
Display help information and exits.

.TP
.BR --version
Display program version and exits.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
