// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

use super::super::cpu::ContextInformation;
use ::core::arch::global_asm;

const CONTEXT_X: usize = core::mem::offset_of!(ContextInformation, x);
const CONTEXT_SP: usize = core::mem::offset_of!(ContextInformation, sp);
const CONTEXT_ELR: usize = core::mem::offset_of!(ContextInformation, elr);
const CONTEXT_SPSR: usize = core::mem::offset_of!(ContextInformation, spsr);
const CONTEXT_TTBR0: usize = core::mem::offset_of!(ContextInformation, ttbr0);
const CONTEXT_SP_EL0: usize = core::mem::offset_of!(ContextInformation, sp_el0);
const CONTEXT_TPIDR_EL0: usize = core::mem::offset_of!(ContextInformation, tpidr_el0);
const CONTEXT_SIZE: usize = core::mem::size_of::<ContextInformation>();

global_asm!(
    r#".section .text,"ax",@progbits"#,
    ".extern do_kcall",
    ".extern aarch64_exception_dispatch",
    ".extern aarch64_interrupt_dispatch",
    ".global __aarch64_vector_table",
    ".global __context_switch",
    ".global __leave_kernel",
    ".global __leave_kernel_to_user_mode",
    ".balign 2048",
    "__aarch64_vector_table:",
    // Current EL with SP0.
    "    b __aarch64_sync",
    "    .balign 128",
    "    b __aarch64_irq",
    "    .balign 128",
    "    b __aarch64_bad",
    "    .balign 128",
    "    b __aarch64_bad",
    // Current EL with SPx.
    "    .balign 128",
    "    b __aarch64_sync",
    "    .balign 128",
    "    b __aarch64_irq",
    "    .balign 128",
    "    b __aarch64_bad",
    "    .balign 128",
    "    b __aarch64_bad",
    // Lower EL using AArch64.
    "    .balign 128",
    "    b __aarch64_sync",
    "    .balign 128",
    "    b __aarch64_irq",
    "    .balign 128",
    "    b __aarch64_bad",
    "    .balign 128",
    "    b __aarch64_bad",
    // Lower EL using AArch32.
    "    .balign 128",
    "    b __aarch64_bad",
    "    .balign 128",
    "    b __aarch64_bad",
    "    .balign 128",
    "    b __aarch64_bad",
    "    .balign 128",
    "    b __aarch64_bad",

    "__aarch64_sync:",
    "    sub sp, sp, #{CONTEXT_SIZE}",
    "    stp x0, x1, [sp, #{CONTEXT_X}]",
    "    stp x2, x3, [sp, #({CONTEXT_X} + 16)]",
    "    stp x4, x5, [sp, #({CONTEXT_X} + 32)]",
    "    stp x6, x7, [sp, #({CONTEXT_X} + 48)]",
    "    stp x8, x9, [sp, #({CONTEXT_X} + 64)]",
    "    stp x10, x11, [sp, #({CONTEXT_X} + 80)]",
    "    stp x12, x13, [sp, #({CONTEXT_X} + 96)]",
    "    stp x14, x15, [sp, #({CONTEXT_X} + 112)]",
    "    stp x16, x17, [sp, #({CONTEXT_X} + 128)]",
    "    stp x18, x19, [sp, #({CONTEXT_X} + 144)]",
    "    stp x20, x21, [sp, #({CONTEXT_X} + 160)]",
    "    stp x22, x23, [sp, #({CONTEXT_X} + 176)]",
    "    stp x24, x25, [sp, #({CONTEXT_X} + 192)]",
    "    stp x26, x27, [sp, #({CONTEXT_X} + 208)]",
    "    stp x28, x29, [sp, #({CONTEXT_X} + 224)]",
    "    str x30, [sp, #({CONTEXT_X} + 240)]",
    "    mrs x9, sp_el0",
    "    str x9, [sp, #{CONTEXT_SP}]",
    "    mrs x9, elr_el1",
    "    str x9, [sp, #{CONTEXT_ELR}]",
    "    mrs x9, spsr_el1",
    "    str x9, [sp, #{CONTEXT_SPSR}]",
    "    mrs x9, ttbr0_el1",
    "    str x9, [sp, #{CONTEXT_TTBR0}]",
    "    add x9, sp, #{CONTEXT_SIZE}",
    "    str x9, [sp, #{CONTEXT_SP_EL0}]",
    "    mrs x9, tpidr_el0",
    "    str x9, [sp, #{CONTEXT_TPIDR_EL0}]",
    "    mrs x9, esr_el1",
    "    ubfx x10, x9, #26, #6",
    "    cmp x10, #0x15",
    "    b.ne 1f",
    // SVC: do_kcall(number=x8, args=x0..x3).
    "    mov w0, w8",
    "    ldr w1, [sp, #({CONTEXT_X} + 0)]",
    "    ldr w2, [sp, #({CONTEXT_X} + 8)]",
    "    ldr w3, [sp, #({CONTEXT_X} + 16)]",
    "    ldr w4, [sp, #({CONTEXT_X} + 24)]",
    // X0 carries both the kernel-call result and the first AAPCS64 handler argument. Remember the
    // original return context so a signal redirection performed inside do_kcall() is not clobbered
    // by the result write below.
    "    ldr x19, [sp, #{CONTEXT_ELR}]",
    "    ldr x20, [sp, #{CONTEXT_SP}]",
    "    bl do_kcall",
    "    ldr x9, [sp, #{CONTEXT_ELR}]",
    "    cmp x9, x19",
    "    b.ne 4f",
    "    ldr x9, [sp, #{CONTEXT_SP}]",
    "    cmp x9, x20",
    "    b.ne 4f",
    "    str x0, [sp, #{CONTEXT_X}]",
    "4:",
    // A kernel call may update TPIDR_EL0 (set_thread_data_area). Persist the new value in the
    // exception frame so the common restore path does not overwrite it with the entry value.
    "    mrs x9, tpidr_el0",
    "    str x9, [sp, #{CONTEXT_TPIDR_EL0}]",
    "    b __aarch64_restore",
    "1:",
    "    mov x0, sp",
    "    mov x1, x9",
    "    mrs x2, far_el1",
    "    bl aarch64_exception_dispatch",
    "    b __aarch64_restore",

    "__aarch64_irq:",
    // The full register-save sequence is shared with synchronous entries by synthesizing an ESR
    // class that cannot be mistaken for SVC and entering immediately after allocation.
    "    sub sp, sp, #{CONTEXT_SIZE}",
    "    stp x0, x1, [sp, #{CONTEXT_X}]",
    "    stp x2, x3, [sp, #({CONTEXT_X} + 16)]",
    "    stp x4, x5, [sp, #({CONTEXT_X} + 32)]",
    "    stp x6, x7, [sp, #({CONTEXT_X} + 48)]",
    "    stp x8, x9, [sp, #({CONTEXT_X} + 64)]",
    "    stp x10, x11, [sp, #({CONTEXT_X} + 80)]",
    "    stp x12, x13, [sp, #({CONTEXT_X} + 96)]",
    "    stp x14, x15, [sp, #({CONTEXT_X} + 112)]",
    "    stp x16, x17, [sp, #({CONTEXT_X} + 128)]",
    "    stp x18, x19, [sp, #({CONTEXT_X} + 144)]",
    "    stp x20, x21, [sp, #({CONTEXT_X} + 160)]",
    "    stp x22, x23, [sp, #({CONTEXT_X} + 176)]",
    "    stp x24, x25, [sp, #({CONTEXT_X} + 192)]",
    "    stp x26, x27, [sp, #({CONTEXT_X} + 208)]",
    "    stp x28, x29, [sp, #({CONTEXT_X} + 224)]",
    "    str x30, [sp, #({CONTEXT_X} + 240)]",
    "    mrs x9, sp_el0",
    "    str x9, [sp, #{CONTEXT_SP}]",
    "    mrs x9, elr_el1",
    "    str x9, [sp, #{CONTEXT_ELR}]",
    "    mrs x9, spsr_el1",
    "    str x9, [sp, #{CONTEXT_SPSR}]",
    "    mrs x9, ttbr0_el1",
    "    str x9, [sp, #{CONTEXT_TTBR0}]",
    "    add x9, sp, #{CONTEXT_SIZE}",
    "    str x9, [sp, #{CONTEXT_SP_EL0}]",
    "    mrs x9, tpidr_el0",
    "    str x9, [sp, #{CONTEXT_TPIDR_EL0}]",
    "    bl aarch64_interrupt_dispatch",
    "    b __aarch64_restore",

    "__aarch64_bad:",
    "    msr daifset, #0xf",
    "2:",
    "    wfi",
    "    b 2b",

    "__aarch64_restore:",
    "    ldr x9, [sp, #{CONTEXT_SP}]",
    "    msr sp_el0, x9",
    "    ldr x9, [sp, #{CONTEXT_ELR}]",
    "    msr elr_el1, x9",
    "    ldr x9, [sp, #{CONTEXT_SPSR}]",
    "    msr spsr_el1, x9",
    "    ldr x9, [sp, #{CONTEXT_TPIDR_EL0}]",
    "    msr tpidr_el0, x9",
    "    ldp x0, x1, [sp, #{CONTEXT_X}]",
    "    ldp x2, x3, [sp, #({CONTEXT_X} + 16)]",
    "    ldp x4, x5, [sp, #({CONTEXT_X} + 32)]",
    "    ldp x6, x7, [sp, #({CONTEXT_X} + 48)]",
    "    ldp x8, x9, [sp, #({CONTEXT_X} + 64)]",
    "    ldp x10, x11, [sp, #({CONTEXT_X} + 80)]",
    "    ldp x12, x13, [sp, #({CONTEXT_X} + 96)]",
    "    ldp x14, x15, [sp, #({CONTEXT_X} + 112)]",
    "    ldp x16, x17, [sp, #({CONTEXT_X} + 128)]",
    "    ldp x18, x19, [sp, #({CONTEXT_X} + 144)]",
    "    ldp x20, x21, [sp, #({CONTEXT_X} + 160)]",
    "    ldp x22, x23, [sp, #({CONTEXT_X} + 176)]",
    "    ldp x24, x25, [sp, #({CONTEXT_X} + 192)]",
    "    ldp x26, x27, [sp, #({CONTEXT_X} + 208)]",
    "    ldp x28, x29, [sp, #({CONTEXT_X} + 224)]",
    "    ldr x30, [sp, #({CONTEXT_X} + 240)]",
    "    add sp, sp, #{CONTEXT_SIZE}",
    "    eret",

    "__context_switch:",
    // x0=from, x1=to, x2=next TPIDR_EL0.
    "    stp x19, x20, [x0, #({CONTEXT_X} + 152)]",
    "    stp x21, x22, [x0, #({CONTEXT_X} + 168)]",
    "    stp x23, x24, [x0, #({CONTEXT_X} + 184)]",
    "    stp x25, x26, [x0, #({CONTEXT_X} + 200)]",
    "    stp x27, x28, [x0, #({CONTEXT_X} + 216)]",
    "    stp x29, x30, [x0, #({CONTEXT_X} + 232)]",
    "    mov x3, sp",
    "    str x3, [x0, #{CONTEXT_SP}]",
    "    mrs x3, ttbr0_el1",
    "    str x3, [x0, #{CONTEXT_TTBR0}]",
    "    str x2, [x1, #{CONTEXT_TPIDR_EL0}]",
    "    ldr x3, [x1, #{CONTEXT_TTBR0}]",
    "    cbz x3, 3f",
    "    msr ttbr0_el1, x3",
    "    dsb ish",
    "    tlbi vmalle1is",
    "    dsb ish",
    "    isb",
    "3:",
    "    ldr x3, [x1, #{CONTEXT_TPIDR_EL0}]",
    "    msr tpidr_el0, x3",
    "    ldp x19, x20, [x1, #({CONTEXT_X} + 152)]",
    "    ldp x21, x22, [x1, #({CONTEXT_X} + 168)]",
    "    ldp x23, x24, [x1, #({CONTEXT_X} + 184)]",
    "    ldp x25, x26, [x1, #({CONTEXT_X} + 200)]",
    "    ldp x27, x28, [x1, #({CONTEXT_X} + 216)]",
    "    ldp x29, x30, [x1, #({CONTEXT_X} + 232)]",
    "    ldr x3, [x1, #{CONTEXT_SP}]",
    "    mov sp, x3",
    "    ret",

    "__leave_kernel:",
    "    eret",

    "__leave_kernel_to_user_mode:",
    "    ldr x9, [sp], #8",
    "    ldr x10, [sp], #8",
    "    ldr x0, [sp], #8",
    "    ldr x1, [sp], #8",
    "    ldr x11, [sp], #8",
    "    msr elr_el1, x9",
    "    msr sp_el0, x10",
    "    msr spsr_el1, x11",
    "    eret",
    CONTEXT_X = const CONTEXT_X,
    CONTEXT_SP = const CONTEXT_SP,
    CONTEXT_ELR = const CONTEXT_ELR,
    CONTEXT_SPSR = const CONTEXT_SPSR,
    CONTEXT_TTBR0 = const CONTEXT_TTBR0,
    CONTEXT_SP_EL0 = const CONTEXT_SP_EL0,
    CONTEXT_TPIDR_EL0 = const CONTEXT_TPIDR_EL0,
    CONTEXT_SIZE = const CONTEXT_SIZE,
);
