# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "echo-rust-nostd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Echo Benchmark for Rust"
homepage.workspace = true

[[bin]]
name = "echo-rust-nostd"

[dependencies]
sys = { workspace = true }
nvx = { workspace = true, features = ["sysalloc"] }
syscall = { workspace = true, features = ["syscall"] }
sysalloc = { workspace = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
trace = ["nvx/trace"]
debug = ["nvx/debug"]
info = ["nvx/info"]
warn = ["nvx/warn"]
error = ["nvx/error"]
panic = ["nvx/panic"]
