# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

all: all-initd all-memd all-testd

clean: clean-initd clean-memd clean-testd

all-initd:
	$(MAKE) -C initd all

clean-initd:
	$(MAKE) -C initd clean

all-memd:
	$(MAKE) -C memd all

clean-memd:

all-testd:
	$(MAKE) -C testd all

clean-testd:
	$(MAKE) -C testd clean
