[package]
name = "nanvix-shim-standalone"
description = "Standalone execution mode for the Nanvix containerd shim"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nanvix-oci = { workspace = true }
nanvix-shim-core = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
tempfile = "3"

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[dev-dependencies]
tempfile = "3"
