# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "sysalloc"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "System Allocator"
homepage.workspace = true

[dependencies]
arch = { workspace = true }
talc = { workspace = true }
cfg-if = { workspace = true }
config = { workspace = true }
syslog = { workspace = true }
sys = { workspace = true, features = ["kcall"] }
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1", optional = true }

[features]
default = []
staticlib = []
rustc-dep-of-std = [
    "alloc",
    "core",
    "arch/rustc-dep-of-std",
    "talc/rustc-dep-of-std",
    "config/rustc-dep-of-std",
    "compiler_builtins/rustc-dep-of-std",
    "sys/rustc-dep-of-std",
    "syslog/rustc-dep-of-std",
    "cfg-if/rustc-dep-of-std",
]

# Logging Features
trace = ["syslog/trace"]
debug = ["syslog/debug"]
info = ["syslog/info"]
warn = ["syslog/warn"]
error = ["syslog/error"]
panic = ["syslog/panic"]
