# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "procd"
version = "0.0.1"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Process Management Daemon"
homepage = "https://github.com/nanvix"

[dependencies]
procd = { path = "../../libs/procd", features = ["daemon"] }
nvx = { path = "../../libs/nvx" }

[build-dependencies]
cc = "1.2.6"
cfg-if = "1.0.0"
