# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nanvixd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Orchestration Daemon for Nanvix"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["std", "clock"] }
log = { workspace = true }
nanvix = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["microvm"]
gdb = ["nanvix/gdb"]
# Enables fine-grained time profiling.
profile-time = ["nanvix/profile-time"]
microvm = ["nanvix/microvm"]
whp = ["nanvix/whp"]

[lints]
workspace = true
