# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nanvixd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Orchestration Daemon for the Nanvix"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
config = { workspace = true }
control-plane-api = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
hwloc = { workspace = true }
libc = { workspace = true }
linuxd = { workspace = true }
num_enum = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
sys = { workspace = true }
syscomm = { workspace = true }
syslog = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
user-vm-api = { workspace = true }
uservm = { workspace = true }
