# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nanvixd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Orchestration Daemon for Nanvix"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
config = { workspace = true }
control-plane-api = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
hwloc = { workspace = true }
libc = { workspace = true }
linuxd = { workspace = true }
nanvix-sandbox = { workspace = true }
nanvix-sandbox-cache = { workspace = true }
nanvix-terminal = { workspace = true }
num_enum = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
sys = { workspace = true }
syscomm = { workspace = true }
syslog = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
user-vm-api = { workspace = true }
uservm = { workspace = true }

[features]
default = []
# If enabled this feature is enabled, the Linux Daemon (linuxd) and User VM (uservm) are embedded
# into Nanvix Daemon (nanvixd).
single-process = [
    "nanvix-sandbox/single-process",
    "nanvix-sandbox-cache/single-process",
    "nanvix-terminal/single-process",
]
hyperlight = [
    "config/hyperlight",
    "uservm/hyperlight",
    "nanvix-sandbox/hyperlight",
]
