.\"
.\" Copyright (C) 2011-2013 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH getppid 2 "August 2013" "System Calls" "The Nanvix Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
getppid \- Gets the parent process ID of the calling process.
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.IR "#include <unistd.h>"

.BI "pid_t getppid(void);"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The
.BR getppid()
system call returns the parent process ID of the calling process.
.\"
.\"=============================================================================
.\"
.SH "RETURN VALUE"
.\"
The 
.BR getppid()
system call is always successful and no return value is reserved to indicate an
error.
.\"
.\"=============================================================================
.\"
.SH ERRORS
.\"
No errors are defined.
.\"
.\"=============================================================================
.\"
.SH "CONFORMING TO"
.\"
POSIX.1-2001
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.SH "SEE ALSO"
.\"
.BR exec(2) ,
.BR fork(2) ,
.BR getpgrp(2) ,
.BR getpid(2) ,
.BR kill(2) ,
.BR setpgrp(2)
