# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "linuxd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Linux Provider Daemon"
homepage.workspace = true

[dependencies]
config = { workspace = true }
syscall = { workspace = true, features = ["std"] }
anyhow = { workspace = true }
log = { workspace = true }
flexi_logger = { workspace = true }
libc = { workspace = true }
signal-hook = { workspace = true }
nvx = { workspace = true, features = ["std"] }
syscomm = { workspace = true }
