# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "linuxd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Linux Provider Daemon"
homepage.workspace = true

[lib]
name = "linuxd"
path = "src/lib.rs"

[[bin]]
name = "linuxd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
config = { workspace = true }
control-plane-api = { workspace = true }
libc = { workspace = true }
net-backend = { workspace = true }
profiler = { workspace = true }
rand = { workspace = true }
signal-hook = { workspace = true }
static_assert = { workspace = true }
sys = { workspace = true, features = ["std"] }
sysapi = { workspace = true, features = ["std"] }
syscall = { workspace = true, features = ["std"] }
syscomm = { workspace = true }
log = { workspace = true }
syslog = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
user-vm-api = { workspace = true }

[features]
default = []
timestamp-messages = ["profiler/timestamp-messages"]

[lints]
workspace = true
