# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "syscall"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "System Call Library"
homepage.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
nvx = { workspace = true }
sys = { workspace = true }
config = { workspace = true }
cfg-if = { workspace = true }
elf = { workspace = true }
goblin = { workspace = true, features = [
    "elf32",
    "elf64",
    "endian_fd",
    "mach32",
    "mach64",
] }
num_enum = { workspace = true }
spin = { workspace = true, features = ["lazy", "spin_mutex"] }
static_assert = { workspace = true }
sysalloc = { workspace = true, optional = true }
syslog = { workspace = true }
type-safe = { workspace = true }

[features]
default = ["syscall", "allocator", "staticlib", "pthread", "sbrk"]
allocator = ["dep:sysalloc", "nvx/allocator"]
syscall = []
std = ["nvx/std"]
staticlib = ["nvx/staticlib", "sysalloc/staticlib"]
pthread = []
sbrk = []

# Logging
trace = ["nvx/trace", "syslog/trace"]
debug = ["nvx/debug", "syslog/debug"]
info = ["nvx/info", "syslog/info"]
warn = ["nvx/warn", "syslog/warn"]
error = ["nvx/error", "syslog/error"]
panic = ["nvx/panic", "syslog/panic"]
