// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//==================================================================================================
// Configuration
//==================================================================================================

#![no_std]
#![no_main]

//==================================================================================================
// Modules
//==================================================================================================

extern crate alloc;
extern crate libc_string;
extern crate nvx;

//==================================================================================================
// Imports
//==================================================================================================

use ::alloc::vec;
use ::core::ptr;
use ::sys::{
    error::{
        Error,
        ErrorCode,
    },
    kcall::{
        mm,
        pm,
    },
    mm::Address,
    pm::Capability,
};

//==================================================================================================
// Constants
//==================================================================================================

/// Encoded 8-byte "RAMFS   " tag exposed by the MicroVM RAMFS MMIO region.
const RAMFS_MMIO_TAG: u64 = u64::from_be_bytes(*b"RAMFS   ");

//==================================================================================================
// Helpers
//==================================================================================================

/// Converts a [`vfs::Fat32Error`] to an [`Error`], preserving the error code.
fn fat_err(e: vfs::Fat32Error, reason: &'static str) -> Error {
    Error::new(ErrorCode::from(e), reason)
}

//==================================================================================================
// Entry Point
//==================================================================================================

#[no_mangle]
pub fn main() -> Result<(), Error> {
    // Initialize the vfs filesystem.
    vfs::init().map_err(|e| fat_err(e, "vfs init failed"))?;

    // Run tests.
    test_create_mount()?;
    test_rename_unlink()?;
    test_chdir_cwd()?;
    test_pread_pwrite()?;
    test_ftruncate_fsync()?;
    test_ramfs_mount()?;

    Ok(())
}

//==================================================================================================
// Test: Mount RAMFS Image
//==================================================================================================

/// Tests mounting a FAT image provided via the RAMFS MMIO region.
///
/// The FAT image is generated by build.rs and passed to nanvixd via `-ramfs`.
/// Since the RAMFS region is read-only in the guest, the image is copied to a
/// heap buffer before mounting.
fn test_ramfs_mount() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_ramfs_mount begin");

    let mut cap_acquired: bool = false;
    let mut region_attached: bool = false;

    let result: Result<(), Error> = (|| {
        // Acquire IO management capability.
        pm::capctl(Capability::IoManagement, true)?;
        cap_acquired = true;

        // Attach RAMFS MMIO region.
        mm::mmio_alloc(RAMFS_MMIO_TAG)?;
        region_attached = true;

        // Get region info.
        let info: ::sys::mm::MmioRegionInfo = mm::mmio_info(RAMFS_MMIO_TAG)?;
        let total_size: usize = info.size();

        ::syslog::info!("vfs-test: ramfs region (size={})", total_size,);

        // Copy RAMFS to heap buffer (RAMFS is read-only in guest).
        let mut buffer: alloc::vec::Vec<u8> = vec![0u8; total_size];
        unsafe {
            let src: *const u8 = info.base().as_ptr();
            for (i, byte) in buffer.iter_mut().enumerate() {
                *byte = ptr::read_volatile(src.add(i));
            }
        }

        // Release MMIO region before mounting.
        mm::mmio_free(RAMFS_MMIO_TAG)?;
        region_attached = false;
        pm::capctl(Capability::IoManagement, false)?;
        cap_acquired = false;

        // Leak the buffer so it lives for the program's lifetime.
        // SAFETY: The mount holds a raw pointer into this buffer, so it
        // must not be deallocated while the mount exists.
        let leaked: &'static mut [u8] = alloc::boxed::Box::leak(buffer.into_boxed_slice());

        // Mount the FAT image.
        unsafe {
            vfs::mount_image("/ramfs", leaked.as_mut_ptr(), leaked.len())
                .map_err(|e| fat_err(e, "vfs mount failed"))?;
        }

        // Verify hello.txt exists and contains expected content.
        verify_file("/ramfs/hello.txt", b"Hello from FAT32 on Nanvix!\n")?;

        // Verify subdirectory and nested file.
        let info: vfs::Stat =
            vfs::stat("/ramfs/subdir").map_err(|e| fat_err(e, "stat subdir failed"))?;
        if !info.is_dir() {
            return Err(Error::new(ErrorCode::InvalidArgument, "subdir should be a directory"));
        }

        verify_file("/ramfs/subdir/nested.txt", b"nested content\n")?;

        // Verify read_dir on root.
        let entries: alloc::vec::Vec<vfs::DirEntry> =
            vfs::read_dir("/ramfs").map_err(|e| fat_err(e, "read_dir /ramfs failed"))?;
        if entries.len() != 2 {
            return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 entries in /ramfs"));
        }

        ::syslog::info!("vfs-test: test_ramfs_mount passed");
        Ok(())
    })();

    // Cleanup on error.
    if region_attached {
        let _ = mm::mmio_free(RAMFS_MMIO_TAG);
    }
    if cap_acquired {
        let _ = pm::capctl(Capability::IoManagement, false);
    }

    result
}

//==================================================================================================
// Test: Create In-Memory Mount
//==================================================================================================

/// Tests creating an in-memory FAT filesystem via `create_mount`.
///
/// Validates write, read, stat, mkdir, readdir, rmdir, unlink, and unmount.
fn test_create_mount() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_create_mount begin");

    // Create an in-memory FAT mount.
    vfs::create_mount("/scratch", 128 * 1024).map_err(|e| fat_err(e, "create_mount failed"))?;

    // Write a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/scratch/test.txt")
            .map_err(|e| fat_err(e, "failed to create test.txt"))?;
        file.write(b"test data")
            .map_err(|e| fat_err(e, "failed to write test.txt"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush test.txt"))?;
    }

    // Read it back.
    {
        let mut file: vfs::File =
            vfs::open("/scratch/test.txt").map_err(|e| fat_err(e, "failed to open test.txt"))?;
        let content: alloc::vec::Vec<u8> = file
            .read_to_vec()
            .map_err(|e| fat_err(e, "failed to read test.txt"))?;
        if content.as_slice() != b"test data" {
            return Err(Error::new(ErrorCode::InvalidArgument, "test.txt content mismatch"));
        }
    }

    // Verify stat.
    let info: vfs::Stat =
        vfs::stat("/scratch/test.txt").map_err(|e| fat_err(e, "stat test.txt failed"))?;
    if info.is_dir() {
        return Err(Error::new(ErrorCode::InvalidArgument, "test.txt should not be a directory"));
    }
    if info.size() != 9 {
        return Err(Error::new(ErrorCode::InvalidArgument, "test.txt size mismatch"));
    }

    // Test mkdir.
    vfs::mkdir("/scratch/mydir").map_err(|e| fat_err(e, "mkdir failed"))?;

    // Verify read_dir sees both entries.
    let entries: alloc::vec::Vec<vfs::DirEntry> =
        vfs::read_dir("/scratch").map_err(|e| fat_err(e, "read_dir failed"))?;
    if entries.len() != 2 {
        return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 entries in /scratch"));
    }

    // Clean up: remove directory and file, then unmount.
    vfs::rmdir("/scratch/mydir").map_err(|e| fat_err(e, "rmdir failed"))?;
    vfs::unlink("/scratch/test.txt").map_err(|e| fat_err(e, "unlink failed"))?;
    vfs::unmount("/scratch").map_err(|e| fat_err(e, "unmount failed"))?;

    ::syslog::info!("vfs-test: test_create_mount passed");
    Ok(())
}

//==================================================================================================
// Test: Rename and Unlink
//==================================================================================================

/// Tests rename and unlink operations on the VFS.
fn test_rename_unlink() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_rename_unlink begin");

    vfs::create_mount("/ren", 128 * 1024).map_err(|e| fat_err(e, "create_mount /ren failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/ren/orig.txt")
            .map_err(|e| fat_err(e, "failed to create orig.txt"))?;
        file.write(b"rename me")
            .map_err(|e| fat_err(e, "failed to write orig.txt"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush orig.txt"))?;
    }

    // Rename the file.
    vfs::rename("/ren/orig.txt", "/ren/moved.txt").map_err(|e| fat_err(e, "rename failed"))?;

    // Verify old name is gone.
    if vfs::stat("/ren/orig.txt").is_ok() {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "orig.txt should not exist after rename",
        ));
    }

    // Verify new name exists with correct content.
    verify_file("/ren/moved.txt", b"rename me")?;

    // Unlink the renamed file.
    vfs::unlink("/ren/moved.txt").map_err(|e| fat_err(e, "unlink failed"))?;

    // Verify the file is gone.
    if vfs::stat("/ren/moved.txt").is_ok() {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "moved.txt should not exist after unlink",
        ));
    }

    vfs::unmount("/ren").map_err(|e| fat_err(e, "unmount /ren failed"))?;

    ::syslog::info!("vfs-test: test_rename_unlink passed");
    Ok(())
}

//==================================================================================================
// Test: Chdir and Cwd
//==================================================================================================

/// Tests chdir and cwd operations on the VFS.
fn test_chdir_cwd() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_chdir_cwd begin");

    vfs::create_mount("/cd", 128 * 1024).map_err(|e| fat_err(e, "create_mount /cd failed"))?;

    // Create a subdirectory.
    vfs::mkdir("/cd/sub").map_err(|e| fat_err(e, "mkdir /cd/sub failed"))?;

    // Verify initial cwd is root.
    let initial_cwd: alloc::string::String = vfs::cwd().map_err(|e| fat_err(e, "cwd failed"))?;
    if initial_cwd != "/" {
        return Err(Error::new(ErrorCode::InvalidArgument, "initial cwd should be /"));
    }

    // Change to the mount root.
    vfs::chdir("/cd").map_err(|e| fat_err(e, "chdir /cd failed"))?;
    let cwd: alloc::string::String =
        vfs::cwd().map_err(|e| fat_err(e, "cwd after chdir failed"))?;
    if cwd != "/cd" {
        return Err(Error::new(ErrorCode::InvalidArgument, "cwd should be /cd"));
    }

    // Change to subdirectory.
    vfs::chdir("/cd/sub").map_err(|e| fat_err(e, "chdir /cd/sub failed"))?;
    let cwd2: alloc::string::String =
        vfs::cwd().map_err(|e| fat_err(e, "cwd after chdir sub failed"))?;
    if cwd2 != "/cd/sub" {
        return Err(Error::new(ErrorCode::InvalidArgument, "cwd should be /cd/sub"));
    }

    // Change back to root.
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir / failed"))?;

    // Clean up.
    vfs::rmdir("/cd/sub").map_err(|e| fat_err(e, "rmdir /cd/sub failed"))?;
    vfs::unmount("/cd").map_err(|e| fat_err(e, "unmount /cd failed"))?;

    ::syslog::info!("vfs-test: test_chdir_cwd passed");
    Ok(())
}

//==================================================================================================
// Test: Pread and Pwrite
//==================================================================================================

/// Tests positional read/write without changing file position.
fn test_pread_pwrite() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_pread_pwrite begin");

    vfs::create_mount("/pp", 128 * 1024).map_err(|e| fat_err(e, "create_mount /pp failed"))?;

    // Create and write sequential data.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/pp/data.bin")
            .map_err(|e| fat_err(e, "failed to create data.bin"))?;
        file.write(b"AABBCCDDEE")
            .map_err(|e| fat_err(e, "failed to write data.bin"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush data.bin"))?;
    }

    // Open for reading and verify pread at offset.
    {
        let mut file: vfs::File =
            vfs::open("/pp/data.bin").map_err(|e| fat_err(e, "failed to open data.bin"))?;

        // Read at offset 4 (should get "CCDDEE").
        let mut buf: [u8; 6] = [0u8; 6];
        file.seek(0, 4).map_err(|e| fat_err(e, "seek failed"))?;
        let n: usize = file.read(&mut buf).map_err(|e| fat_err(e, "read failed"))?;
        if n != 6 || &buf[..6] != b"CCDDEE" {
            return Err(Error::new(ErrorCode::InvalidArgument, "pread content mismatch"));
        }

        // Verify we can still read from the start.
        file.seek(0, 0)
            .map_err(|e| fat_err(e, "seek back failed"))?;
        let mut buf2: [u8; 2] = [0u8; 2];
        let n2: usize = file
            .read(&mut buf2)
            .map_err(|e| fat_err(e, "read2 failed"))?;
        if n2 != 2 || &buf2 != b"AA" {
            return Err(Error::new(ErrorCode::InvalidArgument, "read from start mismatch"));
        }
    }

    // Clean up.
    vfs::unlink("/pp/data.bin").map_err(|e| fat_err(e, "unlink failed"))?;
    vfs::unmount("/pp").map_err(|e| fat_err(e, "unmount /pp failed"))?;

    ::syslog::info!("vfs-test: test_pread_pwrite passed");
    Ok(())
}

//==================================================================================================
// Test: Ftruncate and Fsync
//==================================================================================================

/// Tests file truncation and sync on the VFS.
fn test_ftruncate_fsync() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_ftruncate_fsync begin");

    vfs::create_mount("/trunc", 128 * 1024)
        .map_err(|e| fat_err(e, "create_mount /trunc failed"))?;

    // Create a file with content.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/trunc/file.txt")
            .map_err(|e| fat_err(e, "failed to create file.txt"))?;
        file.write(b"hello world!")
            .map_err(|e| fat_err(e, "failed to write file.txt"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush file.txt"))?;
    }

    // Verify initial size.
    let info: vfs::Stat =
        vfs::stat("/trunc/file.txt").map_err(|e| fat_err(e, "stat file.txt failed"))?;
    if info.size() != 12 {
        return Err(Error::new(ErrorCode::InvalidArgument, "initial size should be 12"));
    }

    // Open and truncate to 5 bytes.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .read(true)
            .write(true)
            .open("/trunc/file.txt")
            .map_err(|e| fat_err(e, "failed to open file.txt for truncation"))?;
        file.seek(0, 5)
            .map_err(|e| fat_err(e, "seek to 5 failed"))?;
        file.truncate().map_err(|e| fat_err(e, "truncate failed"))?;
        file.flush()
            .map_err(|e| fat_err(e, "flush after truncate failed"))?;
    }

    // Verify truncated content.
    let info2: vfs::Stat =
        vfs::stat("/trunc/file.txt").map_err(|e| fat_err(e, "stat after truncate"))?;
    if info2.size() != 5 {
        return Err(Error::new(ErrorCode::InvalidArgument, "truncated size should be 5"));
    }
    verify_file("/trunc/file.txt", b"hello")?;

    // Clean up.
    vfs::unlink("/trunc/file.txt").map_err(|e| fat_err(e, "unlink file.txt"))?;
    vfs::unmount("/trunc").map_err(|e| fat_err(e, "unmount /trunc"))?;

    ::syslog::info!("vfs-test: test_ftruncate_fsync passed");
    Ok(())
}

//==================================================================================================
// Helpers
//==================================================================================================

/// Opens a file and verifies its contents match `expected`.
fn verify_file(path: &str, expected: &[u8]) -> Result<(), Error> {
    let mut file: vfs::File = vfs::open(path).map_err(|e| fat_err(e, "failed to open file"))?;
    let content: alloc::vec::Vec<u8> = file
        .read_to_vec()
        .map_err(|e| fat_err(e, "failed to read file"))?;
    if content.as_slice() != expected {
        return Err(Error::new(ErrorCode::InvalidArgument, "file content mismatch"));
    }
    Ok(())
}
