// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//==================================================================================================
// Configuration
//==================================================================================================

#![no_std]
#![no_main]

//==================================================================================================
// Modules
//==================================================================================================

extern crate alloc;
extern crate libc_string;
extern crate nvx;
extern crate nvx_crt0;

//==================================================================================================
// Imports
//==================================================================================================

use ::alloc::vec;
use ::core::ptr;
use ::sys::{
    error::{
        Error,
        ErrorCode,
    },
    kcall::{
        mm,
        pm,
    },
    mm::Address,
    pm::Capability,
};
use ::sysapi::{
    dirent::{
        dirent_file_type,
        posix_dent,
    },
    fcntl::{
        file_control_request,
        file_creation_flags,
    },
    sys_stat::{
        file_type,
        stat,
    },
    time::timespec,
};

//==================================================================================================
// Constants
//==================================================================================================

/// Encoded 8-byte "RAMFS   " tag exposed by the MicroVM RAMFS MMIO region.
const RAMFS_MMIO_TAG: u64 = u64::from_be_bytes(*b"RAMFS   ");

/// Fixed timestamp epoch (2024-01-01T00:00:00 UTC) used by the VFS stat layer.
const VFS_FIXED_TIMESTAMP: i64 = 1704067200;

//==================================================================================================
// Helpers
//==================================================================================================

/// Converts a [`vfs::Fat32Error`] to an [`Error`], preserving the error code.
fn fat_err(e: vfs::Fat32Error, reason: &'static str) -> Error {
    Error::new(ErrorCode::from(e), reason)
}

//==================================================================================================
// Entry Point
//==================================================================================================

#[no_mangle]
pub fn main() -> Result<(), Error> {
    // Initialize the vfs filesystem.
    vfs::init().map_err(|e| fat_err(e, "vfs init failed"))?;

    // Run tests.
    test_create_mount()?;
    test_rename_unlink()?;
    test_chdir_cwd()?;
    test_pread_pwrite()?;
    test_ftruncate_fsync()?;
    test_open_directory()?;
    test_getdents()?;
    test_fstat_directory_and_timestamps()?;
    test_stat_timestamps()?;
    test_fcntl_fd_flags()?;
    test_resolve_path()?;
    test_chmod()?;
    test_fchmodat()?;
    test_fchownat()?;
    test_utimensat()?;
    test_openat()?;
    test_mkdirat()?;
    test_accessat()?;
    test_fstatat()?;
    test_ramfs_mount()?;

    Ok(())
}

//==================================================================================================
// Test: Mount RAMFS Image
//==================================================================================================

/// Tests mounting a FAT image provided via the RAMFS MMIO region.
///
/// The FAT image is generated by build.rs and passed to nanvixd via `-ramfs`.
/// Since the RAMFS region is read-only in the guest, the image is copied to a
/// heap buffer before mounting.
fn test_ramfs_mount() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_ramfs_mount begin");

    let mut cap_acquired: bool = false;
    let mut region_attached: bool = false;

    let result: Result<(), Error> = (|| {
        // Acquire IO management capability.
        pm::__kcall_capctl(Capability::IoManagement, true)?;
        cap_acquired = true;

        // Attach RAMFS MMIO region.
        mm::__kcall_mmio_alloc(RAMFS_MMIO_TAG)?;
        region_attached = true;

        // Get region info.
        let info: ::sys::mm::MmioRegionInfo = mm::__kcall_mmio_info(RAMFS_MMIO_TAG)?;
        let total_size: usize = info.size();

        ::syslog::info!("vfs-test: ramfs region (size={})", total_size,);

        // Copy RAMFS to heap buffer (RAMFS is read-only in guest).
        let mut buffer: alloc::vec::Vec<u8> = vec![0u8; total_size];
        unsafe {
            let src: *const u8 = info.base().as_ptr();
            for (i, byte) in buffer.iter_mut().enumerate() {
                *byte = ptr::read_volatile(src.add(i));
            }
        }

        // Release MMIO region before mounting.
        mm::__kcall_mmio_free(RAMFS_MMIO_TAG)?;
        region_attached = false;
        pm::__kcall_capctl(Capability::IoManagement, false)?;
        cap_acquired = false;

        // Leak the buffer so it lives for the program's lifetime.
        // SAFETY: The mount holds a raw pointer into this buffer, so it
        // must not be deallocated while the mount exists.
        let leaked: &'static mut [u8] = alloc::boxed::Box::leak(buffer.into_boxed_slice());

        // Mount the FAT image.
        unsafe {
            vfs::mount_image("/ramfs", leaked.as_mut_ptr(), leaked.len(), false)
                .map_err(|e| fat_err(e, "vfs mount failed"))?;
        }

        // Verify hello.txt exists and contains expected content.
        verify_file("/ramfs/hello.txt", b"Hello from FAT32 on Nanvix!\n")?;

        // Verify subdirectory and nested file.
        let info: vfs::Stat =
            vfs::stat("/ramfs/subdir").map_err(|e| fat_err(e, "stat subdir failed"))?;
        if !info.is_dir() {
            return Err(Error::new(ErrorCode::InvalidArgument, "subdir should be a directory"));
        }

        verify_file("/ramfs/subdir/nested.txt", b"nested content\n")?;

        // Verify read_dir on root.
        let entries: alloc::vec::Vec<vfs::DirEntry> =
            vfs::read_dir("/ramfs").map_err(|e| fat_err(e, "read_dir /ramfs failed"))?;
        if entries.len() != 2 {
            return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 entries in /ramfs"));
        }

        ::syslog::info!("vfs-test: test_ramfs_mount passed");
        Ok(())
    })();

    // Cleanup on error.
    if region_attached {
        let _ = mm::__kcall_mmio_free(RAMFS_MMIO_TAG);
    }
    if cap_acquired {
        let _ = pm::__kcall_capctl(Capability::IoManagement, false);
    }

    result
}

//==================================================================================================
// Test: Create In-Memory Mount
//==================================================================================================

/// Tests creating an in-memory FAT filesystem via `create_mount`.
///
/// Validates write, read, stat, mkdir, readdir, rmdir, unlink, and unmount.
fn test_create_mount() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_create_mount begin");

    // Create an in-memory FAT mount.
    vfs::create_mount("/scratch", 128 * 1024).map_err(|e| fat_err(e, "create_mount failed"))?;

    // Write a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/scratch/test.txt")
            .map_err(|e| fat_err(e, "failed to create test.txt"))?;
        file.write(b"test data")
            .map_err(|e| fat_err(e, "failed to write test.txt"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush test.txt"))?;
    }

    // Read it back.
    {
        let mut file: vfs::File =
            vfs::open("/scratch/test.txt").map_err(|e| fat_err(e, "failed to open test.txt"))?;
        let content: alloc::vec::Vec<u8> = file
            .read_to_vec()
            .map_err(|e| fat_err(e, "failed to read test.txt"))?;
        if content.as_slice() != b"test data" {
            return Err(Error::new(ErrorCode::InvalidArgument, "test.txt content mismatch"));
        }
    }

    // Verify stat.
    let info: vfs::Stat =
        vfs::stat("/scratch/test.txt").map_err(|e| fat_err(e, "stat test.txt failed"))?;
    if info.is_dir() {
        return Err(Error::new(ErrorCode::InvalidArgument, "test.txt should not be a directory"));
    }
    if info.size() != 9 {
        return Err(Error::new(ErrorCode::InvalidArgument, "test.txt size mismatch"));
    }

    // Test mkdir.
    vfs::mkdir("/scratch/mydir").map_err(|e| fat_err(e, "mkdir failed"))?;

    // Verify read_dir sees both entries.
    let entries: alloc::vec::Vec<vfs::DirEntry> =
        vfs::read_dir("/scratch").map_err(|e| fat_err(e, "read_dir failed"))?;
    if entries.len() != 2 {
        return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 entries in /scratch"));
    }

    // Clean up: remove directory and file, then unmount.
    vfs::rmdir("/scratch/mydir").map_err(|e| fat_err(e, "rmdir failed"))?;
    vfs::unlink("/scratch/test.txt").map_err(|e| fat_err(e, "unlink failed"))?;
    vfs::unmount("/scratch").map_err(|e| fat_err(e, "unmount failed"))?;

    ::syslog::info!("vfs-test: test_create_mount passed");
    Ok(())
}

//==================================================================================================
// Test: Rename and Unlink
//==================================================================================================

/// Tests rename and unlink operations on the VFS.
fn test_rename_unlink() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_rename_unlink begin");

    vfs::create_mount("/ren", 128 * 1024).map_err(|e| fat_err(e, "create_mount /ren failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/ren/orig.txt")
            .map_err(|e| fat_err(e, "failed to create orig.txt"))?;
        file.write(b"rename me")
            .map_err(|e| fat_err(e, "failed to write orig.txt"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush orig.txt"))?;
    }

    // Rename the file.
    vfs::rename("/ren/orig.txt", "/ren/moved.txt").map_err(|e| fat_err(e, "rename failed"))?;

    // Verify old name is gone.
    if vfs::stat("/ren/orig.txt").is_ok() {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "orig.txt should not exist after rename",
        ));
    }

    // Verify new name exists with correct content.
    verify_file("/ren/moved.txt", b"rename me")?;

    // Unlink the renamed file.
    vfs::unlink("/ren/moved.txt").map_err(|e| fat_err(e, "unlink failed"))?;

    // Verify the file is gone.
    if vfs::stat("/ren/moved.txt").is_ok() {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "moved.txt should not exist after unlink",
        ));
    }

    vfs::unmount("/ren").map_err(|e| fat_err(e, "unmount /ren failed"))?;

    ::syslog::info!("vfs-test: test_rename_unlink passed");
    Ok(())
}

//==================================================================================================
// Test: Chdir and Cwd
//==================================================================================================

/// Tests chdir and cwd operations on the VFS.
fn test_chdir_cwd() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_chdir_cwd begin");

    vfs::create_mount("/cd", 128 * 1024).map_err(|e| fat_err(e, "create_mount /cd failed"))?;

    // Create a subdirectory.
    vfs::mkdir("/cd/sub").map_err(|e| fat_err(e, "mkdir /cd/sub failed"))?;

    // Verify initial cwd is root.
    let initial_cwd: alloc::string::String = vfs::cwd().map_err(|e| fat_err(e, "cwd failed"))?;
    if initial_cwd != "/" {
        return Err(Error::new(ErrorCode::InvalidArgument, "initial cwd should be /"));
    }

    // Change to the mount root.
    vfs::chdir("/cd").map_err(|e| fat_err(e, "chdir /cd failed"))?;
    let cwd: alloc::string::String =
        vfs::cwd().map_err(|e| fat_err(e, "cwd after chdir failed"))?;
    if cwd != "/cd" {
        return Err(Error::new(ErrorCode::InvalidArgument, "cwd should be /cd"));
    }

    // Change to subdirectory.
    vfs::chdir("/cd/sub").map_err(|e| fat_err(e, "chdir /cd/sub failed"))?;
    let cwd2: alloc::string::String =
        vfs::cwd().map_err(|e| fat_err(e, "cwd after chdir sub failed"))?;
    if cwd2 != "/cd/sub" {
        return Err(Error::new(ErrorCode::InvalidArgument, "cwd should be /cd/sub"));
    }

    // Change back to root.
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir / failed"))?;

    // Clean up.
    vfs::rmdir("/cd/sub").map_err(|e| fat_err(e, "rmdir /cd/sub failed"))?;
    vfs::unmount("/cd").map_err(|e| fat_err(e, "unmount /cd failed"))?;

    ::syslog::info!("vfs-test: test_chdir_cwd passed");
    Ok(())
}

//==================================================================================================
// Test: Pread and Pwrite
//==================================================================================================

/// Tests positional read/write without changing file position.
fn test_pread_pwrite() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_pread_pwrite begin");

    vfs::create_mount("/pp", 128 * 1024).map_err(|e| fat_err(e, "create_mount /pp failed"))?;

    // Create and write sequential data.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/pp/data.bin")
            .map_err(|e| fat_err(e, "failed to create data.bin"))?;
        file.write(b"AABBCCDDEE")
            .map_err(|e| fat_err(e, "failed to write data.bin"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush data.bin"))?;
    }

    // Open for reading and verify pread at offset.
    {
        let mut file: vfs::File =
            vfs::open("/pp/data.bin").map_err(|e| fat_err(e, "failed to open data.bin"))?;

        // Read at offset 4 (should get "CCDDEE").
        let mut buf: [u8; 6] = [0u8; 6];
        file.seek(0, 4).map_err(|e| fat_err(e, "seek failed"))?;
        let n: usize = file.read(&mut buf).map_err(|e| fat_err(e, "read failed"))?;
        if n != 6 || &buf[..6] != b"CCDDEE" {
            return Err(Error::new(ErrorCode::InvalidArgument, "pread content mismatch"));
        }

        // Verify we can still read from the start.
        file.seek(0, 0)
            .map_err(|e| fat_err(e, "seek back failed"))?;
        let mut buf2: [u8; 2] = [0u8; 2];
        let n2: usize = file
            .read(&mut buf2)
            .map_err(|e| fat_err(e, "read2 failed"))?;
        if n2 != 2 || &buf2 != b"AA" {
            return Err(Error::new(ErrorCode::InvalidArgument, "read from start mismatch"));
        }
    }

    // Clean up.
    vfs::unlink("/pp/data.bin").map_err(|e| fat_err(e, "unlink failed"))?;
    vfs::unmount("/pp").map_err(|e| fat_err(e, "unmount /pp failed"))?;

    ::syslog::info!("vfs-test: test_pread_pwrite passed");
    Ok(())
}

//==================================================================================================
// Test: Ftruncate and Fsync
//==================================================================================================

/// Tests file truncation and sync on the VFS.
fn test_ftruncate_fsync() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_ftruncate_fsync begin");

    vfs::create_mount("/trunc", 128 * 1024)
        .map_err(|e| fat_err(e, "create_mount /trunc failed"))?;

    // Create a file with content.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/trunc/file.txt")
            .map_err(|e| fat_err(e, "failed to create file.txt"))?;
        file.write(b"hello world!")
            .map_err(|e| fat_err(e, "failed to write file.txt"))?;
        file.flush()
            .map_err(|e| fat_err(e, "failed to flush file.txt"))?;
    }

    // Verify initial size.
    let info: vfs::Stat =
        vfs::stat("/trunc/file.txt").map_err(|e| fat_err(e, "stat file.txt failed"))?;
    if info.size() != 12 {
        return Err(Error::new(ErrorCode::InvalidArgument, "initial size should be 12"));
    }

    // Open and truncate to 5 bytes.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .read(true)
            .write(true)
            .open("/trunc/file.txt")
            .map_err(|e| fat_err(e, "failed to open file.txt for truncation"))?;
        file.seek(0, 5)
            .map_err(|e| fat_err(e, "seek to 5 failed"))?;
        file.truncate().map_err(|e| fat_err(e, "truncate failed"))?;
        file.flush()
            .map_err(|e| fat_err(e, "flush after truncate failed"))?;
    }

    // Verify truncated content.
    let info2: vfs::Stat =
        vfs::stat("/trunc/file.txt").map_err(|e| fat_err(e, "stat after truncate"))?;
    if info2.size() != 5 {
        return Err(Error::new(ErrorCode::InvalidArgument, "truncated size should be 5"));
    }
    verify_file("/trunc/file.txt", b"hello")?;

    // Clean up.
    vfs::unlink("/trunc/file.txt").map_err(|e| fat_err(e, "unlink file.txt"))?;
    vfs::unmount("/trunc").map_err(|e| fat_err(e, "unmount /trunc"))?;

    ::syslog::info!("vfs-test: test_ftruncate_fsync passed");
    Ok(())
}

//==================================================================================================
// Test: Open Directory with O_DIRECTORY
//==================================================================================================

/// Tests that `vfs_open()` with `O_DIRECTORY` creates a directory handle.
fn test_open_directory() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_open_directory begin");

    vfs::create_mount("/odir", 128 * 1024).map_err(|e| fat_err(e, "create_mount /odir failed"))?;

    // Create a subdirectory.
    vfs::mkdir("/odir/sub").map_err(|e| fat_err(e, "mkdir /odir/sub failed"))?;

    // Open the subdirectory with O_DIRECTORY.
    let fd: i32 = vfs::fd::vfs_open("/odir/sub", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "vfs_open O_DIRECTORY failed"))?;

    // The returned fd should be a VFS fd.
    if !vfs::fd::is_vfs_fd(fd) {
        return Err(Error::new(ErrorCode::InvalidArgument, "fd should be a VFS fd"));
    }

    // Reading from a directory handle should fail.
    let mut buf: [u8; 4] = [0u8; 4];
    if vfs::fd::vfs_read(fd, &mut buf).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "read on dir fd should fail"));
    }

    // Writing to a directory handle should fail.
    if vfs::fd::vfs_write(fd, &[1, 2]).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "write on dir fd should fail"));
    }

    // Opening a regular file with O_DIRECTORY should fail.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/odir/regular.txt")
            .map_err(|e| fat_err(e, "create regular.txt"))?;
        file.write(b"data")
            .map_err(|e| fat_err(e, "write regular.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush regular.txt"))?;
    }
    if vfs::fd::vfs_open("/odir/regular.txt", file_creation_flags::O_DIRECTORY).is_ok() {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "O_DIRECTORY on regular file should fail",
        ));
    }

    // Close the directory fd.
    vfs::fd::vfs_close(fd).map_err(|e| fat_err(e, "vfs_close dir fd failed"))?;

    // Clean up.
    vfs::unlink("/odir/regular.txt").map_err(|e| fat_err(e, "unlink regular.txt"))?;
    vfs::rmdir("/odir/sub").map_err(|e| fat_err(e, "rmdir /odir/sub failed"))?;
    vfs::unmount("/odir").map_err(|e| fat_err(e, "unmount /odir failed"))?;

    ::syslog::info!("vfs-test: test_open_directory passed");
    Ok(())
}

//==================================================================================================
// Test: Getdents
//==================================================================================================

/// Tests that `vfs_getdents()` returns directory entries as `posix_dent` structs.
fn test_getdents() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_getdents begin");

    vfs::create_mount("/gd", 128 * 1024).map_err(|e| fat_err(e, "create_mount /gd failed"))?;

    // Create a file and a subdirectory.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/gd/file.txt")
            .map_err(|e| fat_err(e, "create file.txt"))?;
        file.write(b"data")
            .map_err(|e| fat_err(e, "write file.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush file.txt"))?;
    }
    vfs::mkdir("/gd/dir1").map_err(|e| fat_err(e, "mkdir /gd/dir1 failed"))?;

    // Open the mount root with O_DIRECTORY.
    let fd: i32 = vfs::fd::vfs_open("/gd", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "vfs_open /gd O_DIRECTORY"))?;

    // Read all entries.
    let dents: alloc::vec::Vec<posix_dent> =
        vfs::fd::vfs_getdents(fd, 64).map_err(|e| fat_err(e, "vfs_getdents failed"))?;

    // Expect 2 entries: file.txt and dir1.
    if dents.len() != 2 {
        return Err(Error::new(ErrorCode::InvalidArgument, "expected 2 dents"));
    }

    // Collect names and verify types.
    let mut found_file: bool = false;
    let mut found_dir: bool = false;
    for dent in &dents {
        let name_end: usize = dent
            .d_name
            .iter()
            .position(|&b| b == 0)
            .unwrap_or(dent.d_name.len());
        let name: &[u8] = &dent.d_name[..name_end];
        if name.eq_ignore_ascii_case(b"file.txt") {
            if dent.d_type != dirent_file_type::DT_REG {
                return Err(Error::new(ErrorCode::InvalidArgument, "file.txt should be DT_REG"));
            }
            found_file = true;
        } else if name.eq_ignore_ascii_case(b"dir1") {
            if dent.d_type != dirent_file_type::DT_DIR {
                return Err(Error::new(ErrorCode::InvalidArgument, "dir1 should be DT_DIR"));
            }
            found_dir = true;
        }
    }
    if !found_file || !found_dir {
        return Err(Error::new(ErrorCode::InvalidArgument, "missing expected dent entries"));
    }

    // A second getdents call should return 0 entries (cursor exhausted).
    let dents2: alloc::vec::Vec<posix_dent> =
        vfs::fd::vfs_getdents(fd, 64).map_err(|e| fat_err(e, "vfs_getdents second call"))?;
    if !dents2.is_empty() {
        return Err(Error::new(ErrorCode::InvalidArgument, "second getdents should be empty"));
    }

    // Calling getdents on a non-directory fd should fail.
    let file_fd: i32 =
        vfs::fd::vfs_open("/gd/file.txt", 0).map_err(|e| fat_err(e, "vfs_open file.txt"))?;
    if vfs::fd::vfs_getdents(file_fd, 64).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "getdents on file fd should fail"));
    }
    vfs::fd::vfs_close(file_fd).map_err(|e| fat_err(e, "close file_fd"))?;

    // Clean up.
    vfs::fd::vfs_close(fd).map_err(|e| fat_err(e, "close dir fd"))?;
    vfs::unlink("/gd/file.txt").map_err(|e| fat_err(e, "unlink file.txt"))?;
    vfs::rmdir("/gd/dir1").map_err(|e| fat_err(e, "rmdir /gd/dir1"))?;
    vfs::unmount("/gd").map_err(|e| fat_err(e, "unmount /gd"))?;

    ::syslog::info!("vfs-test: test_getdents passed");
    Ok(())
}

//==================================================================================================
// Test: Fstat Directory Mode and Timestamps
//==================================================================================================

/// Tests that `vfs_fstat()` returns `S_IFDIR` for directory handles and sets
/// the fixed 2024-01-01 timestamps.
fn test_fstat_directory_and_timestamps() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_fstat_directory_and_timestamps begin");

    vfs::create_mount("/fsd", 128 * 1024).map_err(|e| fat_err(e, "create_mount /fsd failed"))?;

    // Create a file for comparison.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/fsd/test.txt")
            .map_err(|e| fat_err(e, "create test.txt"))?;
        file.write(b"hello")
            .map_err(|e| fat_err(e, "write test.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush test.txt"))?;
    }

    // Open a file fd and fstat it: should be S_IFREG with timestamps.
    let file_fd: i32 =
        vfs::fd::vfs_open("/fsd/test.txt", 0).map_err(|e| fat_err(e, "open file fd"))?;
    let mut st: stat = unsafe { core::mem::zeroed() };
    vfs::fd::vfs_fstat(file_fd, &mut st).map_err(|e| fat_err(e, "fstat file fd"))?;

    if st.st_mode & file_type::S_IFMT != file_type::S_IFREG {
        return Err(Error::new(ErrorCode::InvalidArgument, "file should be S_IFREG"));
    }
    // Verify fixed timestamp.
    if st.st_atim.tv_sec != VFS_FIXED_TIMESTAMP
        || st.st_mtim.tv_sec != VFS_FIXED_TIMESTAMP
        || st.st_ctim.tv_sec != VFS_FIXED_TIMESTAMP
    {
        return Err(Error::new(ErrorCode::InvalidArgument, "file timestamps should be 2024-01-01"));
    }
    vfs::fd::vfs_close(file_fd).map_err(|e| fat_err(e, "close file fd"))?;

    // Open a directory fd and fstat it: should be S_IFDIR with timestamps.
    let dir_fd: i32 = vfs::fd::vfs_open("/fsd", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open dir fd"))?;
    let mut dst: stat = unsafe { core::mem::zeroed() };
    vfs::fd::vfs_fstat(dir_fd, &mut dst).map_err(|e| fat_err(e, "fstat dir fd"))?;

    if dst.st_mode & file_type::S_IFMT != file_type::S_IFDIR {
        return Err(Error::new(ErrorCode::InvalidArgument, "dir should be S_IFDIR"));
    }
    if dst.st_size != 0 {
        return Err(Error::new(ErrorCode::InvalidArgument, "dir size should be 0"));
    }
    if dst.st_atim.tv_sec != VFS_FIXED_TIMESTAMP
        || dst.st_mtim.tv_sec != VFS_FIXED_TIMESTAMP
        || dst.st_ctim.tv_sec != VFS_FIXED_TIMESTAMP
    {
        return Err(Error::new(ErrorCode::InvalidArgument, "dir timestamps should be 2024-01-01"));
    }
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir fd"))?;

    // Clean up.
    vfs::unlink("/fsd/test.txt").map_err(|e| fat_err(e, "unlink test.txt"))?;
    vfs::unmount("/fsd").map_err(|e| fat_err(e, "unmount /fsd"))?;

    ::syslog::info!("vfs-test: test_fstat_directory_and_timestamps passed");
    Ok(())
}

//==================================================================================================
// Test: Stat Timestamps
//==================================================================================================

/// Tests that `vfs_stat()` sets the fixed 2024-01-01 timestamps.
fn test_stat_timestamps() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_stat_timestamps begin");

    vfs::create_mount("/sts", 128 * 1024).map_err(|e| fat_err(e, "create_mount /sts failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/sts/ts.txt")
            .map_err(|e| fat_err(e, "create ts.txt"))?;
        file.write(b"timestamps")
            .map_err(|e| fat_err(e, "write ts.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush ts.txt"))?;
    }

    // Stat the file via path.
    let mut st: stat = unsafe { core::mem::zeroed() };
    vfs::fd::vfs_stat("/sts/ts.txt", &mut st).map_err(|e| fat_err(e, "vfs_stat ts.txt"))?;

    if st.st_atim.tv_sec != VFS_FIXED_TIMESTAMP {
        return Err(Error::new(ErrorCode::InvalidArgument, "stat st_atim should be 2024-01-01"));
    }
    if st.st_mtim.tv_sec != VFS_FIXED_TIMESTAMP {
        return Err(Error::new(ErrorCode::InvalidArgument, "stat st_mtim should be 2024-01-01"));
    }
    if st.st_ctim.tv_sec != VFS_FIXED_TIMESTAMP {
        return Err(Error::new(ErrorCode::InvalidArgument, "stat st_ctim should be 2024-01-01"));
    }

    // Clean up.
    vfs::unlink("/sts/ts.txt").map_err(|e| fat_err(e, "unlink ts.txt"))?;
    vfs::unmount("/sts").map_err(|e| fat_err(e, "unmount /sts"))?;

    ::syslog::info!("vfs-test: test_stat_timestamps passed");
    Ok(())
}

//==================================================================================================
// Test: Fcntl F_GETFD/F_SETFD
//==================================================================================================

/// Tests that `vfs_fcntl()` supports `F_GETFD` and `F_SETFD` commands.
fn test_fcntl_fd_flags() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_fcntl_fd_flags begin");

    vfs::create_mount("/fcn", 128 * 1024).map_err(|e| fat_err(e, "create_mount /fcn failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/fcn/fc.txt")
            .map_err(|e| fat_err(e, "create fc.txt"))?;
        file.write(b"fcntl test")
            .map_err(|e| fat_err(e, "write fc.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush fc.txt"))?;
    }

    let fd: i32 = vfs::fd::vfs_open("/fcn/fc.txt", 0).map_err(|e| fat_err(e, "open fc.txt fd"))?;

    // F_GETFD should succeed and return 0.
    let flags: i32 = vfs::fd::vfs_fcntl(fd, file_control_request::F_GETFD)
        .map_err(|e| fat_err(e, "fcntl F_GETFD"))?;
    if flags != 0 {
        return Err(Error::new(ErrorCode::InvalidArgument, "F_GETFD should return 0"));
    }

    // F_SETFD should succeed and return 0.
    let result: i32 = vfs::fd::vfs_fcntl(fd, file_control_request::F_SETFD)
        .map_err(|e| fat_err(e, "fcntl F_SETFD"))?;
    if result != 0 {
        return Err(Error::new(ErrorCode::InvalidArgument, "F_SETFD should return 0"));
    }

    // F_GETFL and F_SETFL should still work.
    let fl: i32 = vfs::fd::vfs_fcntl(fd, file_control_request::F_GETFL)
        .map_err(|e| fat_err(e, "fcntl F_GETFL"))?;
    if fl != 0 {
        return Err(Error::new(ErrorCode::InvalidArgument, "F_GETFL should return 0"));
    }

    // An unsupported command (e.g. F_DUPFD) should fail.
    if vfs::fd::vfs_fcntl(fd, file_control_request::F_DUPFD).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "F_DUPFD should fail on VFS"));
    }

    vfs::fd::vfs_close(fd).map_err(|e| fat_err(e, "close fc.txt fd"))?;

    // Clean up.
    vfs::unlink("/fcn/fc.txt").map_err(|e| fat_err(e, "unlink fc.txt"))?;
    vfs::unmount("/fcn").map_err(|e| fat_err(e, "unmount /fcn"))?;

    ::syslog::info!("vfs-test: test_fcntl_fd_flags passed");
    Ok(())
}

//==================================================================================================
// Test: Resolve Path with dirfd
//==================================================================================================

/// Tests `vfs_resolve_path()` for absolute paths, AT_FDCWD, and VFS directory fds.
fn test_resolve_path() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_resolve_path begin");

    vfs::create_mount("/rp", 128 * 1024).map_err(|e| fat_err(e, "create_mount /rp failed"))?;
    vfs::mkdir("/rp/sub").map_err(|e| fat_err(e, "mkdir /rp/sub failed"))?;

    // Absolute path: dirfd should be ignored.
    let resolved: alloc::string::String = vfs::fd::vfs_resolve_path(0, "/rp/sub/file.txt")
        .ok_or(Error::new(ErrorCode::InvalidArgument, "absolute resolve failed"))?;
    if resolved != "/rp/sub/file.txt" {
        return Err(Error::new(ErrorCode::InvalidArgument, "absolute path mismatch"));
    }

    // AT_FDCWD: resolve relative to VFS cwd.
    vfs::chdir("/rp").map_err(|e| fat_err(e, "chdir /rp failed"))?;
    let resolved_cwd: alloc::string::String =
        vfs::fd::vfs_resolve_path(::sysapi::fcntl::atflags::AT_FDCWD, "sub")
            .ok_or(Error::new(ErrorCode::InvalidArgument, "AT_FDCWD resolve failed"))?;
    if resolved_cwd != "/rp/sub" {
        return Err(Error::new(ErrorCode::InvalidArgument, "AT_FDCWD path mismatch"));
    }

    // VFS directory fd: resolve relative to directory path.
    let dir_fd: i32 = vfs::fd::vfs_open("/rp/sub", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "vfs_open /rp/sub O_DIRECTORY"))?;
    let resolved_dir: alloc::string::String = vfs::fd::vfs_resolve_path(dir_fd, "nested.txt")
        .ok_or(Error::new(ErrorCode::InvalidArgument, "dirfd resolve failed"))?;
    if resolved_dir != "/rp/sub/nested.txt" {
        return Err(Error::new(ErrorCode::InvalidArgument, "dirfd path mismatch"));
    }

    // Non-VFS fd should return None.
    if vfs::fd::vfs_resolve_path(3, "file.txt").is_some() {
        return Err(Error::new(ErrorCode::InvalidArgument, "non-VFS fd should return None"));
    }

    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir fd"))?;

    // Clean up.
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir / failed"))?;
    vfs::rmdir("/rp/sub").map_err(|e| fat_err(e, "rmdir /rp/sub"))?;
    vfs::unmount("/rp").map_err(|e| fat_err(e, "unmount /rp"))?;

    ::syslog::info!("vfs-test: test_resolve_path passed");
    Ok(())
}

//==================================================================================================
// Test: Chmod
//==================================================================================================

/// Tests that `vfs_chmod()` succeeds on an existing file and fails on a missing one.
fn test_chmod() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_chmod begin");

    vfs::create_mount("/chm", 128 * 1024).map_err(|e| fat_err(e, "create_mount /chm failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/chm/f.txt")
            .map_err(|e| fat_err(e, "create f.txt"))?;
        file.write(b"chmod test")
            .map_err(|e| fat_err(e, "write f.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush f.txt"))?;
    }

    // chmod on an existing file should succeed (FAT32 ignores mode).
    vfs::fd::vfs_chmod("/chm/f.txt", 0o644).map_err(|e| fat_err(e, "chmod existing file"))?;

    // chmod on a non-existent file should fail.
    if vfs::fd::vfs_chmod("/chm/missing.txt", 0o644).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "chmod on missing file should fail"));
    }

    // Clean up.
    vfs::unlink("/chm/f.txt").map_err(|e| fat_err(e, "unlink f.txt"))?;
    vfs::unmount("/chm").map_err(|e| fat_err(e, "unmount /chm"))?;

    ::syslog::info!("vfs-test: test_chmod passed");
    Ok(())
}

//==================================================================================================
// Test: Fchmodat
//==================================================================================================

/// Tests that `vfs_fchmodat()` validates path resolution and file existence.
fn test_fchmodat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_fchmodat begin");

    vfs::create_mount("/fca", 128 * 1024).map_err(|e| fat_err(e, "create_mount /fca failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/fca/f.txt")
            .map_err(|e| fat_err(e, "create f.txt"))?;
        file.write(b"fchmodat test")
            .map_err(|e| fat_err(e, "write f.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush f.txt"))?;
    }

    // fchmodat with absolute path should succeed regardless of dirfd.
    vfs::fd::vfs_fchmodat(0, "/fca/f.txt", 0o755, 0)
        .map_err(|e| fat_err(e, "fchmodat absolute path"))?;

    // fchmodat with AT_FDCWD and relative path.
    vfs::chdir("/fca").map_err(|e| fat_err(e, "chdir /fca"))?;
    let result = vfs::fd::vfs_fchmodat(::sysapi::fcntl::atflags::AT_FDCWD, "f.txt", 0o755, 0);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    result.map_err(|e| fat_err(e, "fchmodat AT_FDCWD relative"))?;

    // fchmodat with a VFS directory fd and relative path.
    let dir_fd: i32 = vfs::fd::vfs_open("/fca", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /fca O_DIRECTORY"))?;
    vfs::fd::vfs_fchmodat(dir_fd, "f.txt", 0o755, 0)
        .map_err(|e| fat_err(e, "fchmodat dirfd relative"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir fd"))?;

    // fchmodat on a non-existent file should fail.
    if vfs::fd::vfs_fchmodat(0, "/fca/missing.txt", 0o755, 0).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "fchmodat on missing file should fail"));
    }

    // Clean up.
    vfs::unlink("/fca/f.txt").map_err(|e| fat_err(e, "unlink f.txt"))?;
    vfs::unmount("/fca").map_err(|e| fat_err(e, "unmount /fca"))?;

    ::syslog::info!("vfs-test: test_fchmodat passed");
    Ok(())
}

//==================================================================================================
// Test: Fchownat
//==================================================================================================

/// Tests that `vfs_fchownat()` validates path resolution and file existence.
fn test_fchownat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_fchownat begin");

    vfs::create_mount("/fco", 128 * 1024).map_err(|e| fat_err(e, "create_mount /fco failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/fco/f.txt")
            .map_err(|e| fat_err(e, "create f.txt"))?;
        file.write(b"fchownat test")
            .map_err(|e| fat_err(e, "write f.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush f.txt"))?;
    }

    // fchownat with absolute path should succeed (FAT32 ignores owner/group).
    vfs::fd::vfs_fchownat(0, "/fco/f.txt", 1000, 1000, 0)
        .map_err(|e| fat_err(e, "fchownat absolute path"))?;

    // fchownat with AT_FDCWD and relative path.
    vfs::chdir("/fco").map_err(|e| fat_err(e, "chdir /fco"))?;
    let result = vfs::fd::vfs_fchownat(::sysapi::fcntl::atflags::AT_FDCWD, "f.txt", 0, 0, 0);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    result.map_err(|e| fat_err(e, "fchownat AT_FDCWD relative"))?;

    // fchownat with a VFS directory fd and relative path.
    let dir_fd: i32 = vfs::fd::vfs_open("/fco", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /fco O_DIRECTORY"))?;
    vfs::fd::vfs_fchownat(dir_fd, "f.txt", 0, 0, 0)
        .map_err(|e| fat_err(e, "fchownat dirfd relative"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir fd"))?;

    // fchownat on a non-existent file should fail.
    if vfs::fd::vfs_fchownat(0, "/fco/missing.txt", 0, 0, 0).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "fchownat on missing file should fail"));
    }

    // Clean up.
    vfs::unlink("/fco/f.txt").map_err(|e| fat_err(e, "unlink f.txt"))?;
    vfs::unmount("/fco").map_err(|e| fat_err(e, "unmount /fco"))?;

    ::syslog::info!("vfs-test: test_fchownat passed");
    Ok(())
}

//==================================================================================================
// Test: Utimensat
//==================================================================================================

/// Tests that `vfs_utimensat()` validates path resolution and file existence.
fn test_utimensat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_utimensat begin");

    vfs::create_mount("/uts", 128 * 1024).map_err(|e| fat_err(e, "create_mount /uts failed"))?;

    // Create a file.
    {
        let mut file: vfs::File = vfs::OpenOptions::new()
            .write(true)
            .create(true)
            .open("/uts/f.txt")
            .map_err(|e| fat_err(e, "create f.txt"))?;
        file.write(b"utimensat test")
            .map_err(|e| fat_err(e, "write f.txt"))?;
        file.flush().map_err(|e| fat_err(e, "flush f.txt"))?;
    }

    let times: [timespec; 2] = [
        timespec {
            tv_sec: 1_000_000,
            tv_nsec: 0,
        },
        timespec {
            tv_sec: 2_000_000,
            tv_nsec: 0,
        },
    ];

    // utimensat with absolute path should succeed (FAT32 ignores times).
    vfs::fd::vfs_utimensat(0, "/uts/f.txt", &times, 0)
        .map_err(|e| fat_err(e, "utimensat absolute path"))?;

    // utimensat with AT_FDCWD and relative path.
    vfs::chdir("/uts").map_err(|e| fat_err(e, "chdir /uts"))?;
    let result = vfs::fd::vfs_utimensat(::sysapi::fcntl::atflags::AT_FDCWD, "f.txt", &times, 0);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    result.map_err(|e| fat_err(e, "utimensat AT_FDCWD relative"))?;

    // utimensat with a VFS directory fd and relative path.
    let dir_fd: i32 = vfs::fd::vfs_open("/uts", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /uts O_DIRECTORY"))?;
    vfs::fd::vfs_utimensat(dir_fd, "f.txt", &times, 0)
        .map_err(|e| fat_err(e, "utimensat dirfd relative"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir fd"))?;

    // utimensat on a non-existent file should fail.
    if vfs::fd::vfs_utimensat(0, "/uts/missing.txt", &times, 0).is_ok() {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "utimensat on missing file should fail",
        ));
    }

    // Clean up.
    vfs::unlink("/uts/f.txt").map_err(|e| fat_err(e, "unlink f.txt"))?;
    vfs::unmount("/uts").map_err(|e| fat_err(e, "unmount /uts"))?;

    ::syslog::info!("vfs-test: test_utimensat passed");
    Ok(())
}

//==================================================================================================
// Test: Openat
//==================================================================================================

/// Tests that `vfs_openat()` resolves paths relative to a directory file
/// descriptor and refuses to silently fall back to the cwd when the `dirfd`
/// cannot be resolved.
fn test_openat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_openat begin");

    vfs::create_mount("/oat", 128 * 1024).map_err(|e| fat_err(e, "create_mount /oat failed"))?;
    vfs::mkdir("/oat/sub").map_err(|e| fat_err(e, "mkdir /oat/sub"))?;

    // File inside the subdirectory (the dirfd target).
    create_file("/oat/sub/inside.txt", b"inside")?;
    // Decoy file in the mount root (the cwd target).
    create_file("/oat/decoy.txt", b"decoy")?;

    // openat with an absolute path ignores dirfd.
    let fd_abs: i32 = vfs::fd::vfs_openat(0, "/oat/sub/inside.txt", 0)
        .map_err(|e| fat_err(e, "openat absolute path"))?;
    vfs::fd::vfs_close(fd_abs).map_err(|e| fat_err(e, "close fd_abs"))?;

    // openat with AT_FDCWD resolves against the cwd.
    vfs::chdir("/oat/sub").map_err(|e| fat_err(e, "chdir /oat/sub"))?;
    let cwd_result = vfs::fd::vfs_openat(::sysapi::fcntl::atflags::AT_FDCWD, "inside.txt", 0);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    let fd_cwd: i32 = cwd_result.map_err(|e| fat_err(e, "openat AT_FDCWD relative"))?;
    vfs::fd::vfs_close(fd_cwd).map_err(|e| fat_err(e, "close fd_cwd"))?;

    // openat with a directory fd resolves the relative path against that directory.
    let dir_fd: i32 = vfs::fd::vfs_open("/oat/sub", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /oat/sub O_DIRECTORY"))?;
    let fd_rel: i32 =
        vfs::fd::vfs_openat(dir_fd, "inside.txt", 0).map_err(|e| fat_err(e, "openat dirfd rel"))?;
    vfs::fd::vfs_close(fd_rel).map_err(|e| fat_err(e, "close fd_rel"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir_fd"))?;

    // Bug guard: a non-directory fd must not be usable as a dirfd. With the
    // dirfd silently dropped, "decoy.txt" would wrongly resolve against the
    // cwd (/oat) and open successfully.
    let file_fd: i32 =
        vfs::fd::vfs_open("/oat/decoy.txt", 0).map_err(|e| fat_err(e, "open decoy.txt"))?;
    vfs::chdir("/oat").map_err(|e| fat_err(e, "chdir /oat"))?;
    let bug = vfs::fd::vfs_openat(file_fd, "decoy.txt", 0);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    vfs::fd::vfs_close(file_fd).map_err(|e| fat_err(e, "close file_fd"))?;
    match bug {
        Ok(stray) => {
            let _ = vfs::fd::vfs_close(stray);
            return Err(Error::new(
                ErrorCode::InvalidArgument,
                "openat with a non-directory dirfd must fail instead of resolving against the cwd",
            ));
        },
        Err(vfs::Fat32Error::InvalidArgument) => {},
        Err(e) => {
            return Err(fat_err(
                e,
                "openat with a non-directory dirfd must fail with EINVAL, not another error",
            ));
        },
    }

    // Clean up.
    vfs::unlink("/oat/sub/inside.txt").map_err(|e| fat_err(e, "unlink inside.txt"))?;
    vfs::unlink("/oat/decoy.txt").map_err(|e| fat_err(e, "unlink decoy.txt"))?;
    vfs::rmdir("/oat/sub").map_err(|e| fat_err(e, "rmdir /oat/sub"))?;
    vfs::unmount("/oat").map_err(|e| fat_err(e, "unmount /oat"))?;

    ::syslog::info!("vfs-test: test_openat passed");
    Ok(())
}

//==================================================================================================
// Test: Mkdirat
//==================================================================================================

/// Tests that `vfs_mkdirat()` creates directories relative to a directory file
/// descriptor and refuses to silently fall back to the cwd when the `dirfd`
/// cannot be resolved.
fn test_mkdirat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_mkdirat begin");

    vfs::create_mount("/mat", 128 * 1024).map_err(|e| fat_err(e, "create_mount /mat failed"))?;
    vfs::mkdir("/mat/sub").map_err(|e| fat_err(e, "mkdir /mat/sub"))?;
    create_file("/mat/decoy.txt", b"decoy")?;

    // mkdirat with an absolute path ignores dirfd.
    vfs::fd::vfs_mkdirat(0, "/mat/abs").map_err(|e| fat_err(e, "mkdirat absolute path"))?;
    if !path_exists("/mat/abs") {
        return Err(Error::new(ErrorCode::InvalidArgument, "mkdirat absolute: dir not created"));
    }

    // mkdirat with AT_FDCWD resolves against the cwd.
    vfs::chdir("/mat").map_err(|e| fat_err(e, "chdir /mat"))?;
    let cwd_result = vfs::fd::vfs_mkdirat(::sysapi::fcntl::atflags::AT_FDCWD, "cwd_dir");
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    cwd_result.map_err(|e| fat_err(e, "mkdirat AT_FDCWD relative"))?;
    if !path_exists("/mat/cwd_dir") {
        return Err(Error::new(ErrorCode::InvalidArgument, "mkdirat AT_FDCWD: dir not in cwd"));
    }

    // mkdirat with a directory fd resolves the relative path against that directory.
    let dir_fd: i32 = vfs::fd::vfs_open("/mat/sub", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /mat/sub O_DIRECTORY"))?;
    vfs::fd::vfs_mkdirat(dir_fd, "made").map_err(|e| fat_err(e, "mkdirat dirfd relative"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir_fd"))?;
    if !path_exists("/mat/sub/made") {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "mkdirat dirfd: directory created in the wrong place",
        ));
    }

    // Bug guard: a non-directory fd must not silently fall back to the cwd.
    let file_fd: i32 =
        vfs::fd::vfs_open("/mat/decoy.txt", 0).map_err(|e| fat_err(e, "open decoy.txt"))?;
    vfs::chdir("/mat").map_err(|e| fat_err(e, "chdir /mat"))?;
    let bug = vfs::fd::vfs_mkdirat(file_fd, "stray");
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    vfs::fd::vfs_close(file_fd).map_err(|e| fat_err(e, "close file_fd"))?;
    match bug {
        Ok(()) => {
            return Err(Error::new(
                ErrorCode::InvalidArgument,
                "mkdirat with a non-directory dirfd must fail instead of resolving against the cwd",
            ));
        },
        Err(vfs::Fat32Error::InvalidArgument) => {},
        Err(e) => {
            return Err(fat_err(
                e,
                "mkdirat with a non-directory dirfd must fail with EINVAL, not another error",
            ));
        },
    }
    if path_exists("/mat/stray") {
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "mkdirat with a non-directory dirfd must not create a directory in the cwd",
        ));
    }

    // Clean up.
    vfs::rmdir("/mat/sub/made").map_err(|e| fat_err(e, "rmdir made"))?;
    vfs::rmdir("/mat/sub").map_err(|e| fat_err(e, "rmdir /mat/sub"))?;
    vfs::rmdir("/mat/abs").map_err(|e| fat_err(e, "rmdir abs"))?;
    vfs::rmdir("/mat/cwd_dir").map_err(|e| fat_err(e, "rmdir cwd_dir"))?;
    vfs::unlink("/mat/decoy.txt").map_err(|e| fat_err(e, "unlink decoy.txt"))?;
    vfs::unmount("/mat").map_err(|e| fat_err(e, "unmount /mat"))?;

    ::syslog::info!("vfs-test: test_mkdirat passed");
    Ok(())
}

//==================================================================================================
// Test: Accessat
//==================================================================================================

/// Tests that `vfs_accessat()` resolves paths relative to a directory file
/// descriptor and refuses to silently fall back to the cwd when the `dirfd`
/// cannot be resolved.
fn test_accessat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_accessat begin");

    vfs::create_mount("/aat", 128 * 1024).map_err(|e| fat_err(e, "create_mount /aat failed"))?;
    vfs::mkdir("/aat/sub").map_err(|e| fat_err(e, "mkdir /aat/sub"))?;
    create_file("/aat/sub/inside.txt", b"inside")?;
    create_file("/aat/decoy.txt", b"decoy")?;

    // accessat with an absolute path ignores dirfd.
    vfs::fd::vfs_accessat(0, "/aat/sub/inside.txt")
        .map_err(|e| fat_err(e, "accessat absolute path"))?;

    // accessat with AT_FDCWD resolves against the cwd.
    vfs::chdir("/aat/sub").map_err(|e| fat_err(e, "chdir /aat/sub"))?;
    let cwd_result = vfs::fd::vfs_accessat(::sysapi::fcntl::atflags::AT_FDCWD, "inside.txt");
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    cwd_result.map_err(|e| fat_err(e, "accessat AT_FDCWD relative"))?;

    // accessat with a directory fd resolves the relative path against that directory.
    let dir_fd: i32 = vfs::fd::vfs_open("/aat/sub", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /aat/sub O_DIRECTORY"))?;
    vfs::fd::vfs_accessat(dir_fd, "inside.txt").map_err(|e| fat_err(e, "accessat dirfd rel"))?;

    // A relative path that only exists in the cwd must NOT be found via the
    // directory fd (decoy.txt lives in /aat, not in /aat/sub).
    vfs::chdir("/aat").map_err(|e| fat_err(e, "chdir /aat"))?;
    let cross = vfs::fd::vfs_accessat(dir_fd, "decoy.txt");
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    if cross.is_ok() {
        let _ = vfs::fd::vfs_close(dir_fd);
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "accessat resolved against the cwd instead of the directory fd",
        ));
    }

    // Bug guard: a non-directory fd must not silently fall back to the cwd.
    let file_fd: i32 =
        vfs::fd::vfs_open("/aat/decoy.txt", 0).map_err(|e| fat_err(e, "open decoy.txt"))?;
    vfs::chdir("/aat").map_err(|e| fat_err(e, "chdir /aat"))?;
    let bug = vfs::fd::vfs_accessat(file_fd, "decoy.txt");
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    vfs::fd::vfs_close(file_fd).map_err(|e| fat_err(e, "close file_fd"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir_fd"))?;
    match bug {
        Ok(()) => {
            return Err(Error::new(
                ErrorCode::InvalidArgument,
                "accessat with a non-directory dirfd must fail instead of resolving against the \
                 cwd",
            ));
        },
        Err(vfs::Fat32Error::InvalidArgument) => {},
        Err(e) => {
            return Err(fat_err(
                e,
                "accessat with a non-directory dirfd must fail with EINVAL, not another error",
            ));
        },
    }

    // accessat on a non-existent file fails.
    if vfs::fd::vfs_accessat(0, "/aat/missing.txt").is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "accessat on missing file should fail"));
    }

    // Clean up.
    vfs::unlink("/aat/sub/inside.txt").map_err(|e| fat_err(e, "unlink inside.txt"))?;
    vfs::unlink("/aat/decoy.txt").map_err(|e| fat_err(e, "unlink decoy.txt"))?;
    vfs::rmdir("/aat/sub").map_err(|e| fat_err(e, "rmdir /aat/sub"))?;
    vfs::unmount("/aat").map_err(|e| fat_err(e, "unmount /aat"))?;

    ::syslog::info!("vfs-test: test_accessat passed");
    Ok(())
}

//==================================================================================================
// Test: Fstatat
//==================================================================================================

/// Tests that `vfs_fstatat()` resolves paths relative to a directory file
/// descriptor and refuses to silently fall back to the cwd when the `dirfd`
/// cannot be resolved.
fn test_fstatat() -> Result<(), Error> {
    ::syslog::info!("vfs-test: test_fstatat begin");

    vfs::create_mount("/sat", 128 * 1024).map_err(|e| fat_err(e, "create_mount /sat failed"))?;
    vfs::mkdir("/sat/sub").map_err(|e| fat_err(e, "mkdir /sat/sub"))?;
    create_file("/sat/sub/inside.txt", b"inside")?;
    create_file("/sat/decoy.txt", b"decoy")?;

    // fstatat with an absolute path ignores dirfd and reports a regular file.
    let mut st: stat = unsafe { core::mem::zeroed() };
    vfs::fd::vfs_fstatat(0, "/sat/sub/inside.txt", &mut st)
        .map_err(|e| fat_err(e, "fstatat absolute path"))?;
    if st.st_mode & file_type::S_IFMT != file_type::S_IFREG {
        return Err(Error::new(ErrorCode::InvalidArgument, "fstatat absolute: not a regular file"));
    }

    // fstatat with AT_FDCWD resolves against the cwd.
    vfs::chdir("/sat/sub").map_err(|e| fat_err(e, "chdir /sat/sub"))?;
    let mut cwd_st: stat = unsafe { core::mem::zeroed() };
    let cwd_result =
        vfs::fd::vfs_fstatat(::sysapi::fcntl::atflags::AT_FDCWD, "inside.txt", &mut cwd_st);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    cwd_result.map_err(|e| fat_err(e, "fstatat AT_FDCWD relative"))?;

    // fstatat with a directory fd resolves the relative path against that directory.
    let dir_fd: i32 = vfs::fd::vfs_open("/sat/sub", file_creation_flags::O_DIRECTORY)
        .map_err(|e| fat_err(e, "open /sat/sub O_DIRECTORY"))?;
    let mut rel_st: stat = unsafe { core::mem::zeroed() };
    vfs::fd::vfs_fstatat(dir_fd, "inside.txt", &mut rel_st)
        .map_err(|e| fat_err(e, "fstatat dirfd rel"))?;

    // A relative path that only exists in the cwd must NOT be found via the
    // directory fd (decoy.txt lives in /sat, not in /sat/sub).
    vfs::chdir("/sat").map_err(|e| fat_err(e, "chdir /sat"))?;
    let mut cross_st: stat = unsafe { core::mem::zeroed() };
    let cross = vfs::fd::vfs_fstatat(dir_fd, "decoy.txt", &mut cross_st);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    if cross.is_ok() {
        let _ = vfs::fd::vfs_close(dir_fd);
        return Err(Error::new(
            ErrorCode::InvalidArgument,
            "fstatat resolved against the cwd instead of the directory fd",
        ));
    }

    // Bug guard: a non-directory fd must not silently fall back to the cwd.
    let file_fd: i32 =
        vfs::fd::vfs_open("/sat/decoy.txt", 0).map_err(|e| fat_err(e, "open decoy.txt"))?;
    vfs::chdir("/sat").map_err(|e| fat_err(e, "chdir /sat"))?;
    let mut bug_st: stat = unsafe { core::mem::zeroed() };
    let bug = vfs::fd::vfs_fstatat(file_fd, "decoy.txt", &mut bug_st);
    vfs::chdir("/").map_err(|e| fat_err(e, "chdir /"))?;
    vfs::fd::vfs_close(file_fd).map_err(|e| fat_err(e, "close file_fd"))?;
    vfs::fd::vfs_close(dir_fd).map_err(|e| fat_err(e, "close dir_fd"))?;
    match bug {
        Ok(()) => {
            return Err(Error::new(
                ErrorCode::InvalidArgument,
                "fstatat with a non-directory dirfd must fail instead of resolving against the cwd",
            ));
        },
        Err(vfs::Fat32Error::InvalidArgument) => {},
        Err(e) => {
            return Err(fat_err(
                e,
                "fstatat with a non-directory dirfd must fail with EINVAL, not another error",
            ));
        },
    }

    // fstatat on a non-existent file fails.
    let mut missing_st: stat = unsafe { core::mem::zeroed() };
    if vfs::fd::vfs_fstatat(0, "/sat/missing.txt", &mut missing_st).is_ok() {
        return Err(Error::new(ErrorCode::InvalidArgument, "fstatat on missing file should fail"));
    }

    // Clean up.
    vfs::unlink("/sat/sub/inside.txt").map_err(|e| fat_err(e, "unlink inside.txt"))?;
    vfs::unlink("/sat/decoy.txt").map_err(|e| fat_err(e, "unlink decoy.txt"))?;
    vfs::rmdir("/sat/sub").map_err(|e| fat_err(e, "rmdir /sat/sub"))?;
    vfs::unmount("/sat").map_err(|e| fat_err(e, "unmount /sat"))?;

    ::syslog::info!("vfs-test: test_fstatat passed");
    Ok(())
}

//==================================================================================================
// Helpers
//==================================================================================================

/// Creates a file with the given `contents`, truncating any existing file.
fn create_file(path: &str, contents: &[u8]) -> Result<(), Error> {
    let mut file: vfs::File = vfs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)
        .map_err(|e| fat_err(e, "failed to create file"))?;
    let mut written: usize = 0;
    while written < contents.len() {
        let n: usize = file
            .write(&contents[written..])
            .map_err(|e| fat_err(e, "failed to write file"))?;
        if n == 0 {
            return Err(Error::new(ErrorCode::NoSpaceOnDevice, "short write while creating file"));
        }
        written += n;
    }
    file.flush()
        .map_err(|e| fat_err(e, "failed to flush file"))?;
    Ok(())
}

/// Returns `true` if a path exists in the VFS.
fn path_exists(path: &str) -> bool {
    let mut st: stat = unsafe { core::mem::zeroed() };
    vfs::fd::vfs_stat(path, &mut st).is_ok()
}

/// Opens a file and verifies its contents match `expected`.
fn verify_file(path: &str, expected: &[u8]) -> Result<(), Error> {
    let mut file: vfs::File = vfs::open(path).map_err(|e| fat_err(e, "failed to open file"))?;
    let content: alloc::vec::Vec<u8> = file
        .read_to_vec()
        .map_err(|e| fat_err(e, "failed to read file"))?;
    if content.as_slice() != expected {
        return Err(Error::new(ErrorCode::InvalidArgument, "file content mismatch"));
    }
    Ok(())
}
