# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "syslog"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "System Logging Library"
homepage.workspace = true

[dependencies]
cfg-if = { workspace = true }
sys = { workspace = true, features = ["kcall"] }

[features]
default = []

# Logging Features
trace = ["debug"]
debug = ["info"]
info = ["warn"]
warn = ["error"]
error = ["panic"]
panic = []
