# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "memd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Memory Management Daemon"
homepage.workspace = true

[[bin]]
name = "memd"

[dependencies]
nvx = { workspace = true }
proc = { workspace = true, features = ["syscall"] }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }
