# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "memd"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Memory Management Daemon"
homepage.workspace = true

[[bin]]
name = "memd"

[dependencies]
sys = { workspace = true }
nvx = { workspace = true }
proc = { workspace = true, features = ["syscall"] }
syslog = { workspace = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
trace = ["nvx/trace", "syslog/trace"]
debug = ["nvx/debug", "syslog/debug"]
info = ["nvx/info", "syslog/info"]
warn = ["nvx/warn", "syslog/warn"]
error = ["nvx/error", "syslog/error"]
panic = ["nvx/panic", "syslog/panic"]
