# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "matmul"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "A Cache-Oblivious Matrix Multiplication CPU-Bound Benchmark"
homepage.workspace = true

[[bin]]
name = "matmul"

[dependencies]
fastrand.workspace = true
micromath.workspace = true
nvx = { workspace = true, features = ["allocator"] }
posix = { workspace = true, features = ["syscall", "allocator"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json.workspace = true

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
trace = ["nvx/trace"]
debug = ["nvx/debug"]
info = ["nvx/info"]
warn = ["nvx/warn"]
error = ["nvx/error"]
panic = ["nvx/panic"]
