# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "posix"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "POSIX Library"
homepage.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
nvx = { workspace = true }
cfg-if = { workspace = true }
num_enum = { workspace = true }
spin = { workspace = true, features = ["lazy", "spin_mutex"] }
syscall = { workspace = true, features = [
    "syscall",
    "dlfcn",
    "pthread",
    "sbrk",
] }
static_assert = { workspace = true }
sysalloc = { workspace = true, optional = true }
syslog = { workspace = true }
type-safe = { workspace = true }

[features]
default = ["syscall", "allocator", "staticlib"]
allocator = ["dep:sysalloc", "nvx/allocator", "syscall/allocator"]
syscall = []
std = ["nvx/std"]
staticlib = ["nvx/staticlib", "sysalloc/staticlib", "syscall/staticlib"]

# Logging
trace = ["nvx/trace", "syslog/trace"]
debug = ["nvx/debug", "syslog/debug"]
info = ["nvx/info", "syslog/info"]
warn = ["nvx/warn", "syslog/warn"]
error = ["nvx/error", "syslog/error"]
panic = ["nvx/panic", "syslog/panic"]
