.\"
.\" Copyright (C) 2011-2013 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH signals 6 "August 2013" "System Calls" "The Nanvix Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
signals \- Asynchronous inter-process communication. 
.\"
.\"=============================================================================
.\"
.\"
.SH "DESCRIPTION"
.\"
Signals are a form of inter-process communication used to notify a process about
the occurrence of an asynchronous event.

Process may send signals to each other
through the
.BR kill()
system call and control the disposition of signals through the
.BR signal()
system call.

Nanvix supports all signals defined at
.IR <signal.h> ,
which are:

.TS
l l l l
____
l lB l l.
Num	Signal	Action	Comment
0	SIGNULL	ign	null signal (cannot be caught)
1	SIGKILL	term	kill (cannot be caught or ignored)
2	SIGSTOP	stop	stop executing (cannot be caught or ignored)
3	SIGURG	ign	high bandwidth data is available at a socket
4	SIGABRT	abrt	process abort signal
5	SIGBUS	abrt	access to an undefined portion of a memory
6	SIGCHLD	ign	child process terminated or stopped
7	SIGCONT	cont	continue executing, if stopped
8	SIGFPE	term	erroneous arithmetic operation
9	SIGHUP	term	hangup
10	SIGILL	abrt	illegal instruction
11	SIGINT	term	terminal interrupt signal
12	SIGPIPE	abrt	write on a pipe with no one to read it
13	SIGQUIT	abrt	terminal quit signal
14	SIGSEGV	abrt	invalid memory reference
15	SIGTERM	term	termination signal
16	SIGTSTP	stop	terminal stop signal
17	SIGTTIN	stop	background process attempting read
18	SIGTTOU	stop	background process attempting write
19	SIGALRM	term	alarm clock
20	SIGUSR1	term	user-defined signal 1
21	SIGUSR2	term	user-defined signal 2
22	SIGTRAP	abrt	trace/breakpoint trap
.TE
.\"
.\"=============================================================================
.\"
.SH "CONFORMING TO"
.\"
POSIX.1-2001
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.SH "SEE ALSO"
.\"
.BR kill(2) ,
.BR signal2)

