# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

all: all-loader

clean: clean-loader

clippy: clippy-loader

all-loader:
	$(MAKE) -C loader

clean-loader:
	$(MAKE) -C loader clean

clippy-loader:
	$(MAKE) -C loader clippy
