// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//!
//! # Asynchronous Signal Delivery
//!
//! Glue between the process manager and the architecture-neutral [`sigframe`] logic. At the
//! return-to-user boundary the kernel checks the running process for a deliverable caught signal
//! and, if one is found, redirects the interrupted thread through its user-space handler by:
//!
//! 1. reading the interrupted user context off the top of the thread's kernel stack (the hardware
//!    trap frame plus the callee-saved registers preserved by the kernel-call entry stub),
//! 2. building a signal frame on the thread's user stack that saves that context, the FPU state,
//!    and the blocked mask, and
//! 3. rewriting the trap frame so the kernel-call return path resumes in the handler.
//!
//! `sigreturn()` reverses the process: it validates the on-stack frame, restores the saved context,
//! FPU state, and mask, and resumes the interrupted instruction stream.
//!
//! [`sigframe`]: crate::pm::process::state::sigframe
//!

//==================================================================================================
// Imports
//==================================================================================================

use super::{
    r#unsafe::FPU_OWNER_TID,
    ProcessManager,
};
use crate::{
    hal::{
        arch::{
            capture_fpu,
            install_fpu,
            join_kcall_result,
            prepare_kcall_restart,
            read_trap_context,
            read_user_sp,
            redirect_to_handler,
            restore_trap_context,
            returning_to_user,
        },
        mem::Address,
    },
    mm::Vmem,
    pm::{
        process::state::{
            sigframe::{
                self,
                build_frame,
                frame_layout,
                next_blocked,
                save_area_offset_from_sigreturn_sp,
                validate_and_restore,
                FrameLayout,
                SigFrame,
                SignalCpuContext,
                FPU_AREA_SIZE,
            },
            signal::{
                SignalDisposition,
                UNBLOCKABLE,
            },
        },
        KcallRestart,
        ORDER,
    },
};
use ::sys::{
    error::Error,
    mm::VirtualAddress,
    pm::{
        ProcessIdentifier,
        ThreadIdentifier,
        SA_NODEFER,
        SA_RESETHAND,
        SA_RESTART,
        SA_SIGINFO,
        SIG_MAX,
    },
};

//==================================================================================================
// Structures
//==================================================================================================

///
/// # Description
///
/// Outcome of evaluating signal delivery at a return-to-user checkpoint.
///
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SignalDeliveryOutcome {
    /// No deliverable signal was pending; the thread resumes normally.
    None,
    /// A signal frame was built and the thread was redirected to its handler.
    Delivered,
    /// A frame could not be built safely; the caller must take the signal's default action and
    /// terminate the process.
    Escalate,
}

///
/// # Description
///
/// Outcome of evaluating a synchronous signal generated by a CPU exception on the faulting thread.
///
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SyncSignalOutcome {
    /// A signal frame was built; the caller must redirect the faulting context to `entry` with the
    /// stack pointer set to `frame_top`.
    Delivered {
        /// Address of the user-space signal handler to enter.
        entry: usize,
        /// Stack pointer the handler is entered with (top of the signal frame).
        frame_top: usize,
        /// Address of the registered user-space signal-return trampoline.
        restorer: usize,
        /// User address of the embedded `siginfo` image for an `SA_SIGINFO` handler (the handler's
        /// second argument), or `0` when the handler is not `SA_SIGINFO`. Consumed by the caller to
        /// populate the handler's argument register on register-argument ABIs (x86-64); ignored on
        /// stack-argument ABIs (x86), where it is already written to the frame.
        info_ptr: usize,
        /// User address of the embedded context image for an `SA_SIGINFO` handler (the handler's
        /// third argument), or `0` when the handler is not `SA_SIGINFO`. Consumed as for `info_ptr`.
        ctx_ptr: usize,
    },
    /// No catchable handler ran; the caller must take the signal's default action and terminate the
    /// process.
    Terminate,
}

///
/// # Description
///
/// Reason a `sigreturn()` request failed.
///
// `Unsupported` is returned only on architectures without a delivery path (whose trap-frame
// accessors are inert placeholders); `Forged` only where a real frame is built and then fails
// validation. The `sigreturn()` handler matches both.
#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SigReturnFailure {
    /// The on-stack frame was corrupt or forged; the process must be terminated.
    Forged,
    /// `sigreturn()` is not implemented on this architecture.
    Unsupported,
}

//==================================================================================================
// Implementations
//==================================================================================================

impl ProcessManager {
    ///
    /// # Description
    ///
    /// Records the user-space signal-return trampoline (restorer) for a process.
    ///
    /// # Parameters
    ///
    /// - `pid`: Identifier of the process.
    /// - `restorer`: Address of the restorer trampoline in the process's address space.
    ///
    /// # Returns
    ///
    /// Upon success, empty is returned. Upon failure, an error is returned instead.
    ///
    pub fn set_signal_restorer(
        &mut self,
        pid: ProcessIdentifier,
        restorer: VirtualAddress,
    ) -> Result<(), Error> {
        self.find_process_mut(pid)?
            .state_mut()
            .signals_mut()
            .set_restorer(Some(restorer));
        Ok(())
    }

    ///
    /// # Description
    ///
    /// Records, on the running thread, a blocking kernel call that a deliverable caught signal just
    /// interrupted. The asynchronous-delivery checkpoint consumes this record to transparently
    /// restart the call when the interrupting handler is installed with `SA_RESTART`.
    ///
    /// # Parameters
    ///
    /// - `restart`: The interrupted call's number and arguments.
    ///
    pub fn set_running_thread_restart(&mut self, restart: KcallRestart) {
        let tid: ThreadIdentifier = self.get_tid();
        if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
            thread.thread_state_mut().set_restart(restart);
        }
    }

    ///
    /// # Description
    ///
    /// Evaluates and, if warranted, performs delivery of a pending caught signal to the running
    /// thread at the kernel-call return-to-user boundary.
    ///
    /// # Parameters
    ///
    /// - `result`: The return value the interrupted kernel call will deliver to user space (saved
    ///   as the interrupted accumulator so it survives the handler).
    ///
    /// # Returns
    ///
    /// A [`SignalDeliveryOutcome`] describing what happened.
    ///
    pub fn try_deliver_signal(&mut self, result: i64) -> SignalDeliveryOutcome {
        let pid: ProcessIdentifier = self.get_pid();
        let tid: ThreadIdentifier = self.get_tid();

        // Locate the running thread's kernel stack and read its blocked and pending sets.
        let owner_tid: ThreadIdentifier = ThreadIdentifier::from(FPU_OWNER_TID.load(ORDER));
        let (esp0, blocked, thread_pending, restart): (usize, u64, u64, Option<KcallRestart>) = {
            let mut thread = match self.get_running_mut().find_thread_mut(tid) {
                Some(thread) => thread,
                None => return SignalDeliveryOutcome::None,
            };
            let state = thread.thread_state_mut();
            // Consume any restart record now so it never lingers past this kernel-call boundary,
            // even if no signal turns out to be deliverable below.
            let restart: Option<KcallRestart> = state.take_restart();
            let blocked: u64 = state.blocked();
            let thread_pending: u64 = state.pending();
            match state.kernel_stack_top() {
                Some(esp0) => (esp0.into_raw_value(), blocked, thread_pending, restart),
                None => return SignalDeliveryOutcome::None,
            }
        };

        // Deliver only when the kernel-call return resumes in user mode.
        if !unsafe { returning_to_user(esp0) } {
            return SignalDeliveryOutcome::None;
        }

        // Select the lowest-numbered deliverable, caught signal and capture its handler. The
        // deliverable set unions the process-directed pending set with the faulting thread's
        // thread-directed pending set (synchronous faults target the thread). Pending signals whose
        // disposition is not a handler (e.g. job-control stop/continue that `kill()` records for a
        // later phase) are left pending and skipped, so they are neither discarded nor allowed to
        // mask a higher-numbered caught signal in the same set.
        let (signum, entry, sa_mask, sa_flags): (usize, usize, u64, i32) = {
            let signals = self.get_running_mut().state_mut().signals_mut();
            let mut deliverable: u64 = (signals.pending() | thread_pending) & !blocked;
            loop {
                if deliverable == 0 {
                    return SignalDeliveryOutcome::None;
                }
                let signum: usize = (deliverable.trailing_zeros() as usize) + 1;
                if let Some(SignalDisposition::Handler(handler)) = signals.disposition(signum) {
                    break (signum, handler.entry.into_raw_value(), handler.mask, handler.flags);
                }
                // Not a caught signal: leave it pending for its own phase and consider the next.
                deliverable &= deliverable - 1;
            }
        };

        // The handler return address must be a registered restorer trampoline.
        let restorer: usize = match self.get_running_mut().state_mut().signals_mut().restorer() {
            Some(restorer) => restorer.into_raw_value(),
            None => {
                error!("no signal restorer registered (pid={pid:?}, signum={signum})");
                self.get_running_mut()
                    .state_mut()
                    .signals_mut()
                    .clear_pending(signum);
                if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
                    thread.thread_state_mut().clear_pending(signum);
                }
                return SignalDeliveryOutcome::None;
            },
        };

        // Snapshot the interrupted CPU context and place the frame on the user stack.
        let mut cpu: SignalCpuContext = unsafe { read_trap_context(esp0, result) };

        // If a blocking call was interrupted by this signal and the handler that is about to run is
        // installed with SA_RESTART, rewind the saved context to the kernel-call trap and reload the
        // original argument registers, so the call transparently re-executes after the handler
        // returns. Without SA_RESTART the recorded EINTR result (already in the saved accumulator)
        // stands and the record is simply discarded.
        if let Some(restart) = restart {
            if (sa_flags & SA_RESTART) != 0 {
                prepare_kcall_restart(&mut cpu, restart.number, restart.args);
            }
        }

        // Build the signal frame on the interrupted thread's user stack.
        let (frame_top, info_ptr, ctx_ptr): (usize, usize, usize) = match self
            .build_signal_frame(pid, tid, owner_tid, cpu, blocked, signum, sa_flags, restorer)
        {
            Some(frame) => frame,
            None => return SignalDeliveryOutcome::Escalate,
        };

        // Commit the signal-state changes now that the frame is in place.
        let nodefer: bool = (sa_flags & SA_NODEFER) != 0;
        let new_blocked: u64 = next_blocked(blocked, sa_mask, signum, nodefer) & !UNBLOCKABLE;
        {
            if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
                let state = thread.thread_state_mut();
                state.set_blocked(new_blocked);
                state.clear_pending(signum);
            }
        }
        {
            let signals = self.get_running_mut().state_mut().signals_mut();
            signals.clear_pending(signum);
            if (sa_flags & SA_RESETHAND) != 0 {
                signals.set_disposition(signum, SignalDisposition::Default);
            }
        }

        // Redirect the interrupted thread into its handler. The signal number is placed in the
        // handler's first argument register and, for `SA_SIGINFO` handlers, `info_ptr`/`ctx_ptr` in
        // the second and third (register-argument ABIs); on stack-argument ABIs they were already
        // written to the frame and these values are ignored.
        unsafe { redirect_to_handler(esp0, entry, frame_top, restorer, signum, info_ptr, ctx_ptr) };

        SignalDeliveryOutcome::Delivered
    }

    ///
    /// # Description
    ///
    /// Evaluates and, if warranted, performs delivery of a synchronous signal generated by a CPU
    /// exception to the faulting (running) thread.
    ///
    /// Called from the exception path once a fault has proved unresolved and unclaimed by an
    /// exception owner. The signal is recorded against the faulting thread (the thread-directed
    /// pending bit) and then evaluated: a caught (handler) disposition that is not blocked is
    /// delivered by building a signal frame on the thread's user stack, and the caller redirects the
    /// faulting context into the handler. Any other disposition — default, ignore, a blocked signal
    /// (which would otherwise re-fault in a loop), a missing restorer, or an unbuildable frame —
    /// reports [`SyncSignalOutcome::Terminate`] so the caller runs the signal's default action.
    ///
    /// # Parameters
    ///
    /// - `signum`: The signal number (1-based) generated by the fault.
    /// - `cpu`: Snapshot of the faulting thread's interrupted CPU context (read from the exception
    ///   frame), saved into the signal frame so `sigreturn()` can resume the faulting instruction.
    ///
    /// # Returns
    ///
    /// A [`SyncSignalOutcome`] describing what the caller must do.
    ///
    pub fn try_deliver_synchronous_signal(
        &mut self,
        signum: usize,
        cpu: SignalCpuContext,
    ) -> SyncSignalOutcome {
        // Guard the valid signal range up front: every bitset operation below shifts by
        // `signum - 1`, which would underflow for `signum == 0` and overflow for `signum > SIG_MAX`
        // and panic the kernel. An out-of-range vector cannot name a deliverable signal, so force
        // the default action.
        if signum == 0 || signum > SIG_MAX {
            return SyncSignalOutcome::Terminate;
        }

        let pid: ProcessIdentifier = self.get_pid();
        let tid: ThreadIdentifier = self.get_tid();
        let owner_tid: ThreadIdentifier = ThreadIdentifier::from(FPU_OWNER_TID.load(ORDER));

        // Record the synchronous signal against the faulting thread and read its blocked mask.
        let blocked: u64 = {
            let mut thread = match self.get_running_mut().find_thread_mut(tid) {
                Some(thread) => thread,
                None => return SyncSignalOutcome::Terminate,
            };
            let state = thread.thread_state_mut();
            state.post_pending(signum);
            state.blocked()
        };

        // A blocked synchronous signal cannot run its handler without immediately re-faulting in a
        // loop, so force the default action instead.
        if (blocked & (1u64 << (signum - 1))) != 0 {
            return SyncSignalOutcome::Terminate;
        }

        // Resolve the disposition: only a caught (handler) signal is delivered in-process. Default
        // and ignore both run the default action (terminate for the synchronous `Core` signals);
        // ignoring a hardware fault would otherwise loop forever.
        let (sa_mask, sa_flags): (u64, i32) = {
            let signals = self.get_running_mut().state_mut().signals_mut();
            match signals.disposition(signum) {
                Some(SignalDisposition::Handler(handler)) => (handler.mask, handler.flags),
                _ => return SyncSignalOutcome::Terminate,
            }
        };

        // The handler return address must be a registered restorer trampoline.
        let restorer: usize = match self.get_running_mut().state_mut().signals_mut().restorer() {
            Some(restorer) => restorer.into_raw_value(),
            None => {
                error!("no signal restorer registered (pid={pid:?}, signum={signum})");
                return SyncSignalOutcome::Terminate;
            },
        };

        // Build the signal frame on the faulting thread's user stack. An unbuildable frame (for
        // example, a smashed user stack) escalates to the default action.
        let (frame_top, info_ptr, ctx_ptr): (usize, usize, usize) = match self
            .build_signal_frame(pid, tid, owner_tid, cpu, blocked, signum, sa_flags, restorer)
        {
            Some(frame) => frame,
            None => return SyncSignalOutcome::Terminate,
        };

        // Re-resolve the handler entry now that the frame is in place. (It is read again rather than
        // held across the frame build so the borrow of the process manager is not extended.)
        let entry: usize = match self
            .get_running_mut()
            .state_mut()
            .signals_mut()
            .disposition(signum)
        {
            Some(SignalDisposition::Handler(handler)) => handler.entry.into_raw_value(),
            _ => return SyncSignalOutcome::Terminate,
        };

        // Commit the signal-state changes now that the frame is in place.
        let nodefer: bool = (sa_flags & SA_NODEFER) != 0;
        let new_blocked: u64 = next_blocked(blocked, sa_mask, signum, nodefer) & !UNBLOCKABLE;
        {
            if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
                let state = thread.thread_state_mut();
                state.set_blocked(new_blocked);
                state.clear_pending(signum);
            }
        }
        {
            let signals = self.get_running_mut().state_mut().signals_mut();
            signals.clear_pending(signum);
            if (sa_flags & SA_RESETHAND) != 0 {
                signals.set_disposition(signum, SignalDisposition::Default);
            }
        }

        SyncSignalOutcome::Delivered {
            entry,
            frame_top,
            restorer,
            info_ptr,
            ctx_ptr,
        }
    }

    ///
    /// # Description
    ///
    /// Builds the save area and on-stack arguments of a signal frame on the running thread's user
    /// stack, shared by the kernel-call and synchronous-exception delivery paths.
    ///
    /// The caller is responsible for snapshotting the interrupted context into `cpu`, redirecting
    /// the interrupted thread into the handler, and committing the blocked-mask and pending-set
    /// changes; this method only writes the frame to user space.
    ///
    /// # Parameters
    ///
    /// - `pid`: Identifier of the running process.
    /// - `tid`: Identifier of the running (target) thread.
    /// - `owner_tid`: Identifier of the thread that currently owns the live FPU.
    /// - `cpu`: Snapshot of the interrupted CPU context saved into the frame.
    /// - `blocked`: The blocked mask in effect before delivery, saved into the frame.
    /// - `signum`: The signal being delivered (1-based).
    /// - `sa_flags`: The handler flags (consulted for `SA_SIGINFO`).
    /// - `restorer`: Address of the user-space restorer trampoline used as the handler's return
    ///   address.
    ///
    /// # Returns
    ///
    /// A tuple `(frame_top, info_ptr, ctx_ptr)`, or [`None`] if the frame could not be placed or
    /// written safely. `frame_top` is the stack pointer the handler is entered with (the top of the
    /// frame). `info_ptr` and `ctx_ptr` are the user addresses of the embedded `siginfo` and context
    /// images for an `SA_SIGINFO` handler (both `0` when the handler is not `SA_SIGINFO`); on
    /// register-argument ABIs (x86-64) the caller loads them into the handler's second and third
    /// argument registers, while on stack-argument ABIs (x86) they are already written to the frame.
    ///
    #[allow(clippy::too_many_arguments)]
    fn build_signal_frame(
        &mut self,
        pid: ProcessIdentifier,
        tid: ThreadIdentifier,
        owner_tid: ThreadIdentifier,
        cpu: SignalCpuContext,
        blocked: u64,
        signum: usize,
        sa_flags: i32,
        restorer: usize,
    ) -> Option<(usize, usize, usize)> {
        let user_sp: usize = cpu.sp as usize;
        let layout: FrameLayout = frame_layout(user_sp)?;
        let frame_prefix_size: usize = layout.save_area_base - layout.frame_top;
        let frame_size: usize = frame_prefix_size + core::mem::size_of::<SigFrame>();
        // The target stack address derives from user-controlled state, so confirm the whole frame
        // region is mapped and writable before writing it. An unmapped or read-only page escalates
        // to the signal's default action instead of faulting the kernel's physical-alias write path
        // while building the frame.
        let vmem: &Vmem = self.get_running().state().vmem();
        if !vmem.is_user_region_writable(VirtualAddress::new(layout.frame_top), frame_size) {
            return None;
        }

        // Capture the FPU state of the interrupted thread.
        let fpu: [u8; FPU_AREA_SIZE] = self.snapshot_thread_fpu(tid, owner_tid == tid);

        // Build the frame, saving the mask that was in effect before delivery.
        let has_siginfo: bool = (sa_flags & SA_SIGINFO) != 0;
        let frame: SigFrame = build_frame(cpu, blocked, fpu, signum, has_siginfo);

        // Copy the save area to user space.
        if self
            .vmcopy_to_user(
                pid,
                VirtualAddress::new(layout.save_area_base),
                VirtualAddress::new(&frame as *const SigFrame as usize),
                core::mem::size_of::<SigFrame>(),
            )
            .is_err()
        {
            return None;
        }

        // Copy the return address and the on-stack handler arguments below the save area. Only the
        // bytes the ABI actually passes on the stack are written: the return address plus, on
        // architectures that pass handler arguments on the stack, the argument words. On x86-64 the
        // System V ABI passes the arguments in registers, so only the return address is written here
        // (the signal number is placed in a register by `redirect_to_signal_handler`), and writing
        // the full argument array would overrun into the save area that was just copied.
        let (info_ptr, ctx_ptr): (usize, usize) = if has_siginfo {
            (
                layout.save_area_base + sigframe::siginfo_offset(),
                layout.save_area_base + sigframe::ctx_offset(),
            )
        } else {
            (0, 0)
        };
        let args: [usize; 4] = [restorer, signum, info_ptr, ctx_ptr];
        let args_bytes: usize = frame_prefix_size;
        if self
            .vmcopy_to_user(
                pid,
                VirtualAddress::new(layout.frame_top),
                VirtualAddress::new(args.as_ptr() as usize),
                args_bytes,
            )
            .is_err()
        {
            return None;
        }

        Some((layout.frame_top, info_ptr, ctx_ptr))
    }

    ///
    /// # Description
    ///
    /// Restores the interrupted context saved in the signal frame on the running thread's user
    /// stack, completing a `sigreturn()` kernel call.
    ///
    /// # Returns
    ///
    /// On success, the value to leave in the return register (the interrupted accumulator). On
    /// failure, a [`SigReturnFailure`].
    ///
    pub fn sigreturn_restore(&mut self) -> Result<i64, SigReturnFailure> {
        // Architectures without a delivery path ship inert trap-frame placeholders, so a frame can
        // never have been built; treat `sigreturn()` there as an unsupported kernel call instead of
        // running the placeholder restore path and terminating the process as if the frame were
        // forged.
        if !cfg!(any(target_arch = "x86", target_arch = "x86_64", target_arch = "aarch64")) {
            return Err(SigReturnFailure::Unsupported);
        }

        let pid: ProcessIdentifier = self.get_pid();
        let tid: ThreadIdentifier = self.get_tid();

        let owner_tid: ThreadIdentifier = ThreadIdentifier::from(FPU_OWNER_TID.load(ORDER));
        let esp0: usize = {
            let mut thread = match self.get_running_mut().find_thread_mut(tid) {
                Some(thread) => thread,
                None => return Err(SigReturnFailure::Forged),
            };
            match thread.thread_state_mut().kernel_stack_top() {
                Some(esp0) => esp0.into_raw_value(),
                None => return Err(SigReturnFailure::Forged),
            }
        };

        // The restorer issues `sigreturn()` without adjusting the stack pointer, so the save area
        // sits just above the on-stack arguments.
        let user_sp: usize = unsafe { read_user_sp(esp0) };
        let save_area: usize = user_sp + save_area_offset_from_sigreturn_sp();

        // Copy the frame in and validate it.
        let mut frame: SigFrame = SigFrame {
            magic: 0,
            has_siginfo: 0,
            blocked: 0,
            siginfo: [0u32; 8],
            cpu: SignalCpuContext::default(),
            fpu: [0u8; FPU_AREA_SIZE],
        };
        if self
            .vmcopy_from_user(
                pid,
                VirtualAddress::new(&mut frame as *mut SigFrame as usize),
                VirtualAddress::new(save_area),
                core::mem::size_of::<SigFrame>(),
            )
            .is_err()
        {
            return Err(SigReturnFailure::Forged);
        }
        let cpu: SignalCpuContext = match validate_and_restore(&frame) {
            Ok(cpu) => cpu,
            Err(_) => return Err(SigReturnFailure::Forged),
        };

        // Restore the blocked mask and FPU state, then rewrite the trap frame to resume. If a
        // `sigsuspend()` is unwinding through this return, reinstate the mask it saved (restoring
        // the pre-suspend mask now that its interrupting handler has run) instead of the frame's
        // saved mask.
        {
            if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
                let state = thread.thread_state_mut();
                let restored_blocked: u64 = match state.take_saved_blocked() {
                    Some(saved) => saved & !UNBLOCKABLE,
                    None => frame.blocked & !UNBLOCKABLE,
                };
                state.set_blocked(restored_blocked);
            }
        }
        self.restore_thread_fpu(tid, owner_tid == tid, &frame.fpu);
        unsafe { restore_trap_context(esp0, &cpu) };

        Ok(join_kcall_result(cpu.ax, cpu.dx))
    }

    ///
    /// # Description
    ///
    /// Returns the FPU image of thread `tid`, refreshing the kernel-side copy from the live FPU
    /// first when the thread currently owns it.
    ///
    fn snapshot_thread_fpu(
        &mut self,
        tid: ThreadIdentifier,
        is_owner: bool,
    ) -> [u8; FPU_AREA_SIZE] {
        let mut image: [u8; FPU_AREA_SIZE] = [0u8; FPU_AREA_SIZE];
        if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
            let fpu_ptr = thread.thread_state_mut().fpu_state_mut();
            image = unsafe { capture_fpu(fpu_ptr, is_owner) };
        }
        image
    }

    ///
    /// # Description
    ///
    /// Writes `image` into thread `tid`'s FPU state, and reloads the live FPU when the thread
    /// currently owns it so the restored state takes effect immediately.
    ///
    fn restore_thread_fpu(
        &mut self,
        tid: ThreadIdentifier,
        is_owner: bool,
        image: &[u8; FPU_AREA_SIZE],
    ) {
        if let Some(mut thread) = self.get_running_mut().find_thread_mut(tid) {
            let fpu_ptr = thread.thread_state_mut().fpu_state_mut();
            unsafe { install_fpu(fpu_ptr, is_owner, image) };
        }
    }
}
