# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "libc_sys_un"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "POSIX UNIX Domain Socket Address Library"
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]

[features]
default = []
# Enables the use of the Rust Standard Library.
std = []

[lints]
workspace = true
