# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "noop-wasm-rust"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "No-Operation Benchmark for Wasm/Rust"
homepage.workspace = true

[lints]
workspace = true
