// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//==================================================================================================
// Build-Generated Assembly Constants
//==================================================================================================

// Values generated by build.rs from build/kernel_config.toml.
include!(concat!(env!("OUT_DIR"), "/asm_constants.rs"));
