# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "test-rust-cmdline-env-nostd"
version.workspace = true
license-file.workspace = true
edition = "2024"
authors.workspace = true
description = "Integration test for command-line argument and environment variable passing"
homepage.workspace = true

[[bin]]
name = "test-rust-cmdline-env-nostd"

[dependencies]
nvx = { workspace = true }
nvx-crt0 = { workspace = true, features = ["rust-main", "provides-allocator"] }
sysalloc = { workspace = true }
libc_string = { workspace = true }
sys = { workspace = true, features = ["kcall"] }
sysapi = { workspace = true }
syscall = { workspace = true, features = ["syscall"] }
syslog = { workspace = true, default-features = true }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[features]
default = ["panic"]
panic = ["nvx/panic", "nvx-crt0/panic"]
