#!/bin/bash
# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

# Build, install, and configure the Nanvix containerd shim.
#
# Prerequisites:
#   - Rust toolchain (cargo) in PATH
#   - Docker/containerd installed (see install-containerd.sh)
#   - Nanvix built at ~/nanvix (see setup-nanvix.sh)
#
# Usage: ./scripts/install-shim.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default Nanvix binary locations — override with env vars if needed
NANVIX_DIR="${NANVIX_DIR:-$HOME/nanvix}"
NANVIXD_PATH="${NANVIXD_PATH:-$NANVIX_DIR/bin/nanvixd.elf}"
MKRAMFS_PATH="${MKRAMFS_PATH:-$NANVIX_DIR/bin/mkramfs.elf}"

echo "=== Building shim (release) ==="
cd "$PROJECT_DIR"
cargo build --release -p containerd-shim-nanvix-v1
echo "Built: target/release/containerd-shim-nanvix-v1"

echo "=== Installing shim binary ==="
sudo rm -f /usr/local/bin/containerd-shim-nanvix-v1
sudo cp target/release/containerd-shim-nanvix-v1 /usr/local/bin/
sudo chmod 755 /usr/local/bin/containerd-shim-nanvix-v1
echo "Installed to /usr/local/bin/containerd-shim-nanvix-v1"
containerd-shim-nanvix-v1 -version

echo "=== Writing shim config ==="
sudo mkdir -p /etc/nanvix

# Verify Nanvix binaries exist
if [[ ! -f "$NANVIXD_PATH" ]]; then
    echo "ERROR: nanvixd.elf not found at $NANVIXD_PATH"
    echo "Set NANVIX_DIR or NANVIXD_PATH env var, or build Nanvix first."
    exit 1
fi
if [[ ! -f "$MKRAMFS_PATH" ]]; then
    echo "ERROR: mkramfs.elf not found at $MKRAMFS_PATH"
    echo "Set NANVIX_DIR or MKRAMFS_PATH env var, or build Nanvix first."
    exit 1
fi

sudo tee /etc/nanvix/shim-config.toml > /dev/null <<EOF
# Nanvix containerd shim configuration
# Generated by install-shim.sh on $(date -Iseconds)

# Path to the nanvixd kernel binary on the host
kernel_path = "$NANVIXD_PATH"

# Path to the mkramfs tool on the host
mkramfs_path = "$MKRAMFS_PATH"

# Temporary directory for generated ramfs images
temp_dir = "/tmp"


# Additional arguments passed to nanvixd
# -console-file /dev/null suppresses guest console output
extra_args = ["-console-file", "/dev/null"]
EOF

echo "Config written to /etc/nanvix/shim-config.toml"
cat /etc/nanvix/shim-config.toml

echo ""
echo "=== Shim is ready ==="
echo ""
echo "The runtime 'io.containerd.nanvix.v1' is now available."
echo "containerd discovers it automatically from the binary name in PATH."
echo ""
echo "Quick test:"
echo "  sudo ctr run --rm --runtime io.containerd.nanvix.v1 \\"
echo "    --label com.nanvix.os=nanvix \\"
echo "    --label com.nanvix.arch=x86 \\"
echo "    --label com.nanvix.initrd.path=/initrd/hello-rust-nostd.elf \\"
echo "    docker.io/library/nanvix-hello:latest test-hello"
