# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

all: all-procd all-memd all-testd

clean: clean-procd clean-memd clean-testd

all-procd:
	$(MAKE) -C procd all

clean-procd:
	$(MAKE) -C procd clean

all-memd:
	$(MAKE) -C memd all

clean-memd:
	$(MAKE) -C memd clean

all-testd:
	$(MAKE) -C testd all

clean-testd:
	$(MAKE) -C testd clean
