# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

name: "Lint"
description: "Run the lint target on the source code"

inputs:
  release:
    description: "Release type"
    required: true
    default: "release"
  log-level:
    description: "Log level"
    required: true
    default: "trace"
  machine-type:
    description: "Machine type"
    required: true
    default: "microvm"
  deployment-type:
    description: "Deployment type"
    required: true
    default: "single-process"
  target-arch:
    description: "Target architecture (x86 or x86_64)"
    required: false
    default: "x86"

runs:
  using: "composite"
  steps:
    - id: deployment
      uses: ./.github/actions/deployment-features
      with:
        deployment-type: "${{ inputs.deployment-type }}"
    - name: "Lint (${{ inputs.machine-type }})"
      shell: bash
      run: |
        ./z build \
          -- \
          lint-check \
          "MACHINE=${{ inputs.machine-type }}" \
          TARGET=${{ inputs.target-arch }} \
          "LOG_LEVEL=${{ inputs.log-level }}" \
          VERBOSE=yes \
          ${{ inputs.release == 'release' && 'RELEASE=yes' || '' }} \
          ${{ steps.deployment.outputs.make-flags }}
