# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "syscomm"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "System Communication Library"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
config = { workspace = true }
log = { workspace = true }
mio = { workspace = true, features = ["net", "os-poll"] }
