# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nanvix-terminal"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Terminal interface for Nanvix"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
config = { workspace = true, optional = true }
libc = { workspace = true }
log = { workspace = true }
nanvix-sandbox = { workspace = true, optional = true }
nanvix-sandbox-config = { workspace = true, optional = true }
tokio = { workspace = true, features = ["full"] }
user-vm-api = { workspace = true }
uservm = { workspace = true, optional = true }

[features]
default = ["microvm", "standalone"]
single-process = [
    "nanvix-sandbox-config",
    "nanvix-sandbox-config/single-process",
    "nanvix-sandbox",
    "nanvix-sandbox/single-process",
]
standalone = ["config", "nanvix-sandbox-config", "uservm"]
gdb = ["uservm?/gdb", "nanvix-sandbox-config?/gdb"]
# Enables fine-grained time profiling.
profile-time = ["uservm?/profile-time", "nanvix-sandbox?/profile-time"]
microvm = ["config?/microvm", "uservm?/microvm", "nanvix-sandbox?/microvm"]
whp = ["config?/whp", "uservm?/whp", "nanvix-sandbox?/whp"]

[lints]
workspace = true
