# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "nanvix-terminal"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Terminal interface for Nanvix"
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
nanvix-sandbox-cache = { workspace = true }
syslog = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
user-vm-api = { workspace = true }

[features]
default = []
hyperlight = ["nanvix-sandbox-cache/hyperlight"]
single-process = ["nanvix-sandbox-cache/single-process"]
