# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "libc_wchar"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
libc_stdio = { workspace = true }
sysapi = { workspace = true }

[target.'cfg(target_os = "nanvix")'.dependencies]
libc_stdlib = { workspace = true, default-features = false, features = ["default"] }

[features]
default = []
# Enables the use of the Rust Standard Library.
std = ["libc_stdio/std"]

[lints]
workspace = true
