.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH "cat" 1 "February 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
cat \- Concatenates files
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "cat [" "options" "] [" "files" "]"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR cat 
reads each file in sequence and writes it to the standard output. If no input 
file is given, or if the argument '-' is encountered,
.BR cat
reads from the standard input file.
.\"
.\"=============================================================================
.\"
.SH "OPTIONS"
.\"
.TP 
.BR --help
Display help information and exits.

.TP
.BR --version
Display program version and exits.
.\"
.\"=============================================================================
.\"
.SH "BUGS"
.\"
If the standard input file is supplied as argument, like:

.BR "cat" " x > x"

Weird things may happen.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
