.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH "echo" 1 "January 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
echo \- Echo arguments
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "echo [" "args" "]"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR echo
writes its arguments in order as a line on the standard output file. It is 
mainly useful for producing diagnostics in command files.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
