.\"
.\" Copyright(C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.\"=============================================================================
.\"
.TH "echo" 1 "January 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
echo \- Echo arguments
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "echo [" "args" "]"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR echo
writes its arguments in order as a line on the standard output file. It is 
mainly useful for producing diagnostics in command files.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
