.\"
.\" Copyright(C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.\"=============================================================================
.\"
.TH "ls" 1 "February 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
ls \- Lists contents of a directory
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "ls [" "options" "] [" "directory" "]"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR ls 
lists the contents of a directory, writing the output to the standard output 
file.
.\"
.\"=============================================================================
.\"
.SH "OPTIONS"
.\"
.TP
.BR "-a " "--all"
List all entries. Usually those begining with '.' are supressed.

.TP
.BR "-i " "--inode"
Print the inode number of each file.

.TP 
.BR --help
Display help information and exits.

.TP
.BR --version
Display program version and exits.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
