.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH "ls" 1 "February 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
ls \- Lists contents of a directory
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "ls [" "options" "] [" "directory" "]"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR ls 
lists the contents of a directory, writing the output to the standard output 
file.
.\"
.\"=============================================================================
.\"
.SH "OPTIONS"
.\"
.TP
.BR "-a " "--all"
List all entries. Usually those begining with '.' are supressed.

.TP
.BR "-i " "--inode"
Print the inode number of each file.

.TP 
.BR --help
Display help information and exits.

.TP
.BR --version
Display program version and exits.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
