.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH "pwd" 1 "January 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
pwd \-  Prints working directory name
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI pwd
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
.BR pwd
prints the pathname of the current working directory to the standard output
file. It is mainly useful for guiding you when traversing the file system tree. 
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
