.\"
.\" Copyright (C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
.\"=============================================================================
.\"
.TH "stat" 1 "January 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
stat \- Displays file status
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "stat [" "options" "] " file
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The 
.BR stat
command displays file status information. It is useful for getting quick 
information about a file like access permissions, owner, size, etc.
.\"
.\"=============================================================================
.\"
.SH "OPTIONS"
.\"
.TP 
.BR --help
Displays help information and exits.

.TP
.BR --version
Displays program version and exits.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
