// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//==================================================================================================
// Lint Configuration
//==================================================================================================

#![allow(clippy::module_inception)]
// The WHP backend interfaces with the Windows Hypervisor Platform API, which
// uses u32/u16 parameters extensively. These casts are intentional and safe.
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::collapsible_match)]

//==================================================================================================
// Modules
//==================================================================================================

pub mod console;
pub mod lapic;
pub mod partition;
pub mod timer;
pub mod vcpu;
pub mod vmem;

//==================================================================================================
// Imports
//==================================================================================================

use crate::{
    orchestrator::{
        VcpuControlCommand,
        VcpuControlResponse,
    },
    vmm::{
        MicroVmArgs,
        emulator::Emulator,
        guest::{
            Guest,
            GuestState,
            PreparedInitrd,
        },
        microvm::{
            ramfs,
            ramfs::RamFs,
            whp::vcpu::{
                VirtualProcessor,
                VirtualProcessorExitContext,
                VirtualProcessorExitReasonRef,
            },
        },
    },
};
use ::anyhow::Result;
use ::log::{
    error,
    trace,
    warn,
};
use ::serde::{
    Deserialize,
    Serialize,
};
use ::std::{
    ffi::OsStr,
    fs::File,
    io::Write,
    path::{
        Path,
        PathBuf,
    },
    sync::{
        Arc,
        atomic::{
            AtomicBool,
            Ordering,
        },
    },
    time::Instant,
};
use ::sys::error::ErrorCode;
use ::tokio::{
    runtime::Handle,
    sync::{
        Mutex,
        MutexGuard,
        mpsc::{
            Receiver,
            Sender,
        },
    },
    task,
};

#[cfg(feature = "profile-time")]
use crate::perf::PerfTimings;

//==================================================================================================
// Re-exports
//==================================================================================================

pub use crate::vmm::microvm::whp::vcpu::exit::{
    PmioAccess,
    PmioWidth,
};
pub use vmem::VirtualMemory;

//==================================================================================================
// Constants
//==================================================================================================

/// IDT vector for IRQ 9 (IKC): PIC2 base (0x28) + (IRQ 9 - 8) = 0x29.
const IKC_VECTOR: u32 = 0x29;

/// Pvclock host timer period in microseconds (10 ms = 100 Hz). This timer
/// forces periodic VM exits via `WHvCancelRunVirtualProcessor` so the VMM loop
/// can update the pvclock `system_time` field. 100 Hz is high enough that the
/// guest sees sub-10 ms clock drift between LAPIC tick interpolations, yet low
/// enough to keep the VM-exit overhead negligible.
const PVCLOCK_TIMER_PERIOD_US: u64 = 10_000;

/// PIT oscillator frequency in Hz (1.193181 MHz).
const PIT_FREQ_HZ: u64 = 1_193_181;

//==================================================================================================
// PIT Channel 2 Emulation
//==================================================================================================

/// Minimal emulation of PIT channel 2 one-shot mode for LAPIC timer
/// calibration. Tracks channel 2 programming via port I/O and provides
/// the OUT2 status bit (bit 5 of port 0x61) based on elapsed host time.
///
/// This is the *only* PIT (8254) functionality emulated on WHP, and it
/// exists solely as a calibration fallback: the guest kernel programs PIT
/// channel 2 in one-shot mode and polls port 0x61 bit 5 to time a known
/// window when the host does not expose a TSC base frequency (CPUID leaf
/// 0x16 returns 0). When the TSC frequency *is* available the kernel
/// calibrates via RDTSC and never touches the PIT at all.
///
/// Full PIT emulation is deliberately omitted because timer *interrupts*
/// are never delivered through the PIT on WHP: the periodic scheduling
/// tick is generated by the WHP LAPIC emulator's own timer, and the
/// host-side [`timer::Timer`] only forces VM exits for pvclock updates.
/// Channel 0/1 programming and the other legacy PIT ports are therefore
/// handled as intentional no-ops in the PMIO dispatch loop.
struct PitCh2State {
    /// Whether channel 2 is in one-shot mode (mode 0).
    active: bool,
    /// Reload value for the countdown.
    reload: u16,
    /// Next byte expected: false = low byte, true = high byte.
    expect_hi: bool,
    /// Speaker gate enabled (bit 0 of port 0x61).
    gate_enabled: bool,
    /// Host timestamp when the countdown started.
    start_time: Option<Instant>,
}

impl PitCh2State {
    fn new() -> Self {
        Self {
            active: false,
            reload: 0,
            expect_hi: false,
            gate_enabled: false,
            start_time: None,
        }
    }

    /// Handles a write to port 0x43 (PIT control register).
    fn handle_ctrl_write(&mut self, byte: u8) {
        let channel: u8 = (byte >> 6) & 0x03;
        if channel != 2 {
            return;
        }
        // Mode 0 = interrupt on terminal count (one-shot).
        let mode: u8 = (byte >> 1) & 0x07;
        self.active = mode == 0;
        self.reload = 0;
        self.expect_hi = false;
        self.start_time = None;
    }

    /// Handles a write to port 0x42 (PIT channel 2 data register).
    fn handle_data_write(&mut self, byte: u8) {
        if !self.active {
            return;
        }
        if !self.expect_hi {
            self.reload = (self.reload & 0xFF00) | (byte as u16);
            self.expect_hi = true;
        } else {
            self.reload = (self.reload & 0x00FF) | ((byte as u16) << 8);
            self.expect_hi = false;
            if self.gate_enabled {
                self.start_time = Some(Instant::now());
            }
        }
    }

    /// Handles a write to port 0x61 (speaker/gate control).
    fn handle_speaker_write(&mut self, byte: u8) {
        self.gate_enabled = (byte & 0x01) != 0;
        if self.gate_enabled && self.active && self.reload > 0 && self.start_time.is_none() {
            self.start_time = Some(Instant::now());
        }
    }

    /// Reads port 0x61 (speaker status). Returns bit 5 (OUT2) set when
    /// the PIT channel 2 countdown has expired.
    fn read_speaker(&self) -> u8 {
        let mut result: u8 = if self.gate_enabled { 0x01 } else { 0x00 };
        if let Some(start) = self.start_time {
            let duration_ns: u64 = (self.reload as u64) * 1_000_000_000 / PIT_FREQ_HZ;
            if start.elapsed().as_nanos() as u64 >= duration_ns {
                result |= 0x20;
            }
        }
        result
    }
}

//==================================================================================================
// IKC Notifier
//==================================================================================================

/// Notifier that signals the VMM loop to inject an IKC interrupt after the host writes credits.
///
/// Delivers the IKC vector via `WHvRequestInterrupt` through the WHP
/// LAPIC emulator. This wakes the vCPU from HLT and delivers the
/// interrupt when IF=1.
#[derive(Clone)]
pub struct IkcNotifier {
    pending: Arc<AtomicBool>,
    /// Set to true after the VMM has shut down.
    shutdown: Arc<AtomicBool>,
    /// WHP partition handle for `WHvRequestInterrupt`.
    partition: windows::Win32::System::Hypervisor::WHV_PARTITION_HANDLE,
}

// SAFETY: WHV_PARTITION_HANDLE is an opaque OS handle that can be used from
// any thread. The IkcNotifier struct has no thread-affine state.
unsafe impl Send for IkcNotifier {}
unsafe impl Sync for IkcNotifier {}

impl IkcNotifier {
    fn new(partition: windows::Win32::System::Hypervisor::WHV_PARTITION_HANDLE) -> Self {
        Self {
            pending: Arc::new(AtomicBool::new(false)),
            shutdown: Arc::new(AtomicBool::new(false)),
            partition,
        }
    }

    /// Signals that an IKC message is available.
    ///
    /// Delivers the IKC vector (0x29) via `WHvRequestInterrupt` through
    /// the LAPIC emulator. This wakes the vCPU from HLT.
    pub fn notify(&self) -> Result<()> {
        if self.shutdown.load(Ordering::Acquire) {
            return Ok(());
        }
        // Only request an interrupt on the transition from not-pending to pending.
        if self.pending.swap(true, Ordering::AcqRel) {
            return Ok(());
        }

        let interrupt = windows::Win32::System::Hypervisor::WHV_INTERRUPT_CONTROL {
            _bitfield: 0, // Fixed, Physical, Edge.
            Destination: 0,
            Vector: IKC_VECTOR,
        };
        // SAFETY: partition handle outlives the notifier.
        let hr = unsafe {
            windows::Win32::System::Hypervisor::WHvRequestInterrupt(
                self.partition,
                &interrupt,
                ::std::mem::size_of::<windows::Win32::System::Hypervisor::WHV_INTERRUPT_CONTROL>()
                    as u32,
            )
        };
        if let Err(e) = hr {
            // Interrupt was not delivered; clear pending so callers can retry.
            self.pending.store(false, Ordering::Release);
            log::error!("WHvRequestInterrupt failed for IKC: {e:?}");
            anyhow::bail!("WHvRequestInterrupt failed for IKC: {e:?}");
        }
        Ok(())
    }

    /// Returns true if an IKC notification is pending, and clears the flag.
    fn take_pending(&self) -> bool {
        self.pending.swap(false, Ordering::AcqRel)
    }

    /// Marks the notifier as shut down, preventing future `notify()` calls from invoking
    /// WHP APIs.
    fn mark_shutdown(&self) {
        self.shutdown.store(true, Ordering::Release);
    }
}

//==================================================================================================
// Snapshot
//==================================================================================================

/// Serializable WHP snapshot holding guest metadata and vCPU register state.
///
/// Memory is saved separately via the dense snapshot APIs
/// [`vmem::VirtualMemory::save_snapshot_dense`] and
/// [`vmem::VirtualMemory::load_snapshot_cow`].
#[derive(Serialize, Deserialize)]
struct WhpSnapshot {
    /// Guest metadata (kernel/initrd locations, credits, entry point).
    guest_state: GuestState,
    /// Full vCPU register and LAPIC state.
    vcpu_state: vcpu::VcpuState,
    /// Pvclock `system_time` value (nanoseconds) at the moment the snapshot was taken.
    /// On restore, this becomes the time base so the guest sees monotonically advancing time.
    #[serde(default)]
    pvclock_time_ns: u64,
}

//==================================================================================================
// Structures
//==================================================================================================

///
/// # Description
///
/// A structure that represents a VMM backed by Windows Hypervisor Platform (WHP).
///
#[derive(Clone)]
pub struct Vmm {
    /// Guest of the virtual machine.
    guest: Arc<Mutex<Guest>>,
    /// Virtual memory of the virtual machine.
    vmem: Arc<Mutex<VirtualMemory>>,
    /// Virtual processor of the virtual machine.
    vcpu: Arc<Mutex<VirtualProcessor>>,
    /// IKC notifier for waking the guest when credits are added.
    ikc_notifier: IkcNotifier,
    /// Partition handle, used to cancel the running vCPU (pvclock and
    /// guest-profiler timers). Also shared with [`IkcNotifier`] for interrupt
    /// delivery via the WHP LAPIC emulator. Not used for PIT emulation.
    partition_handle: windows::Win32::System::Hypervisor::WHV_PARTITION_HANDLE,
    /// Low-frequency host timer for pvclock updates. Calls
    /// `WHvCancelRunVirtualProcessor` at 100Hz while a vCPU run is pending to force VM exits so
    /// the VMM loop can update `system_time`. The LAPIC periodic timer
    /// handles actual 1kHz scheduling inside the WHP emulator (zero
    /// VM exits for timer delivery).
    timer: Arc<std::sync::Mutex<timer::Timer>>,
    /// Shared shutdown flag. When set to `true` from any thread, the VMM
    /// run loop will break on the next iteration.
    shutdown_flag: Arc<AtomicBool>,
    /// Synchronizes cancellation with entry to and return from `WHvRunVirtualProcessor`.
    run_state: Arc<RunState>,
    /// Wraps fields that don't require individual `Arc<Mutex<_>>`s.
    inner: Arc<Mutex<InteriorWhpHandle>>,
    /// Pvclock time base in nanoseconds. When restoring from a snapshot, this is set to
    /// the `system_time` value at snapshot time so that the guest sees monotonically
    /// increasing time (base + run-loop elapsed).
    pvclock_time_base_ns: Arc<std::sync::atomic::AtomicU64>,
    /// Last pvclock `system_time` value (nanoseconds) written to the guest. Used by
    /// `create_snapshot` to persist the current time without needing access to `loop_start`.
    pvclock_last_written_ns: Arc<std::sync::atomic::AtomicU64>,
    /// Performance timings collector for fine-grained startup breakdown.
    #[cfg(feature = "profile-time")]
    perf_timings: PerfTimings,
    /// Guest stack profiler (active when guest_profile_path is set).
    guest_profiler: Option<Arc<std::sync::Mutex<Vec<crate::guest_profiler::StackSample>>>>,
}

///
/// # Description
///
/// An internal structure to the VMM that wraps its contents in `Arc<Mutex<_>>`. It allows
/// the VMM to be clonable without wrapping each field in `Arc<Mutex<_>>`.
///
struct InteriorWhpHandle {
    /// WHP partition handle (must outlive vCPU and vmem).
    _partition: partition::WhpPartition,
    /// Emulator of the virtual machine.
    emulator: Emulator,
    /// Channel to receive commands from the VMM.
    control_rx: Receiver<VcpuControlCommand>,
    /// Channel to send control responses to the VMM.
    control_tx: Sender<VcpuControlResponse>,
    /// Kernel filename used for snapshot path derivation.
    kernel_filename: String,
    /// When true, the next guest-initiated snapshot request is silently skipped.
    skip_next_snapshot: bool,
    /// When true, the guest is entitled to take exactly one snapshot.
    /// Set from the `snapshot` kernel option; consumed on the first successful request.
    snapshot_allowed: bool,
}

/// Synchronizes cancellation with `WHvRunVirtualProcessor`.
struct RunState {
    /// Whether the vCPU is about to enter or is blocked in `WHvRunVirtualProcessor`.
    pending: AtomicBool,
    /// Serializes cancellation calls with transitions out of the pending state.
    cancel_gate: std::sync::Mutex<()>,
}

impl RunState {
    fn new() -> Self {
        Self {
            pending: AtomicBool::new(false),
            cancel_gate: std::sync::Mutex::new(()),
        }
    }

    fn lock_cancel_gate(&self) -> std::sync::MutexGuard<'_, ()> {
        match self.cancel_gate.lock() {
            Ok(guard) => guard,
            Err(poisoned) => poisoned.into_inner(),
        }
    }

    fn begin_run(&self) {
        let _guard: std::sync::MutexGuard<'_, ()> = self.lock_cancel_gate();
        self.pending.store(true, Ordering::SeqCst);
    }

    fn finish_run(&self) {
        let _guard: std::sync::MutexGuard<'_, ()> = self.lock_cancel_gate();
        self.pending.store(false, Ordering::SeqCst);
    }

    fn is_pending(&self) -> bool {
        self.pending.load(Ordering::SeqCst)
    }

    /// Runs `cancel` only while a vCPU entry is pending. Holding `cancel_gate` until the call
    /// returns ensures that once [`RunPendingGuard`] is dropped, no cancellation can overlap with
    /// snapshot or teardown operations on the same WHP partition.
    fn cancel_if_pending<F>(&self, cancel: F) -> bool
    where
        F: FnOnce(),
    {
        let _guard: std::sync::MutexGuard<'_, ()> = self.lock_cancel_gate();
        if self.pending.load(Ordering::SeqCst) {
            cancel();
            true
        } else {
            false
        }
    }
}

/// Clears the WHP run-pending state whenever a vCPU entry attempt finishes or unwinds.
struct RunPendingGuard<'a> {
    run_state: &'a RunState,
}

impl<'a> RunPendingGuard<'a> {
    fn new(run_state: &'a RunState) -> Self {
        run_state.begin_run();
        Self { run_state }
    }
}

impl Drop for RunPendingGuard<'_> {
    fn drop(&mut self) {
        self.run_state.finish_run();
    }
}

/// Repeatedly requests cancellation until the pending or active WHP run finishes.
fn cancel_while_run_pending<F>(run_state: &RunState, mut cancel: F)
where
    F: FnMut(),
{
    while run_state.cancel_if_pending(&mut cancel) {
        std::thread::sleep(std::time::Duration::from_millis(1));
    }
}

//==================================================================================================
// Types
//==================================================================================================

pub type StdinFn =
    dyn FnMut(&Arc<Mutex<Guest>>, &Arc<Mutex<VirtualMemory>>, u32, usize) -> Result<()> + Send;

pub type StdoutFn =
    dyn FnMut(&Arc<Mutex<VirtualMemory>>, &::sys::ipc::VmBusMessage) -> Result<()> + Send;

pub type StderrFn = dyn Write + Send;

//==================================================================================================
// Implementations
//==================================================================================================

impl Vmm {
    ///
    /// # Description
    ///
    /// Creates a VMM backed by Windows Hypervisor Platform.
    ///
    /// # Parameters
    ///
    /// - `args`: Arguments for creating the VMM.
    ///
    /// # Returns
    ///
    /// Upon successful completion, this method returns the VMM that was created. Otherwise, it
    /// returns an error.
    ///
    pub fn new(args: MicroVmArgs) -> Result<Self> {
        trace!("new(): args={:?}", args);

        #[cfg(feature = "profile-time")]
        let perf_timings: PerfTimings = args.perf_timings.clone();

        // Phase: WHP partition creation.
        #[cfg(feature = "profile-time")]
        let partition_create_start: Instant = Instant::now();

        let partition: partition::WhpPartition = partition::WhpPartition::new()?;

        #[cfg(feature = "profile-time")]
        perf_timings.set_partition_create(partition_create_start.elapsed().as_micros() as u64);

        #[cfg(feature = "profile-time")]
        let vmem_create_start: Instant = Instant::now();

        let mut vmem: VirtualMemory =
            VirtualMemory::new(&partition, ::config::kernel::MEMORY_SIZE)?;

        #[cfg(feature = "profile-time")]
        perf_timings.set_vmem_create(vmem_create_start.elapsed().as_micros() as u64);

        #[cfg(feature = "profile-time")]
        let vcpu_create_start: Instant = Instant::now();

        let mut vcpu: VirtualProcessor = VirtualProcessor::new(&partition, 0)?;

        #[cfg(feature = "profile-time")]
        perf_timings.set_vcpu_create(vcpu_create_start.elapsed().as_micros() as u64);

        // Determine whether the snapshot kernel option is present.
        let snapshot_allowed: bool = args.kernel_args.as_deref().is_some_and(|kargs| {
            ::koptions::parse(kargs).contains(&::koptions::KernelOption::Snapshot)
        });

        let guest: Arc<Mutex<Guest>> = if args.restoring_from_snapshot {
            Arc::new(Mutex::new(Guest::default()))
        } else {
            let mut guest: Guest = Guest::default();

            // Phase: Kernel loading.
            #[cfg(feature = "profile-time")]
            let kernel_load_start: Instant = Instant::now();

            guest.load_kernel(&mut vmem, &args.kernel_filename)?;

            #[cfg(feature = "profile-time")]
            perf_timings.set_kernel_load(kernel_load_start.elapsed().as_micros() as u64);

            // Write kernel arguments to guest control registers. These registers reside in
            // the kernel ELF's `.zero` section, which `load_kernel()` zero-fills by default, so
            // this write must happen after it. (With the `nightly-performance-optimizations`
            // feature the loader skips that zeroing and relies on the freshly allocated guest
            // memory already being zero, but writing after `load_kernel()` remains correct.)
            if let Some(ref kargs) = args.kernel_args {
                Guest::write_kernel_args(&mut vmem, kargs)?;
            }

            // Phase: Initrd loading.
            // When a RAMFS will also be loaded, prepare the initrd for zero-copy mapping
            // so it can be combined with the RAMFS into a single remap_files_at() call.
            #[cfg(feature = "profile-time")]
            let initrd_load_start: Instant = Instant::now();

            let has_ramfs: bool = args.ramfs_filename.is_some();

            // When RAMFS is present, page-aligned initrd files can be included in the
            // combined zero-copy remap.  Non-page-aligned files fall back to copy-based
            // loading because `CreateFileMappingW(PAGE_WRITECOPY)` constrains the section's
            // maximum size to the raw file size, which cannot match a page-granular
            // placeholder required by `MapViewOfFile3(MEM_REPLACE_PLACEHOLDER)`.
            let prepared_initrd: Option<PreparedInitrd> = if has_ramfs {
                if let Some(ref initrd_filename) = args.initrd_filename {
                    let file_len: u64 = std::fs::metadata(initrd_filename)
                        .map_err(|e| anyhow::anyhow!("failed to query initrd metadata: {e}"))?
                        .len();
                    if (file_len as usize).is_multiple_of(::arch::mem::PAGE_SIZE) {
                        // Page-aligned: defer to combined zero-copy remap.
                        Some(guest.prepare_initrd(
                            &vmem,
                            initrd_filename,
                            args.initrd_args.clone(),
                        )?)
                    } else {
                        // Not page-aligned: fall back to copy-based loading.
                        guest.load_initrd(&mut vmem, initrd_filename, args.initrd_args.clone())?;
                        None
                    }
                } else {
                    None
                }
            } else {
                // No RAMFS to combine with: fall back to the copy-based path.
                args.initrd_filename
                    .as_ref()
                    .map(|initrd_filename| {
                        guest.load_initrd(&mut vmem, initrd_filename, args.initrd_args)
                    })
                    .transpose()?;
                None
            };

            #[cfg(feature = "profile-time")]
            perf_timings.set_initrd_load(initrd_load_start.elapsed().as_micros() as u64);

            // Phase: RamFS loading (with optional combined initrd zero-copy remap).
            #[cfg(feature = "profile-time")]
            let ramfs_load_start: Instant = Instant::now();

            let ramfs_region: Option<(usize, usize)> = {
                let initrd_end: usize = match guest.initrd_region() {
                    Some((base, size)) => match base.checked_add(size) {
                        Some(end) => end,
                        None => {
                            let reason: String = "initrd region overflowed while computing ramfs \
                                                  placement"
                                .to_string();
                            error!("new(): {reason}");
                            anyhow::bail!(reason)
                        },
                    },
                    None => ::config::microvm::DEFAULT_INITRD_BASE,
                };

                // Build the extra remap regions list from the prepared initrd (if any).
                let initrd_remap: Vec<(usize, &std::fs::File)> = prepared_initrd
                    .as_ref()
                    .map(|pi| vec![(pi.base, &pi.file)])
                    .unwrap_or_default();

                let loaded: ramfs::LoadedRamFs = ramfs::load_ramfs(
                    &mut vmem,
                    initrd_end,
                    args.ramfs_filename.as_deref(),
                    &initrd_remap,
                )?;

                match loaded {
                    ramfs::LoadedRamFs::Single { base, size, .. } => Some((base, size)),
                    ramfs::LoadedRamFs::None => None,
                }
            };

            // Finalize initrd arguments: write them into the gap memory between
            // the initrd view and the ramfs view, which was re-committed by the
            // combined remap.
            if let Some(ref pi) = prepared_initrd
                && let Some(ref initrd_args_str) = pi.args
            {
                guest.write_args(&mut vmem, initrd_args_str)?;
            }

            // Keep the initrd file handle alive for the VM's lifetime so the
            // file-backed mapping remains valid.
            if let Some(pi) = prepared_initrd {
                vmem.attach_backing_files(vec![pi.file]);
            }

            RamFs::write_registers(&mut vmem, ramfs_region)?;

            // Write host TSC base frequency so the guest can use RDTSC-based LAPIC
            // timer calibration without requiring CPUID leaf 0x16.
            let tsc_freq_mhz: u32 = ::arch::cpu::cpuid::get_base_frequency_mhz();
            vmem.write_bytes(
                ::config::microvm::DEFAULT_MICROVM_CTRL_TSC_FREQ_MHZ as u64,
                &tsc_freq_mhz.to_le_bytes(),
            )?;
            trace!("ctrl: tsc_freq_mhz={tsc_freq_mhz}");

            #[cfg(feature = "profile-time")]
            perf_timings.set_ramfs_load(ramfs_load_start.elapsed().as_micros() as u64);

            // Phase: vCPU reset and pvclock setup.
            #[cfg(feature = "profile-time")]
            let vcpu_reset_start: Instant = Instant::now();

            // Populate the pvclock page so the kernel uses TSC-based time instead
            // of PIT tick counting. The page at DEFAULT_PVCLOCK_PAGE resides in the
            // kernel ELF's `.zero` section, which `load_kernel()` zero-fills by default,
            // so this must run after it. (With the `nightly-performance-optimizations`
            // feature the loader skips that zeroing and relies on the freshly allocated
            // guest memory already being zero, but running after `load_kernel()` remains
            // correct.)
            Self::setup_pvclock(&mut vmem)?;

            #[cfg(feature = "profile-time")]
            perf_timings.set_vcpu_reset(vcpu_reset_start.elapsed().as_micros() as u64);

            // Phase: Finalize guest RAM mapping.
            // Map the loaded image regions (kernel/initrd/RAMFS) into the partition eagerly and
            // leave anonymous gaps to be mapped lazily on first access. This keeps VM creation
            // time on WHP independent of the configured guest memory size, mirroring the Linux
            // `mmap(MAP_NORESERVE)` behavior even when RAMFS is placed near the top of memory.
            let mut eager_ranges: Vec<(usize, usize)> = Vec::new();
            if let Some(region) = guest.kernel_region() {
                eager_ranges.push(region);
            }
            if let Some(region) = guest.initrd_region() {
                eager_ranges.push(region);
            }
            if let Some(region) = ramfs_region {
                eager_ranges.push(region);
            }
            vmem.finalize_lazy_mapping(&eager_ranges)?;

            // Phase: EPT pre-population.
            // Pre-populate EPT entries for the kernel and ramfs regions so the hypervisor resolves
            // SLAT entries from the host side before guest execution.  This avoids costly EPT
            // violations during WHvRunVirtualProcessor.
            #[cfg(feature = "profile-time")]
            let ept_populate_start: Instant = Instant::now();

            vmem.populate_ept(&guest.ept_populate_ranges()?)?;

            // Pre-populate file-backed initrd pages with read-only access. This brings the
            // pages into the working set and SLAT without triggering copy-on-write on the
            // PAGE_WRITECOPY mapping.
            let read_ranges: Vec<(u64, u64)> = guest.ept_populate_read_ranges();
            if !read_ranges.is_empty() {
                vmem.populate_ept_read(&read_ranges)?;
            }

            #[cfg(feature = "profile-time")]
            perf_timings.set_ept_populate(ept_populate_start.elapsed().as_micros() as u64);

            // Reset the vCPU to its boot state. For 64-bit guests this programs the long-mode
            // control/segment registers and the GDTR; the hypervisor consults guest memory (boot
            // page tables and the GDT) while applying that state, so this must run *after* the EPT
            // has been populated. The 32-bit reset only touches CS and the general-purpose
            // registers, so the ordering is immaterial there.
            guest.reset(&mut vmem, &mut vcpu)?;

            Arc::new(Mutex::new(guest))
        };

        let partition_handle = partition.handle();
        let run_state: Arc<RunState> = Arc::new(RunState::new());
        let timer: Arc<std::sync::Mutex<timer::Timer>> =
            Arc::new(std::sync::Mutex::new(timer::Timer::new(partition_handle, run_state.clone())));
        let vmem: Arc<Mutex<VirtualMemory>> = Arc::new(Mutex::new(vmem));
        let vcpu: Arc<Mutex<VirtualProcessor>> = Arc::new(Mutex::new(vcpu));

        let ikc_notifier: IkcNotifier = IkcNotifier::new(partition_handle);
        let shutdown_flag: Arc<AtomicBool> = Arc::new(AtomicBool::new(false));

        let emulator: Emulator =
            Emulator::new(guest.clone(), vmem.clone(), args.input, args.output, args.stderr)?;

        Ok(Self {
            guest,
            vmem,
            vcpu,
            ikc_notifier,
            partition_handle,
            timer,
            shutdown_flag,
            run_state,
            inner: Arc::new(Mutex::new(InteriorWhpHandle {
                _partition: partition,
                emulator,
                control_rx: args.control_rx,
                control_tx: args.control_tx,
                kernel_filename: args.kernel_filename,
                skip_next_snapshot: false,
                snapshot_allowed,
            })),
            pvclock_time_base_ns: Arc::new(std::sync::atomic::AtomicU64::new(0)),
            pvclock_last_written_ns: Arc::new(std::sync::atomic::AtomicU64::new(0)),
            #[cfg(feature = "profile-time")]
            perf_timings,
            guest_profiler: None,
        })
    }

    pub fn spawn(mut self) -> tokio::task::JoinHandle<Result<u16>> {
        task::spawn_blocking(move || {
            warn!("VMM spawn_blocking: calling run()");
            let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| self.run()));
            warn!("VMM spawn_blocking: run() returned (is_ok={})", result.is_ok());
            match result {
                Ok(inner) => inner,
                Err(panic_info) => {
                    let msg = format!("VMM panicked: {:?}", panic_info);
                    error!("{msg}");
                    Err(anyhow::anyhow!(msg))
                },
            }
        })
    }

    ///
    /// # Description
    ///
    /// Runs the virtual machine.
    ///
    /// # Returns
    ///
    /// Upon successful completion, this method returns the exit status of the virtual machine.
    /// Otherwise, it returns an error.
    ///
    pub fn run(&mut self) -> Result<u16> {
        trace!("run()");

        // Reset shutdown flag from any previous runs.
        self.shutdown_flag.store(false, Ordering::SeqCst);

        // Publish the vCPU thread ID only after the shutdown flag is initialized. Otherwise an
        // early request from the orchestrator could be overwritten by the reset above.
        let thread_id: u64 =
            unsafe { windows::Win32::System::Threading::GetCurrentThreadId() as u64 };
        Handle::current().block_on(self.send_tid(thread_id))?;

        let loop_start: Instant = Instant::now();

        // Throttle pvclock updates to once per millisecond instead of every
        // VMM loop iteration. This avoids unnecessary mutex acquisition and
        // memory writes on fast-path exits (HLT, Interrupted, legacy PMIO).
        let mut last_pvclock_update: Instant = Instant::now();
        const PVCLOCK_UPDATE_INTERVAL: std::time::Duration = std::time::Duration::from_millis(1);

        // Pvclock: VMM-driven system_time updates.
        // Version starts at 2 (set by setup_pvclock). Each update does +1
        // (odd = writing) then +1 (even = stable).
        let mut pvclock_version: u32 = 2;

        // The LAPIC periodic timer runs entirely inside the WHP LAPIC
        // emulator, configured by the guest kernel during boot via
        // PIT-based calibration (1kHz, zero VM exits for delivery).
        //
        // Pvclock updates are driven by a host timer. The guest
        // interpolates between updates using LAPIC timer tick counts
        // (1 kHz) for ~1 ms accuracy with zero VM exits per time read.
        //
        // Defer the pvclock timer until the kernel explicitly signals
        // boot completion via DEFAULT_VMM_BOOT_COMPLETE_CMD on the VMM
        // port. Starting the timer earlier causes
        // WHvCancelRunVirtualProcessor to interrupt the very first
        // WHvRunVirtualProcessor call, which carries a heavy one-time
        // partition-setup cost inside WHP. Deferring avoids those
        // unnecessary cancel-induced VM exits during boot while still
        // providing pvclock updates once user-space is running.
        let mut timer_started: bool = false;

        // Guest profiler: start a dedicated cancel timer for periodic sampling.
        // Deferred slightly to avoid interfering with the first VP entry.
        // Uses a dedicated `AtomicBool` flag so only profiler-driven cancels
        // trigger sampling (not pvclock or other `Interrupted` exits).
        let profiler_sample_pending = Arc::new(AtomicBool::new(false));
        let profiler_stop = Arc::new(AtomicBool::new(false));
        let mut profiler_thread: Option<std::thread::JoinHandle<()>> = None;
        let mut profiler_timer_started: bool = false;
        /// Number of VM exits to skip before starting the profiler timer,
        /// avoiding interference with the initial vCPU entry sequence.
        const PROFILER_START_DELAY_EXITS: u64 = 5;
        let mut exit_count: u64 = 0;

        // Per-exit-type counters for profiling.
        #[cfg(feature = "profile-time")]
        let mut exit_pmio_out_fast: u64 = 0;
        #[cfg(feature = "profile-time")]
        let mut exit_pmio_in_fast: u64 = 0;
        #[cfg(feature = "profile-time")]
        let mut exit_pmio_slow: u64 = 0;
        #[cfg(feature = "profile-time")]
        let mut exit_interrupted: u64 = 0;
        #[cfg(feature = "profile-time")]
        let mut exit_halt: u64 = 0;
        #[cfg(feature = "profile-time")]
        let mut exit_mmio: u64 = 0;
        #[cfg(feature = "profile-time")]
        let mut exit_intwin: u64 = 0;

        // PIT channel 2 state for LAPIC timer calibration. The guest
        // programs PIT ch2 in one-shot mode and polls port 0x61 bit 5
        // to detect when the countdown expires.
        let mut pit_ch2: PitCh2State = PitCh2State::new();

        // Accumulate guest execution time (inside WHvRunVirtualProcessor).
        #[cfg(feature = "profile-time")]
        let mut guest_time_acc_us: u64 = 0;

        let result = loop {
            // Check shutdown flag.
            if self.shutdown_flag.load(Ordering::SeqCst) {
                let exit_status: u16 = 0;
                warn!("VMM exit: SHUTDOWN flag (elapsed={:?})", loop_start.elapsed());
                Handle::current().block_on(self.handle_shutdown(exit_status));
                break Ok(exit_status);
            }

            // Update pvclock at most once per millisecond to avoid
            // excessive mutex acquisition and memory writes on fast-path
            // exits. The guest kernel tolerates stale system_time values
            // within a few milliseconds.
            if last_pvclock_update.elapsed() >= PVCLOCK_UPDATE_INTERVAL {
                let pvclock_base: u64 = self
                    .pvclock_time_base_ns
                    .load(std::sync::atomic::Ordering::Relaxed);
                let system_time_ns: u64 = pvclock_base + loop_start.elapsed().as_nanos() as u64;
                Self::update_pvclock(
                    &mut self.vmem.blocking_lock(),
                    &mut pvclock_version,
                    system_time_ns,
                );
                self.pvclock_last_written_ns
                    .store(system_time_ns, std::sync::atomic::Ordering::Relaxed);
                last_pvclock_update = Instant::now();
            }

            // Consume pending IKC notification.  to prevent re-delivery on the next loop iteration.
            let _ = self.ikc_notifier.take_pending();

            // Start profiler cancel timer after a few exits to avoid the first-entry cost.
            exit_count += 1;
            if self.guest_profiler.is_some()
                && !profiler_timer_started
                && exit_count > PROFILER_START_DELAY_EXITS
            {
                let stop = profiler_stop.clone();
                let sample_pending = profiler_sample_pending.clone();
                let partition = self.partition_handle;
                let run_state: Arc<RunState> = self.run_state.clone();
                profiler_thread = Some(std::thread::spawn(move || {
                    unsafe { timer::timeBeginPeriod(1) };
                    // Target ~1 kHz sampling. Actual rate is approximate due to
                    // Windows scheduler granularity, even with timeBeginPeriod(1).
                    let period = std::time::Duration::from_micros(1000);
                    while !stop.load(Ordering::Relaxed) {
                        std::thread::sleep(period);
                        if stop.load(Ordering::Relaxed) {
                            break;
                        }
                        run_state.cancel_if_pending(|| {
                            sample_pending.store(true, Ordering::Release);
                            unsafe {
                                let _ = windows::Win32::System::Hypervisor::WHvCancelRunVirtualProcessor(
                                    partition, 0, 0,
                                );
                            }
                        });
                    }
                    unsafe { timer::timeEndPeriod(1) };
                }));
                profiler_timer_started = true;
            }

            let (exit_context, profile_regs) = {
                let mut locked_vcpu: MutexGuard<'_, VirtualProcessor> = self.vcpu.blocking_lock();
                // Exit if the vCPU is no longer online.
                if !locked_vcpu.is_online() {
                    warn!(
                        "VMM exit: vCPU offline (exit_status={}, elapsed={:?})",
                        locked_vcpu.exit_status(),
                        loop_start.elapsed()
                    );
                    break Ok(locked_vcpu.exit_status());
                }

                // Publish intent before the final shutdown check. If shutdown races with this
                // boundary, either this check observes it or the shutdown callback observes
                // `run_state` as pending and keeps canceling until the WHP call returns.
                let run_pending_guard: RunPendingGuard<'_> =
                    RunPendingGuard::new(self.run_state.as_ref());
                if self.shutdown_flag.load(Ordering::SeqCst) {
                    drop(run_pending_guard);
                    drop(locked_vcpu);
                    let exit_status: u16 = 0;
                    warn!("VMM exit: SHUTDOWN flag before vCPU entry");
                    Handle::current().block_on(self.handle_shutdown(exit_status));
                    break Ok(exit_status);
                }
                #[cfg(feature = "profile-time")]
                let run_start: Instant = Instant::now();

                let ctx: VirtualProcessorExitContext = locked_vcpu.run();
                drop(run_pending_guard);

                #[cfg(feature = "profile-time")]
                {
                    guest_time_acc_us += run_start.elapsed().as_micros() as u64;
                }

                // Guest profiler: read registers only when our profiler timer fired.
                let regs = if self.guest_profiler.is_some()
                    && profiler_sample_pending.swap(false, Ordering::Acquire)
                    && matches!(ctx.reason_ref(), VirtualProcessorExitReasonRef::Interrupted)
                {
                    locked_vcpu.get_profile_regs().ok()
                } else {
                    None
                };

                (ctx, regs)
            };

            // Guest profiler: capture sample after vcpu lock is released.
            //
            // Safety: The vCPU is stopped at this point — WHvRunVirtualProcessor
            // returned with an Interrupted exit, and the next run() call hasn't
            // been issued yet. Guest memory (page tables, stack) cannot change
            // while the vCPU is not executing, so reading vmem here is safe.
            if let (Some(profiler_samples), Some((eip, ebp, cr3))) =
                (&self.guest_profiler, profile_regs)
            {
                let vmem_guard = self.vmem.blocking_lock();
                crate::guest_profiler::GuestProfiler::capture_sample(
                    profiler_samples,
                    vmem_guard.get_raw_ptr(),
                    vmem_guard.get_size(),
                    eip,
                    ebp,
                    cr3,
                );
            }

            // Parse exit reason.
            match exit_context.reason_ref() {
                // The guest requested to access an I/O port.
                VirtualProcessorExitReasonRef::PmioAccess(access) => {
                    // Fast-path: handle legacy hardware ports inline.
                    if let PmioAccess::PmioOut(port, data, _width) = access {
                        match *port {
                            // PIT control register: track channel 2 programming.
                            0x43 => {
                                #[cfg(feature = "profile-time")]
                                {
                                    exit_pmio_out_fast += 1;
                                }
                                pit_ch2.handle_ctrl_write(*data as u8);
                                continue;
                            },
                            // PIT channel 2 data register.
                            0x42 => {
                                #[cfg(feature = "profile-time")]
                                {
                                    exit_pmio_out_fast += 1;
                                }
                                pit_ch2.handle_data_write(*data as u8);
                                continue;
                            },
                            // Speaker/gate control: track gate enable.
                            0x61 => {
                                #[cfg(feature = "profile-time")]
                                {
                                    exit_pmio_out_fast += 1;
                                }
                                pit_ch2.handle_speaker_write(*data as u8);
                                continue;
                            },
                            // PIC, PIT ch0/ch1, IMCR, CMOS, serial: no-op.
                            // PIT channel 0/1 are intentionally not emulated:
                            // the kernel programs them during legacy boot, but
                            // the periodic timer interrupt is generated by the
                            // WHP LAPIC emulator, not the 8254. Only channel 2
                            // is tracked (above) for calibration fallback.
                            0x20
                            | 0x21
                            | 0xA0
                            | 0xA1
                            | 0x22
                            | 0x23
                            | 0x40
                            | 0x41
                            | 0x70
                            | 0x71
                            | 0x3F8..=0x3FF => {
                                #[cfg(feature = "profile-time")]
                                {
                                    exit_pmio_out_fast += 1;
                                }
                                continue;
                            },
                            _ => {},
                        }
                    }
                    if let PmioAccess::PmioIn(port, _data) = access {
                        match *port {
                            // PIT channel 2 output: return gate/OUT2 status.
                            0x61 => {
                                #[cfg(feature = "profile-time")]
                                {
                                    exit_pmio_in_fast += 1;
                                }
                                let value: u8 = pit_ch2.read_speaker();
                                self.vcpu.blocking_lock().set_rip_and_rax(value as u64);
                                continue;
                            },
                            // Other legacy ports: return zero.
                            0x20
                            | 0x21
                            | 0x22
                            | 0x23
                            | 0xA0
                            | 0xA1
                            | 0x40..=0x43
                            | 0x70
                            | 0x71
                            | 0x3F8..=0x3FF
                            | 0xCF8
                            | 0xCFC..=0xCFF => {
                                #[cfg(feature = "profile-time")]
                                {
                                    exit_pmio_in_fast += 1;
                                }
                                self.vcpu.blocking_lock().set_rip_and_rax(0);
                                continue;
                            },
                            _ => {},
                        }
                    }

                    // Slow path: application-level I/O (stdout, stdin, VMM port).
                    #[cfg(feature = "profile-time")]
                    {
                        exit_pmio_slow += 1;
                    }
                    // Flush any deferred RIP advance for reads that reach the slow path.
                    self.vcpu.blocking_lock().flush_pending_rip();

                    let exit_status: Option<u16> = match self
                        .inner
                        .blocking_lock()
                        .emulator
                        .handle_pmio_access(access)
                    {
                        Ok(status) => status,
                        Err(e) => {
                            error!("VMM exit: PMIO access error (error={e:?})",);
                            break Err(e);
                        },
                    };
                    if let Some(exit_status) = exit_status {
                        if exit_status == ::config::microvm::DEFAULT_VMM_BOOT_COMPLETE_CMD {
                            // The kernel signals that boot is complete and user-space is about to
                            // start. Start the pvclock host timer now.
                            if !timer_started {
                                match self.timer.lock() {
                                    Ok(mut locked_timer) => {
                                        locked_timer.start(PVCLOCK_TIMER_PERIOD_US);
                                        trace!("pvclock timer started");
                                        timer_started = true;
                                    },
                                    Err(e) => {
                                        error!(
                                            "Failed to acquire timer lock to start pvclock: {e:?}"
                                        );
                                        break Err(anyhow::anyhow!(
                                            "Failed to acquire timer lock to start pvclock: {e:?}"
                                        ));
                                    },
                                }
                            }
                        } else if exit_status == ::config::microvm::DEFAULT_VMM_SNAPSHOT_CMD {
                            // One-shot "save and exit" flow: once the snapshot files are
                            // durable on disk, shut the VM down with exit code 0 so the
                            // standalone daemon returns to its caller instead of running the
                            // guest on. `handle_snapshot()` returns `false` for the OUT that is
                            // absorbed via `skip_next_snapshot` after a restore; in that case
                            // keep running the restored guest.
                            let took_snapshot: bool =
                                match Handle::current().block_on(self.handle_snapshot()) {
                                    Ok(took) => took,
                                    Err(e) => {
                                        error!("VMM exit: snapshot error (error={e:?})");
                                        break Err(e);
                                    },
                                };
                            if took_snapshot {
                                let exit_status: u16 = 0;
                                Handle::current().block_on(self.handle_shutdown(exit_status));
                                break Ok(exit_status);
                            }
                        } else if exit_status != ::config::microvm::DEFAULT_VMM_PAUSE_CMD {
                            warn!(
                                "VMM exit: PMIO shutdown (exit_status={exit_status}, elapsed={:?})",
                                loop_start.elapsed()
                            );
                            Handle::current().block_on(self.handle_shutdown(exit_status));
                            break Ok(exit_status);
                        } else {
                            if let Err(e) = Handle::current().block_on(self.handle_pause()) {
                                error!("VMM exit: pause error (error={e:?})");
                                break Err(e);
                            }
                            trace!("VMM resumed");
                        }
                    }
                },

                // HLT: with LAPIC emulation enabled, HLT is handled internally by the LAPIC and
                // shouldn't cause VM exits.  If it does, log and re-enter the vCPU loop.
                VirtualProcessorExitReasonRef::Halt => {
                    #[cfg(feature = "profile-time")]
                    {
                        exit_halt += 1;
                    }
                    warn!("VMM exit: HLT");
                    continue;
                },

                // The vCPU was canceled (WHvCancelRunVP from the host
                // timer thread). Re-enter after pvclock update
                // (handled at top of loop).
                VirtualProcessorExitReasonRef::Interrupted => {
                    #[cfg(feature = "profile-time")]
                    {
                        exit_interrupted += 1;
                    }
                    continue;
                },

                // InterruptWindow: IF just became 1. With LAPIC-based
                // delivery, interrupts are handled by the LAPIC emulator.
                VirtualProcessorExitReasonRef::InterruptWindow => {
                    #[cfg(feature = "profile-time")]
                    {
                        exit_intwin += 1;
                    }
                    continue;
                },

                // Virtual machine exited due to an unknown reason.
                VirtualProcessorExitReasonRef::Unknown => {
                    warn!("VMM exit: Unknown exit reason (elapsed={:?})", loop_start.elapsed());
                    break Ok(ErrorCode::IllegalByteSequence.into());
                },

                // Guest accessed a memory-mapped address.
                VirtualProcessorExitReasonRef::MmioAccess(gpa) => {
                    #[cfg(feature = "profile-time")]
                    {
                        exit_mmio += 1;
                    }

                    // Lazy guest-RAM mapping: anonymous RAM beyond the loaded image is committed
                    // host-side but not registered with the partition at creation time (see
                    // `VirtualMemory::finalize_lazy_mapping`). The first guest access to such a
                    // page faults out with an unmapped-GPA memory-access exit; map the containing
                    // chunk on demand and re-execute the faulting instruction. RIP is left
                    // unchanged so the access is retried once the mapping is in place.
                    //
                    // The guard is released before matching so the abort path can re-borrow
                    // `self` for shutdown.
                    let mapping_result: Result<bool> =
                        self.vmem.blocking_lock().ensure_ram_mapped(gpa);
                    match mapping_result {
                        Ok(true) => continue,
                        Ok(false) => {},
                        Err(e) => {
                            error!(
                                "VMM MMIO exit: failed to map guest RAM at GPA {gpa:#010x} \
                                 (error={e:?})"
                            );
                            let exit_status: u16 = ErrorCode::BadAddress.into();
                            Handle::current().block_on(self.handle_shutdown(exit_status));
                            break Ok(exit_status);
                        },
                    }

                    // Check if access falls within the LAPIC page.
                    let page_gpa: u64 = gpa & !(::arch::mem::PAGE_SIZE as u64 - 1);
                    if page_gpa == ::config::microvm::DEFAULT_LAPIC_BASE as u64 {
                        trace!("VMM MMIO exit: LAPIC access at GPA {gpa:#010x}, retrying");
                        continue;
                    }

                    // All other MMIO accesses are unexpected. Terminate execution.
                    error!("VMM MMIO exit: unexpected GPA {gpa:#010x}, aborting");
                    let exit_status: u16 = ErrorCode::BadAddress.into();
                    Handle::current().block_on(self.handle_shutdown(exit_status));
                    break Ok(exit_status);
                },
            }
        };

        // Drain any guest console output still buffered by the asynchronous console writer to the
        // host sink before returning, so the final bytes the guest emitted (for example the
        // shutdown magic string) are not stranded when the VMM thread unwinds. The wait is bounded
        // and runs off the guest's execution path, since the run loop has already exited.
        self.inner.blocking_lock().emulator.flush_console();

        self.timer.lock().unwrap().stop();

        // Stop profiler timer if running.
        profiler_stop.store(true, Ordering::Relaxed);
        if let Some(t) = profiler_thread.take() {
            let _ = t.join();
        }

        // Record guest vs exit-handling time breakdown.
        #[cfg(feature = "profile-time")]
        {
            let loop_total_us: u64 = loop_start.elapsed().as_micros() as u64;
            self.perf_timings.set_guest_exec(guest_time_acc_us);
            self.perf_timings
                .set_exit_handling(loop_total_us.saturating_sub(guest_time_acc_us));
            self.perf_timings.set_exit_count_total(exit_count);
            self.perf_timings
                .set_exit_count_pmio_out_fast(exit_pmio_out_fast);
            self.perf_timings
                .set_exit_count_pmio_in_fast(exit_pmio_in_fast);
            self.perf_timings.set_exit_count_pmio_slow(exit_pmio_slow);
            self.perf_timings
                .set_exit_count_interrupted(exit_interrupted);
            self.perf_timings.set_exit_count_halt(exit_halt);
            self.perf_timings.set_exit_count_mmio(exit_mmio);
            self.perf_timings.set_exit_count_intwin(exit_intwin);
        }

        warn!("VMM run loop finished (result={result:?}, elapsed={:?})", loop_start.elapsed());
        result
    }

    ///
    /// # Description
    ///
    /// Returns a reference to the virtual memory of the target virtual machine.
    ///
    pub fn vmem(&self) -> Arc<Mutex<VirtualMemory>> {
        self.vmem.clone()
    }

    ///
    /// # Description
    ///
    /// Returns a reference to the guest of the virtual machine.
    ///
    pub fn guest(&self) -> Arc<Mutex<Guest>> {
        self.guest.clone()
    }

    /// Enables guest stack profiling. Returns the profiler handle for
    /// reading samples after VM exit.
    pub fn enable_guest_profiler(&mut self) -> crate::guest_profiler::GuestProfiler {
        let profiler = crate::guest_profiler::GuestProfiler::new(
            crate::guest_profiler::DEFAULT_SAMPLE_CAPACITY,
        );
        self.guest_profiler = Some(profiler.handle());
        profiler
    }

    /// Returns a clone of the IKC notifier for use by the memory thread.
    pub fn ikc_notifier(&self) -> IkcNotifier {
        self.ikc_notifier.clone()
    }

    ///
    /// # Description
    ///
    /// Derives the snapshot file paths from the kernel filename.
    ///
    /// # Parameters
    ///
    /// - `filepath`: Path to the kernel file whose stem is used to build snapshot filenames.
    ///
    /// # Returns
    ///
    /// Upon successful completion, this method returns a tuple containing the virtual memory
    /// snapshot path and the WHP state snapshot path.
    ///
    fn make_snapshot_paths(filepath: &str) -> (PathBuf, PathBuf) {
        let snapshots_dir: &Path = Path::new("snapshots");
        let stem: &OsStr = Path::new(filepath)
            .file_stem()
            .unwrap_or(OsStr::new("default"));
        let vmem_filepath: PathBuf = snapshots_dir.join(stem).with_extension("vmem");
        let whp_filepath: PathBuf = snapshots_dir.join(stem).with_extension("whp.cbor");
        (vmem_filepath, whp_filepath)
    }

    ///
    /// # Description
    ///
    /// Saves the virtual memory and WHP state to snapshot files.
    ///
    /// # Parameters
    ///
    /// - `filepath`: Path to the kernel file whose stem is used to build snapshot filenames.
    ///
    /// # Returns
    ///
    /// Upon successful completion, an empty result is returned. Otherwise, it returns an error.
    ///
    pub async fn create_snapshot(&self, filepath: String) -> Result<()> {
        #[cfg(feature = "profile-time")]
        let snapshot_creation_start: Instant = Instant::now();

        let (vmem_filepath, whp_filepath) = Self::make_snapshot_paths(&filepath);

        // Ensure snapshots directory exists.
        if let Some(parent) = vmem_filepath.parent() {
            std::fs::create_dir_all(parent)?;
        }

        // Save guest memory (dense format: raw image for COW-mapped restore).
        if let Err(e) = self.vmem.lock().await.save_snapshot_dense(&vmem_filepath) {
            let reason: String = format!("failed creating virtual memory snapshot (error={e:?})");
            error!("create_snapshot(): {reason}");
            anyhow::bail!(reason)
        }

        // Capture the last pvclock system_time written to the guest so restore can
        // use it as the time base, ensuring monotonically advancing guest time.
        let pvclock_time_ns: u64 = self
            .pvclock_last_written_ns
            .load(std::sync::atomic::Ordering::Relaxed);

        // Save vCPU, guest state, and pvclock time.
        let whp_snapshot = WhpSnapshot {
            guest_state: self.guest.lock().await.save_state()?,
            vcpu_state: self.vcpu.lock().await.save_state()?,
            pvclock_time_ns,
        };

        let mut file: File = File::create(&whp_filepath)?;
        match ::serde_cbor::to_vec(&whp_snapshot) {
            Ok(buffer) => {
                file.write_all(&buffer)?;
                trace!(
                    "create_snapshot(): wrote {} bytes to WHP snapshot file \
                     (pvclock_ns={pvclock_time_ns})",
                    buffer.len()
                );
                #[cfg(feature = "profile-time")]
                {
                    #![allow(clippy::cast_possible_truncation)]
                    let elapsed_us: u64 = snapshot_creation_start.elapsed().as_micros() as u64;
                    self.perf_timings.set_snapshot_creation(elapsed_us);
                }
                Ok(())
            },
            Err(e) => {
                let reason: String = format!("failed serializing WHP snapshot (error={e:?})");
                error!("create_snapshot(): {reason}");
                anyhow::bail!(reason)
            },
        }
    }

    ///
    /// # Description
    ///
    /// Loads the virtual memory and WHP state from snapshot files.
    ///
    /// # Parameters
    ///
    /// - `filepath`: Path to the kernel file whose stem is used to locate snapshot filenames.
    ///
    /// # Returns
    ///
    /// Upon successful completion, an empty result is returned. Otherwise, it returns an error.
    ///
    pub async fn load_snapshot(&self, filepath: String) -> Result<()> {
        let (vmem_filepath, whp_filepath) = Self::make_snapshot_paths(&filepath);

        // Load guest memory (COW-mapped from dense snapshot file).
        if let Err(e) = self.vmem.lock().await.load_snapshot_cow(&vmem_filepath) {
            let reason: String = format!("failed loading virtual memory snapshot (error={e:?})");
            error!("load_snapshot(): {reason}");
            anyhow::bail!(reason)
        }

        // Load vCPU and guest state.
        let mut file: File = match File::open(&whp_filepath) {
            Ok(f) => f,
            Err(e) => {
                let reason: String = format!("failed opening WHP snapshot file (error={e:?})");
                error!("load_snapshot(): {reason}");
                anyhow::bail!(reason)
            },
        };

        let whp_snapshot: WhpSnapshot =
            match ::serde_cbor::from_reader::<WhpSnapshot, &mut File>(&mut file) {
                Ok(snapshot) => snapshot,
                Err(e) => {
                    let reason: String = format!("failed decoding WHP snapshot file (error={e:?})");
                    error!("load_snapshot(): {reason}");
                    anyhow::bail!(reason)
                },
            };

        // Restore guest state.
        self.guest
            .lock()
            .await
            .restore_state(&whp_snapshot.guest_state)?;

        // Restore vCPU state (registers + LAPIC).
        self.vcpu
            .lock()
            .await
            .load_state(&whp_snapshot.vcpu_state)?;

        // Restore pvclock time base so the run loop resumes with monotonically advancing
        // time: system_time = snapshot_time + new_loop_elapsed.
        let restored_time_ns: u64 = whp_snapshot.pvclock_time_ns;
        self.pvclock_time_base_ns
            .store(restored_time_ns, std::sync::atomic::Ordering::Relaxed);
        self.pvclock_last_written_ns
            .store(restored_time_ns, std::sync::atomic::Ordering::Relaxed);
        trace!("load_snapshot(): restored pvclock_time_base_ns={restored_time_ns}");

        Ok(())
    }

    ///
    /// # Description
    ///
    /// Requests a graceful shutdown of the vCPU run loop from any thread.
    /// Sets the shared shutdown flag and cancels the current
    /// `WHvRunVirtualProcessor` call so the VMM loop can observe the flag
    /// on its next iteration.
    ///
    pub fn request_shutdown(&self, _vcpu_tid: u64) {
        self.shutdown_flag.store(true, Ordering::SeqCst);

        if self.run_state.is_pending() {
            let inner: Arc<Mutex<InteriorWhpHandle>> = self.inner.clone();
            let partition_handle = self.partition_handle;
            let run_state: Arc<RunState> = self.run_state.clone();
            let vcpu: Arc<Mutex<VirtualProcessor>> = self.vcpu.clone();
            let _cancel_worker: std::thread::JoinHandle<()> = std::thread::spawn(move || {
                let mut error_logged: bool = false;
                cancel_while_run_pending(run_state.as_ref(), || {
                    // SAFETY: `inner` and `vcpu` keep the WHP partition and virtual processor
                    // alive until this worker exits.
                    unsafe {
                        if let Err(error) =
                            windows::Win32::System::Hypervisor::WHvCancelRunVirtualProcessor(
                                partition_handle,
                                0,
                                0,
                            )
                            && !error_logged
                        {
                            warn!("request_shutdown(): failed to cancel vCPU (error={error:?})");
                            error_logged = true;
                        }
                    }
                });
                drop(vcpu);
                drop(inner);
            });
        }
    }

    ///
    /// # Description
    ///
    /// Sends the vCPU thread's tid to the main thread.
    ///
    async fn send_tid(&self, tid: u64) -> Result<()> {
        Ok(self
            .inner
            .lock()
            .await
            .control_tx
            .send(VcpuControlResponse::Tid(tid))
            .await?)
    }

    /// Handles a guest-initiated snapshot request from the VMM run loop.
    ///
    /// WHP advances RIP before delivering port-I/O exits, so the saved
    /// state already points past the `out` instruction. Unlike KVM, no
    /// `skip_next_snapshot` guard is needed to prevent re-triggering.
    async fn handle_snapshot(&self) -> Result<bool> {
        // Scope the lock to avoid deadlock: `create_snapshot` re-acquires `self.inner`.
        // Safety: no concurrent snapshot requests can race here because snapshot is triggered
        // by a single vCPU VMEXIT which is processed sequentially on the VMM run loop.
        let kernel_filename: String = {
            let mut locked_inner: MutexGuard<'_, InteriorWhpHandle> = self.inner.lock().await;
            if locked_inner.skip_next_snapshot {
                trace!("handle_snapshot(): skipping snapshot (restored from snapshot)");
                locked_inner.skip_next_snapshot = false;
                return Ok(false);
            }
            if !locked_inner.snapshot_allowed {
                error!("handle_snapshot(): snapshot refused (not enabled or already consumed)");
                anyhow::bail!(
                    "snapshot refused: not enabled via kernel option or already consumed"
                );
            }
            locked_inner.kernel_filename.clone()
        };
        match self.create_snapshot(kernel_filename).await {
            Ok(()) => {
                // Consume the one-shot permission only after a successful snapshot.
                self.inner.lock().await.snapshot_allowed = false;
                trace!("handle_snapshot(): snapshot created successfully");
                Ok(true)
            },
            Err(error) => {
                error!("handle_snapshot(): failed to create snapshot: {error:?}");
                Err(error)
            },
        }
    }

    /// Creates a snapshot and sends the result to the orchestrator.
    async fn handle_create_snapshot(&self, filepath: String) -> Result<()> {
        match self.create_snapshot(filepath).await {
            Ok(()) => {
                self.inner
                    .lock()
                    .await
                    .control_tx
                    .send(VcpuControlResponse::SnapshotCreated)
                    .await?;
                Ok(())
            },
            Err(error) => {
                self.inner
                    .lock()
                    .await
                    .control_tx
                    .send(VcpuControlResponse::SnapshotCreationFailed)
                    .await?;
                error!("handle_create_snapshot(): failed to create snapshot: {error:?}");
                Err(error)
            },
        }
    }

    ///
    /// # Description
    ///
    /// Acknowledges a pause request and waits for the next command.
    ///
    async fn handle_pause(&mut self) -> Result<()> {
        self.inner
            .lock()
            .await
            .control_tx
            .send(VcpuControlResponse::Paused)
            .await?;

        match self.inner.lock().await.control_rx.recv().await {
            Some(VcpuControlCommand::Resume) => Ok(()),
            Some(VcpuControlCommand::CreateSnapshot(filepath)) => {
                self.handle_create_snapshot(filepath).await?;
                Ok(())
            },
            None => {
                let reason: String = "the vmm has disconnected".to_string();
                error!("run(): {reason}");
                anyhow::bail!(reason)
            },
        }
    }

    ///
    /// # Description
    ///
    /// Helper method to poweroff the vCPU with a given exit status, and send a shutdown message to
    /// the orchestrator thread.
    ///
    async fn handle_shutdown(&mut self, exit_status: u16) {
        // Mark the IKC notifier as shut down so that any pending or future notify() calls from
        // the memory thread will skip the WHvRequestInterrupt API call. This prevents
        // STATUS_ACCESS_VIOLATION crashes after the vCPU is no longer running.
        self.ikc_notifier.mark_shutdown();

        // Power-off vCPU.
        self.vcpu.lock().await.poweroff(exit_status);

        // Send message to orchestrator thread.
        match self
            .inner
            .lock()
            .await
            .control_tx
            .send(VcpuControlResponse::Shutdown)
            .await
        {
            Ok(()) => {
                trace!("handle_shutdown(): shutdown notification sent to orchestrator");
            },
            Err(error) => {
                warn!("handle_shutdown(): failed to notify orchestrator thread (error={error:?})");
            },
        }
    }

    /// Populates the pvclock shared memory page so the kernel reads accurate
    /// wall-clock time without relying on TSC.
    ///
    /// The page at `DEFAULT_PVCLOCK_PAGE` (GPA 0x1000) uses the KVM pvclock
    /// format (`KvmPvclockVcpuTimeInfo`). On KVM this is filled by the
    /// hypervisor itself; on WHP we write it from the VMM.
    ///
    /// **Strategy**: Set `tsc_to_system_mul = 0` so the TSC delta contributes
    /// nothing. The VMM periodically updates `system_time` directly from the
    /// host clock (see [`update_pvclock`]). This avoids depending on the
    /// guest's `rdtsc` matching the host's TSC — which is unreliable on WHP.
    fn setup_pvclock(vmem: &mut VirtualMemory) -> Result<()> {
        use std::time::{
            SystemTime,
            UNIX_EPOCH,
        };

        // Build the KvmPvclockVcpuTimeInfo structure (32 bytes).
        //   [0..4]   version: u32           (2 = valid, even)
        //   [4..8]   _pad0: u32             (0)
        //   [8..16]  tsc_timestamp: u64     (unused, 0)
        //   [16..24] system_time: u64       (ns, updated by VMM)
        //   [24..28] tsc_to_system_mul: u32 (0 = TSC not used)
        //   [28]     tsc_shift: i8          (0)
        //   [29]     flags: u8              (0x01 = TSC_STABLE)
        //   [30..32] _pad: [u8; 2]
        let mut data = [0u8; 32];
        // Version 2 = pvclock enabled (VMM-driven system_time updates).
        let pvclock_version: u32 = 2;
        data[0..4].copy_from_slice(&pvclock_version.to_le_bytes());
        // tsc_timestamp = 0, system_time = 0, mul = 0, shift = 0
        data[29] = 0x01; // TSC_STABLE

        let pvclock_gpa = ::config::microvm::DEFAULT_PVCLOCK_PAGE as u64;
        vmem.write_bytes(pvclock_gpa, &data)?;

        // Write boot time (UTC nanoseconds since Unix epoch) at offset 0x20.
        let boot_time_ns: u64 = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos() as u64;
        let boot_offset = pvclock_gpa + ::config::microvm::PVCLOCK_BOOT_TIME_NS_OFFSET as u64;
        vmem.write_bytes(boot_offset, &boot_time_ns.to_le_bytes())?;

        trace!("pvclock: VMM-driven mode (mul=0), boot_ns={boot_time_ns}");

        Ok(())
    }

    /// Updates the pvclock page's `system_time` field via the seqlock protocol.
    ///
    /// The kernel's seqlock reader retries when it sees an odd version, so
    /// the update sequence is: version→odd, write system_time, version→even.
    fn update_pvclock(vmem: &mut VirtualMemory, pvclock_version: &mut u32, system_time_ns: u64) {
        let gpa = ::config::microvm::DEFAULT_PVCLOCK_PAGE as u64;
        // Odd version signals "update in progress".
        *pvclock_version += 1;
        let _ = vmem.write_bytes(gpa, &pvclock_version.to_le_bytes());
        // Update system_time (offset 16).
        let _ = vmem.write_bytes(gpa + 16, &system_time_ns.to_le_bytes());
        // Even version signals "stable snapshot".
        *pvclock_version += 1;
        let _ = vmem.write_bytes(gpa, &pvclock_version.to_le_bytes());
    }
}

//==================================================================================================
// Tests
//==================================================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use ::std::sync::atomic::AtomicUsize;

    #[test]
    fn run_pending_guard_tracks_vcpu_entry() {
        let run_state: RunState = RunState::new();
        {
            let _guard: RunPendingGuard<'_> = RunPendingGuard::new(&run_state);
            assert!(run_state.is_pending());
        }
        assert!(!run_state.is_pending());
    }

    #[test]
    fn cancellation_is_skipped_outside_vcpu_entry() {
        let run_state: RunState = RunState::new();
        let mut attempts: usize = 0;

        let cancelled: bool = run_state.cancel_if_pending(|| attempts += 1);

        assert!(!cancelled);
        assert_eq!(attempts, 0);
    }

    #[test]
    fn cancellation_runs_under_cancel_gate() {
        // The crash fixed here came from cancellation overlapping snapshot/teardown. This locks in
        // the invariant that prevents it: the cancel closure runs while `cancel_gate` is held, so
        // it is mutually exclusive with `finish_run`. A cross-thread `try_lock` on the held gate
        // must fail for the whole closure.
        let run_state: Arc<RunState> = Arc::new(RunState::new());
        run_state.begin_run();

        let mut gate_held_during_cancel: bool = false;
        run_state.cancel_if_pending(|| {
            let probe: Arc<RunState> = run_state.clone();
            gate_held_during_cancel =
                std::thread::spawn(move || probe.cancel_gate.try_lock().is_err())
                    .join()
                    .expect("prober thread panicked");
        });

        assert!(gate_held_during_cancel, "cancel closure must run while holding cancel_gate");
    }

    #[test]
    fn cancellation_retries_until_run_finishes() {
        let run_state: Arc<RunState> = Arc::new(RunState::new());
        let attempts: Arc<AtomicUsize> = Arc::new(AtomicUsize::new(0));
        let guard: RunPendingGuard<'_> = RunPendingGuard::new(run_state.as_ref());

        let worker_state: Arc<RunState> = run_state.clone();
        let worker_attempts: Arc<AtomicUsize> = attempts.clone();
        let worker: std::thread::JoinHandle<()> = std::thread::spawn(move || {
            cancel_while_run_pending(worker_state.as_ref(), || {
                worker_attempts.fetch_add(1, Ordering::SeqCst);
            });
        });

        while attempts.load(Ordering::SeqCst) < 2 {
            std::thread::yield_now();
        }

        // Ends the run through `cancel_gate`, exactly as the VMM loop does.
        drop(guard);
        worker.join().expect("cancel worker panicked");

        assert!(attempts.load(Ordering::SeqCst) >= 2);
        assert!(!run_state.is_pending());
    }
}
