.\"
.\" Copyright(C) 2011-2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.\"=============================================================================
.\"
.TH "mv" 1 "July 2014" "Commands" "The Nanvix User Programmer's Manual"
.\"
.\"=============================================================================
.\"
.SH NAME
.\"
mv \- Moves or renames files
.\"
.\"=============================================================================
.\"
.\"
.SH "SYNOPSIS"
.\"
.BI "mv [" "options" "] <" "name1" "> <" "name2" ">"
.\"
.\"=============================================================================
.\"
.SH "DESCRIPTION"
.\"
The
.BR mv
utility changes the name of file 
.IR name1 " to " name2 .
If 
.IR name2
is a directory,
.IR name1
is moved to that directory with its original file-name.
Moreover, if
.IR name2
already exists, it is removed before 
.IR name1
is renamed.
.\"
.\"=============================================================================
.\"
.SH "OPTIONS"
.\"
.TP 
.BR --help
Display help information and exits.

.TP
.BR --version
Display program version and exits.
.\"
.\"=============================================================================
.\"
.SH AUTHOR
.\"
Pedro H. Penna <pedrohenriquepenna@gmail.com>
.\"
