# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

name: "Nanvix Benchmark (Self-Hosted)"

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'ready_for_review'
    branches:
      - 'dev'

  push:
    branches:
      - 'dev'

# Cancel previous running actions for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' }}

env:
  TARGET_BRANCH: ${{ github.ref_name }}
  SCCACHE: "/usr/local/bin/sccache"

jobs:
  precheck:
    uses: nanvix/nanvix/.github/workflows/branch-up-to-date.yml@dev
    secrets: inherit

  benchmark:
    name: "Nanvix Benchmark (self-hosted)"
    needs: precheck
    timeout-minutes: 240
    strategy:
      matrix:
        build-type: [release]
        arch: [X64]
    runs-on: [self-hosted, Linux, X64, baremetal]
    permissions:
      contents: read
      pull-requests: write

    # Only run the benchmark for:
    # - Non-merge pushes to 'dev'.
    # - Non-draft PRs.
    if: |
      (
        github.event_name != 'push' ||
        github.event.head_commit == null ||
        !startsWith(github.event.head_commit.message, 'Merge ')
      ) && (
        github.event_name != 'pull_request_target' ||
        !github.event.pull_request.draft
      ) && needs.precheck.outputs.up_to_date == 'true'

    steps:
    - uses: actions/checkout@v6

    - name: "Benchmark"
      uses: ./.github/actions/benchmark
      with:
        arch: '${{ matrix.arch }}'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        benchmark_list: |
          boot-time
          cold-start
          cold-start-l2
          cold-start-uvm
          concurrent
          concurrent-l2
          echo-breakdown
          echo-breakdown-l2
          round-trip-latency
          warm-start
          warm-start-l2
          warm-start-vmm


    - name: "Cleanup images directory"
      if: always()
      run: sudo rm -rf images
      shell: bash

    - name: "Upload logs in case of benchmark failures"
      if: failure()
      uses: actions/upload-artifact@v5
      with:
        name: nanvix-benchmark-logs-${{ github.event.pull_request.number || github.run_number }}-${{ matrix.build-type }}-${{ matrix.arch }}
        # Overwrite to limit the amount of storage we use.
        overwrite: 'true'
        path: |
          logs/
          **/*.log
          **/*.out
          **/*.err
          bench_*.txt
