# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

name: Test

on:
  workflow_call:
    inputs:
      release:
        description: 'Release type'
        required: true
        default: 'release'
        type: string
      log-level:
        description: 'Log level'
        required: true
        default: 'trace'
        type: string
    secrets:
      hostname:
        description: 'Hostname'
        required: true
      username:
        description: 'Username'
        required: true
      sshkey:
        description: 'SSH key'
        required: true
      portnum:
        description: 'Port number'
        required: true

env:
  TARGET_BRANCH: ${{ github.ref_name }}
  RELEASE_TYPE: ${{ inputs.release }}
  LOG_LEVEL: ${{ inputs.log-level }}

jobs:
  test-qemu-pc:
    name: Test (qemu-pc)
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH, RELEASE_TYPE, LOG_LEVEL
        script: |
          cd github/nanvix-${TARGET_BRANCH}-${RELEASE_TYPE}
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=${LOG_LEVEL} --target-machine=qemu-pc --${RELEASE_TYPE} --test

  test-qemu-isapc:
    name: Test (qemu-isapc)
    needs: test-qemu-pc
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH, RELEASE_TYPE, LOG_LEVEL
        script: |
          cd github/nanvix-${TARGET_BRANCH}-${RELEASE_TYPE}
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=${LOG_LEVEL} --target-machine=qemu-isapc --${RELEASE_TYPE} --test

  test-qemu-baremetal:
    name: Test (qemu-baremetal)
    needs: test-qemu-isapc
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH, RELEASE_TYPE, LOG_LEVEL
        script: |
          cd github/nanvix-${TARGET_BRANCH}-${RELEASE_TYPE}
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=${LOG_LEVEL} --target-machine=qemu-baremetal --${RELEASE_TYPE} --test

  test-microvm:
    name: Test (microvm)
    needs: test-qemu-baremetal
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH, RELEASE_TYPE, LOG_LEVEL
        command_timeout: 30m
        script: |
          cd github/nanvix-${TARGET_BRANCH}-${RELEASE_TYPE}
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=${LOG_LEVEL} --target-machine=microvm --${RELEASE_TYPE} --test

  test-hyperlight:
    name: Test (hyperlight)
    needs: test-microvm
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH, RELEASE_TYPE, LOG_LEVEL
        command_timeout: 30m
        script: |
          cd github/nanvix-${TARGET_BRANCH}-${RELEASE_TYPE}
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=${LOG_LEVEL} --target-machine=hyperlight --${RELEASE_TYPE} --test
