# Copyright(c) 2011-2024 The Maintainers of Nanvix.
# Licensed under the MIT License.

name: x86 Debug

on:
  push:
    branches:
      - 'enhancement-*'
      - 'feature-*'
      - 'bugfix-*'
      - 'dev'

env:
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          if [ "${TARGET_BRANCH}" = "dev" ]; then
            find . -type d -name 'nanvix-*-debug' -not -name 'nanvix-dev-debug' -exec rm -rf {} +
            cd nanvix-dev-debug
            git fetch origin
            git reset --hard origin/${TARGET_BRANCH}
          else
            if [ ! -d "nanvix-${TARGET_BRANCH}-debug" ]; then
              git clone https://github.com/nanvix/nanvix.git --branch ${TARGET_BRANCH} nanvix-${TARGET_BRANCH}-debug
            else
              cd nanvix-${TARGET_BRANCH}-debug
              git fetch origin
              git reset --hard origin/${TARGET_BRANCH}
            fi
          fi

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Clippy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-isapc --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-pc --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-baremetal --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=microvm --lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-isapc --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-pc --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-baremetal --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=microvm --build

  test-qemu-isapc:
    name: Test (qemu-isapc)
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-isapc --test

  test-qemu-pc:
    name: Test (qemu-pc)
    needs: [test-qemu-isapc]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-pc --test

  test-qemu-baremetal:
    name: Test (qemu-baremetal)
    needs: [test-qemu-pc]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-baremetal --test

  test-microvm:
    name: Test (microvm)
    needs: [test-qemu-baremetal]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=microvm --test

  test-nanvixd:
    name: Test (nanvixd)
    needs: [test-microvm]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd nanvix-${TARGET_BRANCH}-debug
          sudo -E ./test.sh 127.0.0.1 8181 && exit 1 || exit 0


  cleanup:
    name: Cleanup
    needs: [test-nanvixd]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          if [ "${TARGET_BRANCH}" = "dev" ]; then
            cd nanvix-dev-debug
            git remote prune origin
          fi
