# Copyright(c) 2011-2024 The Maintainers of Nanvix.
# Licensed under the MIT License.

name: x86 Release

concurrency:
  group: x86-release
  cancel-in-progress: false

on:
  push:
    branches:
      - 'enhancement-*'
      - 'feature-*'
      - 'bugfix-*'
      - 'dev'

env:
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          if [ "${TARGET_BRANCH}" = "dev" ]; then
            find . -type d -name 'nanvix-*-release' -not -name 'nanvix-dev-release' -exec rm -rf {} +
            cd github/nanvix-dev-release
            git fetch origin
            git reset --hard origin/${TARGET_BRANCH}
          else
            if [ ! -d "github/nanvix-${TARGET_BRANCH}-release" ]; then
              git clone https://github.com/nanvix/nanvix.git --branch ${TARGET_BRANCH} github/nanvix-${TARGET_BRANCH}-release
            else
              cd github/nanvix-${TARGET_BRANCH}-release
              git fetch origin
              git reset --hard origin/${TARGET_BRANCH}
            fi
          fi

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Clippy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-isapc --release --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-pc --release --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-baremetal --release --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=microvm --release --lint
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=hyperlight --release --lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-isapc --release --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-pc --release --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-baremetal --release --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=microvm --release --build
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=hyperlight --release --build

  test-qemu-isapc:
    name: Test (qemu-isapc)
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-isapc --release --test

  test-qemu-pc:
    name: Test (qemu-pc)
    needs: [test-qemu-isapc]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-pc --release --test

  test-qemu-baremetal:
    name: Test (qemu-baremetal)
    needs: [test-qemu-pc]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=qemu-baremetal --release --test

  test-microvm:
    name: Test (microvm)
    needs: [test-qemu-baremetal]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=microvm --release --test

  test-hyperlight:
    name: Test (hyperlight)
    needs: [test-microvm]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          cd github/nanvix-${TARGET_BRANCH}-release
          python3 scripts/ci.py --toolchain-dir=$HOME/toolchain --target-arch=x86 --log-level=trace --target-machine=hyperlight --release --test

  cleanup:
    name: Cleanup
    needs: [test-hyperlight]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.hostname }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        port: ${{ secrets.portnum }}
        envs: TARGET_BRANCH
        script: |
          if [ "${TARGET_BRANCH}" = "dev" ]; then
            cd github/nanvix-dev-release
            git remote prune origin
          fi
