# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "linux-app"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
description = "Linux App Benchmark"
homepage.workspace = true

[[bin]]
name = "linux-app"

[dependencies]
nvx = { workspace = true, features = ["allocator"] }
posix = { workspace = true, features = ["syscall", "allocator"] }

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }
